### ISSUE TITLE
Vanishing route line is not animated

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3214] opened 2020-06-22 17:45 UTC
When testing `1.0.0-qa.2020.w25` I'm noticing that the vanishing route line's progress change is not animated:
![ezgif com-optimize (42)](https://user-images.githubusercontent.com/16925074/85318728-c92b4c80-b4c0-11ea-97ee-1536485d2746.gif)

/cc @cafesilencio @abhishek1508 @Guardiola31337

**Comment by cafesilencio** [comment] 2020-06-22 19:52
This is confusing. When I run the basic activity from master this is what I see:

![20200622_125020](https://user-images.githubusercontent.com/2249818/85329311-17235e80-b487-11ea-9611-768d9d6cf818.gif)

**Comment by cafesilencio** [comment] 2020-06-22 20:22
I can see on a longer route it looks a bit more choppy. The animation duration is 900ms. Each animation 'tick' will make 3 calls to update the gradient for the shield line, the route line and the traffic line. There are many 'ticks' in every 900ms animation window. @LukasPaczos do you have any insight into what happens on the map side? Could some of the calls be getting ignored because there are too many in short period of time?

**Comment by LukasPaczos** [comment] 2020-06-23 10:06
> Could some of the calls be getting ignored because there are too many in short period of time?

The map render will most likely coalesce the calls if they are coming in faster than we are able to render, but it would not result in a jump. It would still be animated as smoothly as possible, but missing a couple of frames.

**Comment by cafesilencio** [comment] 2020-06-23 18:02
I see the value animator updating all three route lines about 90 times per second. That's about every 11 ms.

**Comment by Guardiola31337** [comment] 2020-06-24 15:39
This is easily reproducible running the `ReplayActivity` from the `examples` test app 👀 

![replay_location_engine_activity_vanishing_route_line_not_animated](https://user-images.githubusercontent.com/1668582/85586876-4b298b80-b60f-11ea-9f99-3bf6c05faa7e.gif)

cc @cafesilencio @LukasPaczos

**Comment by cafesilencio** [comment] 2020-06-24 17:44
Looks like we need to wait for a maps gl update. There was a slack
conversation about it.

**Comment by LukasPaczos** [comment] 2020-06-24 17:53
Yes, looks like this also depends on https://github.com/mapbox/mapbox-gl-js/pull/9694.

/cc @1ec5 @captainbarbosa

**Comment by Guardiola31337** [comment] 2020-07-08 13:06
Cross-posting from https://github.com/mapbox/mapbox-navigation-android/pull/3284#pullrequestreview-444268267 so these comments don't get lost

> Noting a couple interesting things that I found though:
>
> - We keep vanishing the route line when off-route is happening 👀 
>
> ![examples_test_app_vanishing_when_offroute](https://user-images.githubusercontent.com/1668582/86845146-14279100-c077-11ea-96c5-dc389fb7f352.gif)
>
> - When putting the app in the background and bringing it back to the foreground the vanishing line is not updated - note how it catches up quickly 👀 
>
> ![examples_test_app_vanishing_catches_up_after_background_foreground](https://user-images.githubusercontent.com/1668582/86845689-e0993680-c077-11ea-9c27-d9bd8a4368b2.gif)
>
> It seems that route progress updates are stopped when in the background.
>
> Also noticed that in that example (`FragmentNavigationActivity`) the route line is not re-drawn after putting the app in the background and bringing it back to the foreground but that may be the specific setup from that example.
>
> Feel free to merge here and cut separate tickets to investigate ☝️ further.

cc @LukasPaczos @cafesilencio

**Comment by cafesilencio** [comment] 2020-07-09 15:44
This should be resolved since getting the maps GL update.

**Comment by cafesilencio** [comment] 2020-07-09 16:38
Closing this issue as I believe it's resolved.

**Closed by cafesilencio** 2020-07-09 16:38 UTC
Labels: UI SDK v1+
