### ISSUE TITLE
error when starting the navigation with the optimized route

### ISSUE THREAD

**Issue by rayo3199** [mapbox/mapbox-navigation-android#4405] opened 2021-05-17 19:42 UTC
Hello I am trying to execute the navigation with an optimized route but I have read that the optimization api does not have the voice instructions they will implement or what other solution do they give me

Android API: 15+
Mapbox Navigation SDK version: 0.42.6

Steps to trigger behavior
Build a client with MapboxOptimization builder
Get a route back as response and add it to the map
Start the navigation with NavigationLauncher
Expected behavior
Navigation starts

Actual behavior
The navigation screen comes in, but the current position or the route can not be seen. The x button is unresponsive and the route button, when pressed, returns:
FATAL EXCEPTION:
java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.services.android.navigation.v5.navigation.camera.Camera com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.getCameraEngine()' on a null object reference

This is my code can you help me?

private void getOptimizedRoute(@nonnull final Style styleE, List coordinates) {
optimizedClient = MapboxOptimization.builder()
.source(FIRST)
.destination(ANY)
.coordinates(coordinates)
.overview(DirectionsCriteria.OVERVIEW_FULL)
.profile(DirectionsCriteria.PROFILE_WALKING)
.accessToken(getString(R.string.token))
.build();

    optimizedClient.enqueueCall(new Callback<OptimizationResponse>() {
        @Override
        public void onResponse(@NotNull Call<OptimizationResponse> call, @NotNull Response<OptimizationResponse> response) {
            if (!response.isSuccessful()) {
                Timber.d(getString(R.string.no_success));
                Toast.makeText(Mapboxnavigation.this, "no ok", Toast.LENGTH_SHORT).show();
            } else {
                if (response.body() != null) {
                    List<DirectionsRoute> routes = response.body().trips();
                    if (routes != null) {
                        if (routes.isEmpty()) {
                            Timber.d("%s size = %s", getString(R.string.successful_but_no_routes), routes.size());
                            Toast.makeText(Mapboxnavigation.this, R.string.successful_but_no_routes,
                                    Toast.LENGTH_SHORT).show();
                        } else {
                            // Get most optimized route from API response
                             optimizedRoute = routes.get(0);

                            //Toast.makeText(getApplicationContext(),""+optimizedRoute.toString(),Toast.LENGTH_LONG).show();
                            drawOptimizedRoute(style, optimizedRoute);

                        }
                    } else {
                        Timber.d("list of routes in the response is null");
                        Toast.makeText(Mapboxnavigation.this, String.format(getString(R.string.null_in_response),
                                "The Optimization API response's list of routes"), Toast.LENGTH_SHORT).show();
                    }
                } else {
                    Timber.d("response.body() is null");
                    Toast.makeText(Mapboxnavigation.this, String.format(getString(R.string.null_in_response),
                            "The Optimization API response's body"), Toast.LENGTH_SHORT).show();
                }
            }
        }

        @Override
        public void onFailure(@NotNull Call<OptimizationResponse> call, @NotNull Throwable throwable) {
            Timber.d("Error: %s", throwable.getMessage());
        }
    });
}
public void onClick(View view) {
getRoute2();

        }
    });

}

private void getRoute2() {

                     options = NavigationLauncherOptions.builder()
                            .directionsRoute(optimizedRoute)
                            .shouldSimulateRoute(true)
                            .build();

                    NavigationLauncher.startNavigation(Mapboxnavigation
                            .this, options);
                    

                }

**Comment by rayo3199** [comment] 2021-05-17 19:43
@zugaldia Can you give me an alternative to generate the navigation with the optimized route?

**Comment by zugaldia** [comment] 2021-05-17 19:52
This is again a dupe of https://github.com/mapbox/mapbox-navigation-android/issues/4399 which was just closed.

@rayo3199 current documentation for custom routes is [available here](https://docs.mapbox.com/android/navigation/guides/custom-routes/). For additional questions, please [contact our support team](https://docs.mapbox.com/help/).

**Closed by zugaldia** 2021-05-17 19:52 UTC
