### ISSUE TITLE
Drop-in UI crash with Android 4.2.2-4.4.2 devices

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#258] opened 2017-09-21 14:46 UTC
Hey,

I've downloaded your [sample project](https://github.com/mapbox/mapbox-navigation-android/tree/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity) today.

Running on a 

- Google Nexus 6 (Android 7.1.1) 
- MOBISTEL Cynus E4 (Android 5.1)
- Ulefone Be Touch 2 (Android 5.1) 

there is no crash. 

Different with these devices (Device | Android Version):
- Samsung Galaxy S3 (GT-I9300) | 4.3
- HTC One X | 4.2.2
- Huawei MediaPad T1-701u | 4.4.2
- Samsung Galaxy S3 mini (GT-I8200N) | 4.2.2

If I open the drop-in UI view and click on the map for route calculation everything is fine. But if I press for e.g. "Launch navigation with route"-button the app crashes

```
09-21 16:03:50.440 11520-11520/com.mapbox.services.android.navigation.testapp W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40e92a08)
09-21 16:03:50.495 11520-11520/com.mapbox.services.android.navigation.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.services.android.navigation.testapp/com.mapbox.services.android.navigation.ui.v5.NavigationView}: android.view.InflateException: Binary XML file line #19: Error inflating class com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView
                                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2463)
                                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
                                                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:162)
                                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    at android.os.Looper.loop(Looper.java:158)
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5751)
                                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                    at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
                                                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                                                 Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView
                                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                                    at com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(NavigationView.java:109)
                                                                                                    at android.app.Activity.performCreate(Activity.java:5165)
                                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1103)
                                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
                                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520) 
                                                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:162) 
                                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366) 
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    at android.os.Looper.loop(Looper.java:158) 
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5751) 
                                                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                                    at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083) 
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850) 
                                                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                                                    at com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(NavigationView.java:109) 
                                                                                                    at android.app.Activity.performCreate(Activity.java:5165) 
                                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1103) 
                                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419) 
                                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520) 
                                                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:162) 
                                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366) 
                                                                                      ```

**Comment by danesfeder** [comment] 2017-09-21 14:49
@P-Zenker I'll look into this - looks like it's related to API 19

**Comment by davols** [comment] 2017-09-22 07:32
Had a quick glance yesterday. Pretty sure it's related to VectorDrawables, need to use vectordrawablecompat for < 21.  Having some issues in my navigation project as well.

**Comment by danesfeder** [comment] 2017-09-22 15:22
Looks like using custom attributes using`?attr/` to set the theme colors won't fly below API 21.

Going to have to work on a fix to set the colors at runtime.  We are going to let users of the drop-in UI set custom colors to style the Views.

**Comment by davols** [comment] 2017-09-25 12:31
You're probably right.

Another stacktrace with the example app from `master`
Sony V | 4.1.2
`Caused by: android.content.res.Resources$NotFoundException: File res/drawable/instruction_background.xml from drawable resource ID #0x7f0200c1`

```
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.services.android.navigation.testapp/com.mapbox.services.android.navigation.ui.v5.NavigationView}: android.view.InflateException: Binary XML file line #19: Error inflating class com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2071)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096)
      at android.app.ActivityThread.access$600(ActivityThread.java:138)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loop(Looper.java:213)
      at android.app.ActivityThread.main(ActivityThread.java:4787)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:511)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
      at dalvik.system.NativeStart.main(Native Method)
  Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView
      at android.view.LayoutInflater.createView(LayoutInflater.java:613)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
      at com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(NavigationView.java:109)
      at android.app.Activity.performCreate(Activity.java:5008)
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2035)
      ... 11 more
  Caused by: java.lang.reflect.InvocationTargetException
      at java.lang.reflect.Constructor.constructNative(Native Method)
      at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
      at android.view.LayoutInflater.createView(LayoutInflater.java:587)
      ... 22 more
  Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
      at android.view.LayoutInflater.createView(LayoutInflater.java:613)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:807)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
      at android.view.View.inflate(View.java:16295)
      at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.init(InstructionView.java:181)
      at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.<init>(InstructionView.java:84)
      at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.<init>(InstructionView.java:79)
      ... 25 more
  Caused by: java.lang.reflect.InvocationTargetException
      at java.lang.reflect.Constructor.constructNative(Native Method)
      at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
      at android.view.LayoutInflater.createView(LayoutInflater.java:587)
      ... 35 more
  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/instruction_background.xml from drawable resource ID #0x7f0200c1
      at android.content.res.Resources.loadDrawable(Resources.java:1923)
      at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
      at android.view.View.<init>(View.java:3373)
      at android.view.View.<init>(View.ja
```

**Comment by Danny-James** [comment] 2017-09-26 13:12
@davols @danesfeder I'm Also Getting This Same Error On Android 4.12 - With The Same LogCat Shown Above.

**Comment by danesfeder** [comment] 2017-09-26 13:36
@Danny-James @davols @P-Zenker Keep an eye out for a PR to fix this later this week

**Comment by Danny-James** [comment] 2017-09-26 15:53
Thank You @danesfeder!

**Comment by johnwallco** [comment] 2017-09-30 21:28
Same issue when trying to drop an InstructionView into a custom navigation activity.

**Comment by danesfeder** [comment] 2017-10-02 13:15
@johnwallco Yeah those custom attributes are only supported API 21 and above - removing them should get rid of the inflation exception in API 19

**Comment by Danny-James** [comment] 2017-10-02 13:46
Any News On A Fix @danesfeder I'm Currently Using.

```
// Mapbox Maps SDK
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.3@aar') {
        transitive=true
    }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT'
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0-SNAPSHOT'
    compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.1.0'
    compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
```

**Comment by danesfeder** [comment] 2017-10-02 14:14
@Danny-James Keep an eye on https://github.com/mapbox/mapbox-navigation-android/pull/286 the fix will be included there

**Comment by Danny-James** [comment] 2017-10-02 14:30
@danesfeder Take a Look At My LogCat Below On My Android 4.1.2 - May Be Useful When Fixing The Problem
```
10-02 15:22:52.668 631-2065/? I/ActivityManager: START u0 {cmp=uk.co.ainscough.routeinfo/com.mapbox.services.android.navigation.ui.v5.NavigationView (has extras)} from pid 23534
10-02 15:22:52.688 23534-23534/uk.co.ainscough.routeinfo W/dalvikvm: VFY: unable to resolve virtual method 50629: Lcom/mapbox/services/android/navigation/v5/navigation/NavigationEngine;.quitSafely ()Z
10-02 15:22:52.928 23534-23534/uk.co.ainscough.routeinfo W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41dff438)
10-02 15:22:52.958 23534-23534/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{uk.co.ainscough.routeinfo/com.mapbox.services.android.navigation.ui.v5.NavigationView}: android.view.InflateException: Binary XML file line #19: Error inflating class com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2108)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2133)
                                                                               at android.app.ActivityThread.access$600(ActivityThread.java:142)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                               at android.os.Looper.loop(Looper.java:137)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4895)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                               at dalvik.system.NativeStart.main(Native Method)
                                                                            Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                               at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                               at com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(NavigationView.java:109)
                                                                               at android.app.Activity.performCreate(Activity.java:5042)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2072)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2133) 
                                                                               at android.app.ActivityThread.access$600(ActivityThread.java:142) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                               at android.os.Looper.loop(Looper.java:137) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4895) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                                               at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                               at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                               at com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(NavigationView.java:109) 
                                                                               at android.app.Activity.performCreate(Activity.java:5042) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2072) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2133) 
                                                                               at android.app.ActivityThread.access$600(ActivityThread.java:142) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                               at android.os.Looper.loop(Looper.java:137) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4895) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.constraint.ConstraintLayout
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                               at android.view.LayoutInflater.parseInclude(LayoutInflater.java:807)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                               at android.view.View.inflate(View.java:16119)
                                                                               at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.init(InstructionView.java:181)
                                                                               at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.<init>(InstructionView.java:84)
                                                                               at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.<init>(InstructionView.java:79)
                                                                               at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                               at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                               at com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(NavigationView.java:109) 
                                                                               at android.app.Activity.performCreate(Activity.java:5042) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2072) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2133) 
                                                                               at android.app.ActivityThread.access$600(ActivityThread.java:142) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                               at android.os.Looper.loop(Looper.java:137) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4895) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                                               at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                               at android.view.LayoutInflater.parseInclude(LayoutInflater.java:807) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:736) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                               at android.view.View.inflate(View.java:16119) 
                                                                               at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.init(InstructionView.java:181) 
                                                                               at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.<init>(InstructionView.java:84) 
                                                                               at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.<init>(InstructionView.java:79) 
                                                                               at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                               at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                               at com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(NavigationView.java:109) 
                                                                               at android.app.Activity.performCreate(Activity.java:5042) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2072) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2133) 
                                                                               at android.app.ActivityThread.access$600(ActivityThread.java:142) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                               at android.os.Looper.loop(Looper.java:137) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4895) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: android.content.res.Resources$NotFoundException: File res/drawable/instruction_background.xml from drawable resource ID #0x7f0200e9
                                                                               at android.content.res.Resources.loadDrawable(Resources.java:1918)
                                                                               at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
                                                                               at android.view.View.<init>(View.java:3336)
                                                                           	at android.view.View.<
10-02 15:22:52.968 631-631/? W/ActivityManager:   Force finishing activity uk.co.ainscough.routeinfo/com.mapbox.services.android.navigation.ui.v5.NavigationView
````

**Comment by danesfeder** [comment] 2017-10-02 18:58
I think I narrowed this down to `?attr/` being used in custom drawables we are using for the backgrounds in some views

**Comment by danesfeder** [comment] 2017-10-02 19:03
Running on `4.4.2` with custom attributes removed from `Drawable`s an hardcoded to grey 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8434572/31094316-bafd9ddc-a782-11e7-8b35-9489780e326f.gif)

**Comment by Danny-James** [comment] 2017-10-02 19:06
Great work @danesfeder, So will this just be hard coded to white?

**Comment by danesfeder** [comment] 2017-10-02 19:09
@Danny-James Thanks and no, I'm going to try to set the color of the drawables programmatically so you can still customize the theme (currently being worked in #286).  This will eliminate the custom attribute tags in the drawable XML

**Comment by Danny-James** [comment] 2017-10-02 19:11
Great, I Look Forward To This Being Released.

Many Thanks For Looking Into A Fix For This.

**Comment by danesfeder** [comment] 2017-12-04 15:01
This has been fixed for a while - was related to using custom attributes to color drawables

**Closed by danesfeder** 2017-12-04 15:01 UTC
