### ISSUE TITLE
BadTokenException caused by Toast

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#1291] opened 2018-09-13 17:38 UTC
**Android API:** 25 (Google Nexus 5)
**Mapbox Navigation SDK version:** 0.18.0

### Steps to trigger behavior
```
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import android.widget.Toast;

import com.mapbox.api.directions.v5.DirectionsCriteria;
import com.mapbox.api.directions.v5.models.DirectionsResponse;
import com.mapbox.api.directions.v5.models.DirectionsRoute;
import com.mapbox.geojson.Point;
import com.mapbox.mapboxsdk.Mapbox;
import com.mapbox.mapboxsdk.camera.CameraUpdateFactory;
import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.geometry.LatLngBounds;
import com.mapbox.mapboxsdk.maps.MapView;
import com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute;
import com.mapbox.services.android.navigation.v5.navigation.NavigationRoute;

import java.util.Locale;

import catchup.com.mapboxtest.R;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

public class MainActivity extends AppCompatActivity {

    private DirectionsRoute directionsRoute;
    private NavigationMapRoute navigationMapRoute;
    private MapView mapView;

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mapView = findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(mapboxMap -> {

            Point origin = Point.fromLngLat(9.910877, 57.041474);
            Point destination = Point.fromLngLat(15.819441, 38.017852);

            LatLngBounds latLngBounds = new LatLngBounds.Builder()
                    .include(new LatLng(origin.latitude(), origin.longitude()))
                    .include(new LatLng(destination.latitude(), destination.longitude()))
                    .build();
            mapboxMap.easeCamera(CameraUpdateFactory.newLatLngBounds(latLngBounds, 200), 2000);

            NavigationRoute.builder(MainActivity.this)
                    .accessToken(Mapbox.getAccessToken())
                    .origin(origin)
                    .destination(destination)
                    .voiceUnits(DirectionsCriteria.METRIC)
                    .language(Locale.GERMAN)
                    .profile(DirectionsCriteria.PROFILE_DRIVING)
                    .build()
                    .getRoute(new Callback<DirectionsResponse>() {
                        @Override
                        public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                            try {
                                directionsRoute = response.body().routes().get(0);
                                if (directionsRoute != null) {
                                    Toast.makeText(MainActivity.this, "First Toast", Toast.LENGTH_LONG).show();
                                    if (navigationMapRoute != null) {
                                        navigationMapRoute.removeRoute();
                                    } else {
                                        navigationMapRoute = new NavigationMapRoute(null, mapView, mapboxMap);
                                    }
                                    navigationMapRoute.addRoute(directionsRoute);
                                }
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }

                        @Override
                        public void onFailure(Call<DirectionsResponse> call, Throwable t) {
                        }
                    });
        });
    }

    // Add the mapView lifecycle to the activity's lifecycle methods
    @Override
    public void onResume() {
        super.onResume();
        if (mapView != null) {
            mapView.onResume();
        }
    }

    @Override
    protected void onStart() {
        super.onStart();
        if (mapView != null) {
            mapView.onStart();
        }
    }

    @Override
    protected void onStop() {
        super.onStop();
        mapView.onStop();
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }
}
```
### Expected behavior
Show a toast

### Actual behavior
```09-13 18:44:31.829 19109-19109/com.mapboxtest E/mbgl: {.com.mapboxtest}[JNI]: Error setting property: icon-size [5]: Input/output pairs for "interpolate" expressions must be arranged with input values in strictly ascending order.
09-13 18:44:31.829 19109-19109/com.mapboxtest W/art: Attempt to remove non-JNI local reference, dumping thread
    Attempt to remove non-JNI local reference, dumping thread
    Attempt to remove non-JNI local reference, dumping thread
09-13 18:44:31.839 19109-19109/com.mapboxtest D/AndroidRuntime: Shutting down VM
09-13 18:44:31.839 19109-19109/com.mapboxtest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapboxtest, PID: 19109
    android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@72d4633 is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.widget.Toast$TN.handleShow(Toast.java:459)
        at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### Solution
- Show the toast after `navigationMapRoute.addRoute(directionsRoute);`

But maybe you can fix it in your SDK, if it's possible and needed / wished.

**Comment by Guardiola31337** [comment] 2018-09-13 19:52
Hey @P-Zenker 👋 thanks for reaching out and report your issue.

Yeah, that's an Android known issue (here you can :eyes: why it's caused https://github.com/drakeet/ToastCompat#why) although unrelated to the SDK.

Please feel free to reopen if you find this is caused by the SDK. Thanks again!

Closing as non actionable.

**Closed by Guardiola31337** 2018-09-13 19:52 UTC

**Comment by P-Zenker** [comment] 2018-09-14 07:51
Ah, good to know. Thanks for your explanation!
