### ISSUE TITLE
Metalava misconfigured for Kotlin value classes

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#5852] opened 2022-05-24 10:35 UTC
https://github.com/mapbox/mapbox-navigation-android/pull/5842 introduced a Kotlin `value class` that even when marked `internal` was producing an entry in metalava's API files. For example:
```kotlin
@JvmInline
internal value class RouteLineTrimOffset(val offset: Double)
```
results in:
```
   public final class RouteLineTrimOffset {
    ctor public RouteLineTrimOffset(double offset);
    method public double getOffset();
    property public final double offset;
  }
```

**Comment by Guardiola31337** [comment] 2022-05-24 16:55
The problem is that the Metalava filter https://github.com/mapbox/mapbox-navigation-android/blob/17e3a68083d76dbeb5cd336a9c0337c5f26b7ef4/Makefile#L202 is not working because there are no other classes or packages under `internal` so the filter should be `internal.route.line`. For now, as there's only that class under `internal` moving it out from `route.line` in https://github.com/mapbox/mapbox-navigation-android/commit/17e3a68083d76dbeb5cd336a9c0337c5f26b7ef4 so that Metalava doesn't add `RouteLineTrimOffset` to the public changes (`current.txt`) even being `public` 👍 

In any case, we shouldn't push that into the `main` because that class was moved under the `internal` package due to this other issue https://github.com/mapbox/mapbox-navigation-android/issues/5851 which IMO we should address in the first place.

cc @LukasPaczos @cafesilencio @RingerJK

**Comment by Guardiola31337** [comment] 2022-05-24 16:57
BTW noting that OP wasn't failing on `main` because we have two different packages under [`internal`](https://github.com/mapbox/mapbox-navigation-android/tree/main/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal).

**Comment by RingerJK** [comment] 2022-06-01 13:42
let's try to update metalava

**Comment by Guardiola31337** [comment] 2022-06-01 18:31
Tested OP in https://github.com/mapbox/mapbox-navigation-android/pull/5883 with a fake `internal` `@JvmInline` `value class` and it's working as expected now i.e. no changes are added to `current.txt` 👍

**Closed** 2022-06-02 21:41 UTC
Labels: op-ex
