### ISSUE TITLE
Android: Choice of Navigation UI Buttons

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#527] opened 2017-11-22 12:00 UTC
What i'm looking for is an option to specifiy which buttons are visible when the NavigationUI is shown, the reason for this is in the application I have developed we have an internal routing department where the user is able to submit feedback to, they can then amend the route the user is using.

However, the new Navigation UI shows a feedback button, this may get confusing, could you please provide an option so i can decide if i would like to show or hide the Volume Button and Feedback Button.

Many Thanks.

**Comment by danesfeder** [comment] 2017-11-28 14:24
Thanks @Danny-James, we can look into adding this as options in `NavigationViewOptions` @ericrwolfe Does iOS have an equivalent of this?

**Comment by Danny-James** [comment] 2017-11-28 15:29
Cheers @danesfeder 👍

**Comment by Danny-James** [comment] 2018-03-12 09:38
@danesfeder Did this ever get included in any of the latest releases? also just another quick question did you manage to include the `boolean` value in the `NavigationOptions` to disable re-routing?

Cheers!

**Comment by Guardiola31337** [comment] 2018-03-22 09:05
Hey @Danny-James 👋 Thanks for reaching out and report your problem.

Closing here as duplicate of #634 

Let us know if you have any other questions!

**Closed by Guardiola31337** 2018-03-22 09:05 UTC
