### ISSUE TITLE
MapboxInvalidModuleException in v2.0.0 Navigation SDK

### ISSUE THREAD

**Issue by samcrawford** [mapbox/mapbox-navigation-android#5100] opened 2021-11-11 16:35 UTC
Sentry has caught 11 instances of this exception occurring in my app since moving to Navigation SDK 2.0.0:

```
MapboxInvalidModuleException
NavigationTripNotification has been excluded from build but a correct alternative was not provided.
Make sure that:
- Your custom module implements com.mapbox.navigation.base.trip.notification.TripNotification.
- Your custom module class is annotated with @MapboxModule(MapboxModuleType.NavigationTripNotification).
- You've provided a `ModuleProvider` instance to Mapbox_TripNotificationModuleConfiguration#setModuleProvider before initializing the library,
  unless `enableConfiguration` flag is set to false and your implementation has a public, non-arg constructor or is a Kotlin object.
```

**Android API:** 31
**Mapbox Navigation SDK version:** 2.0.0

### Steps to trigger behavior

I do not know how to reliably reproduce it. The errors have all come from Android 12 devices. The exception is thrown on this line:

```
mapboxNavigation = MapboxNavigationProvider.create(
    new NavigationOptions.Builder(this.getApplicationContext())
        .distanceFormatterOptions(new DistanceFormatterOptions.Builder(this.getApplicationContext()).unitType(UnitType.METRIC).build())
        .accessToken(getString(R.string.mapbox_access_token))
        .build());
```

### Expected behavior

No exception.

### Actual behavior

Exception above is thrown.

**Comment by LukasPaczos** [comment] 2021-11-12 15:29
Thanks @samcrawford, closing as a duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/4967.

**Closed by LukasPaczos** 2021-11-12 15:29 UTC
