### ISSUE TITLE
Announcements with unique writing system

### ISSUE THREAD

**Issue by awoisoak** [mapbox/mapbox-navigation-android#4139] opened 2021-03-16 01:58 UTC
**Android API:** 11 
**Mapbox Navigation SDK version:** core:2.0.0-SNAPSHOT

### Steps to trigger behavior

 1. Start navigating in Japan setting `RouteOptions` language to English
 2. Receive announcement in English including the name of the street in Japanese
 3. TTS can't handle both writing systems and won't read the name of the street

(I didn't try with the voice SDK as Japanese spoken instructions are [not supported](https://github.com/mapbox/mapbox-navigation-android/blob/main/docs/localization.md))

### Expected behavior
Ideally, announcement could be received in romaji 
`Drive east. Then Turn right onto Adzuma-dōri shōten machi`

or allow to receive simple instructions 
`Drive east. Then Turn right`

so the whole instruction can be read right away by the corresponding TTS engine.

### Actual behavior
The street name is received in different writing system which can't be used right away with TTS
`Drive east. Then Turn right onto あづま通り商店街`

so the user ends just hearing
`Drive east. Then Turn right onto`

**Comment by Guardiola31337** [comment] 2021-03-16 18:33
cc @mapbox/navigation-api @1ec5 @danpaz

**Comment by awoisoak** [comment] 2021-03-17 08:07
Just to give some more details. 
I tested different cases it with both Google & Samsung TTS engines and they behave the same:

1) `Turn right onto あづま通り商店街`
They will read everything **with Japanese** pronunciation

2) `Drive east. Then Turn right onto あづま通り商店街`
They will just read `Drive east. Then Turn right onto` with English pronunciation

3) `Turn right onto 商店街`
They will read `Turn right onto` with English pronunciation + `商店街` **with Chinese** pronunciation (no hiragana/katakana characters)

4) `Turn right onto Adzuma-dōri shōten machi`
They will read everything with English pronunciation (the most ideal scenario)

**Comment by 1ec5** [comment] 2021-09-15 17:47
Duplicate of #2511.

**Closed by 1ec5** 2021-09-15 17:47 UTC
Labels: archived
