### ISSUE TITLE
NavigationView with custom style and tilesets in a wrong order

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#2561] opened 2020-03-10 12:53 UTC
Hey,

I want to show a few (raster) tilesets below the route inside a NavigationView. 

**Android API: 29**
**Mapbox Navigation SDK version: 0.42.4**

### Steps to trigger behavior

1. Adjust a theme and include the mapbox style ...
``` 
    <style name="CUNavigationViewLight" parent="@style/NavigationViewLight">
        <item name="navigationViewMapStyle">myWithMapboxStudioCreatedPublicStyle</item>
    </style>
``` 
... include the theme ...
``` 
    <com.mapbox.services.android.navigation.ui.v5.NavigationView
        android:id="@+id/mapboxNavigationView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:navigationLightTheme="@style/CUNavigationViewLight"/>
``` 

2. Create a Fragment with the Mapbox NavigationView and implement OnNavigationReadyCallback
``` 
@Override
public void onNavigationReady(boolean isRunning) {
    mapboxMap = navigationView.retrieveNavigationMapboxMap().retrieveMap();
    mapboxMap.getStyle(new Style.OnStyleLoaded() {
        @Override
        public void onStyleLoaded(@NonNull Style style) {
	    for (int i = 0; i < style.getLayers().size(); i++) {
                Timber.tag(TAG).d("Layer " + i + ": " + style.getLayers().get(i).getId());
	    }
        }
    });
}
``` 
I could also use mapboxMap.getStyle() but that doesn't change angything. 

### Expected behavior
[...]
Layer 40: settlement-minor-label
Layer 41: settlement-major-label
Layer 42: state-label
Layer 43: country-label
Layer 44: background
**Layer 45: My Layer 1
Layer 46: My Layer 2**
Layer 47: mapbox-navigation-route-shield-layer
Layer 48: mapbox-navigation-route-layer
Layer 49: mapbox-navigation-waypoint-layer
Layer 50: mapbox-navigation-arrow-shaft-casing-layer
Layer 51: mapbox-navigation-arrow-head-casing-layer
Layer 52: mapbox-navigation-arrow-shaft-layer
Layer 53: mapbox-navigation-arrow-head-layer
Layer 54: com.mapbox.annotations.points
Layer 55: mapbox-location-shadow-layer
Layer 56: mapbox-location-accuracy-layer
Layer 57: mapbox-location-background-layer
Layer 58: mapbox-location-foreground-layer
Layer 59: mapbox-location-bearing-layer
Layer 60: mapbox-android-symbol-layer-2

### Actual behavior
[...]
Layer 40: settlement-minor-label
Layer 41: settlement-major-label
Layer 42: state-label
Layer 43: country-label
Layer 44: background
**Layer 45: My Layer 1**
_Layer 46: mapbox-navigation-route-shield-layer
Layer 47: mapbox-navigation-route-layer
Layer 48: mapbox-navigation-waypoint-layer_
**Layer 49: My Layer 2**
Layer 50: mapbox-navigation-arrow-shaft-casing-layer
Layer 51: mapbox-navigation-arrow-head-casing-layer
Layer 52: mapbox-navigation-arrow-shaft-layer
Layer 53: mapbox-navigation-arrow-head-layer
Layer 54: com.mapbox.annotations.points
Layer 55: mapbox-location-shadow-layer
Layer 56: mapbox-location-accuracy-layer
Layer 57: mapbox-location-background-layer
Layer 58: mapbox-location-foreground-layer
Layer 59: mapbox-location-bearing-layer
Layer 60: mapbox-android-symbol-layer-2

![2020-03-10 13 55 01](https://user-images.githubusercontent.com/23097192/76314301-d12afc00-62d6-11ea-96de-fba123bee913.jpg)

I don't know why the navigation-route layers are inserted between my layers. But because of this disorder not the whole route is on top like it should be.

**Comment by Guardiola31337** [comment] 2020-06-01 15:06
@abhishek1508 @cafesilencio could we check if this would be an issue in `1.0`?

**Comment by cafesilencio** [comment] 2020-06-04 00:29
Thus far I can't reproduce this with the 1.0 SDK code but there are lots of possible variations with custom styles. 

@P-Zenker is your custom style something you can share? If so I will try testing with it.

**Comment by P-Zenker** [comment] 2020-07-03 08:36
@cafesilencio Sorry for my late response. Yes, I can share the style temporary: mapbox://styles/patrickzenker/ckc5yp5m90s371jp5js17ptfv

**Comment by cafesilencio** [comment] 2020-07-06 18:05
Thanks @P-Zenker I tested your style with our soon to be released version 1.0 SDK. I looped through the layers as you described and printed to the log. I'll include the list below with a screen shot.  I see a layer called "MediaDocks EG". Is that where it's supposed to be? I'm guessing it's not. I'm looking into this further and I'll update the ticket when I have more information.


NavigationViewFragment$onNavigationReady: Layer: streetsLayer
NavigationViewFragment$onNavigationReady: Layer: land
NavigationViewFragment$onNavigationReady: Layer: national-park
NavigationViewFragment$onNavigationReady: Layer: landuse
NavigationViewFragment$onNavigationReady: Layer: pitch-outline
NavigationViewFragment$onNavigationReady: Layer: waterway
NavigationViewFragment$onNavigationReady: Layer: water
NavigationViewFragment$onNavigationReady: Layer: land-structure-polygon
NavigationViewFragment$onNavigationReady: Layer: land-structure-line
NavigationViewFragment$onNavigationReady: Layer: aeroway-polygon
NavigationViewFragment$onNavigationReady: Layer: aeroway-line
NavigationViewFragment$onNavigationReady: Layer: building-outline
NavigationViewFragment$onNavigationReady: Layer: building
NavigationViewFragment$onNavigationReady: Layer: tunnel-path
NavigationViewFragment$onNavigationReady: Layer: tunnel-steps
NavigationViewFragment$onNavigationReady: Layer: tunnel-pedestrian
NavigationViewFragment$onNavigationReady: Layer: tunnel-simple
NavigationViewFragment$onNavigationReady: Layer: road-path
NavigationViewFragment$onNavigationReady: Layer: road-steps
NavigationViewFragment$onNavigationReady: Layer: road-pedestrian
NavigationViewFragment$onNavigationReady: Layer: road-simple
NavigationViewFragment$onNavigationReady: Layer: bridge-path
NavigationViewFragment$onNavigationReady: Layer: bridge-steps
NavigationViewFragment$onNavigationReady: Layer: bridge-pedestrian
NavigationViewFragment$onNavigationReady: Layer: bridge-case-simple
NavigationViewFragment$onNavigationReady: Layer: bridge-simple
NavigationViewFragment$onNavigationReady: Layer: admin-1-boundary-bg
NavigationViewFragment$onNavigationReady: Layer: admin-0-boundary-bg
NavigationViewFragment$onNavigationReady: Layer: admin-1-boundary
NavigationViewFragment$onNavigationReady: Layer: admin-0-boundary
NavigationViewFragment$onNavigationReady: Layer: admin-0-boundary-disputed
NavigationViewFragment$onNavigationReady: Layer: road-label-simple
NavigationViewFragment$onNavigationReady: Layer: path-pedestrian-label
NavigationViewFragment$onNavigationReady: Layer: waterway-label
NavigationViewFragment$onNavigationReady: Layer: natural-line-label
NavigationViewFragment$onNavigationReady: Layer: natural-point-label
NavigationViewFragment$onNavigationReady: Layer: water-line-label
NavigationViewFragment$onNavigationReady: Layer: water-point-label
NavigationViewFragment$onNavigationReady: Layer: poi-label
NavigationViewFragment$onNavigationReady: Layer: airport-label
NavigationViewFragment$onNavigationReady: Layer: settlement-subdivision-label
NavigationViewFragment$onNavigationReady: Layer: settlement-minor-label
NavigationViewFragment$onNavigationReady: Layer: settlement-major-label
NavigationViewFragment$onNavigationReady: Layer: state-label
NavigationViewFragment$onNavigationReady: Layer: country-label
NavigationViewFragment$onNavigationReady: Layer: background
**NavigationViewFragment$onNavigationReady: Layer: Catchup Buero Unten
NavigationViewFragment$onNavigationReady: Layer: Catchup Buero
NavigationViewFragment$onNavigationReady: Layer: MediaDocks 2. OG
NavigationViewFragment$onNavigationReady: Layer: MediaDocks 1. OG**
NavigationViewFragment$onNavigationReady: Layer: mapbox-navigation-alt-route-shield-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-navigation-alt-route-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-navigation-route-shield-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-navigation-route-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-navigation-route-traffic-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-navigation-waypoint-layer
**NavigationViewFragment$onNavigationReady: Layer: MediaDocks EG**
NavigationViewFragment$onNavigationReady: Layer: com.mapbox.annotations.points
NavigationViewFragment$onNavigationReady: Layer: mapbox-navigation-arrow-shaft-casing-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-navigation-arrow-head-casing-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-navigation-arrow-shaft-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-navigation-arrow-head-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-android-symbol-layer-1
NavigationViewFragment$onNavigationReady: Layer: mapbox-location-shadow-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-location-pulsing-circle-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-location-accuracy-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-location-background-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-location-foreground-layer
NavigationViewFragment$onNavigationReady: Layer: mapbox-location-bearing-layer

![Screenshot_20200706-105233](https://user-images.githubusercontent.com/2249818/86624275-e4de2a80-bf77-11ea-807c-aa5bb31837f6.png)

**Comment by cafesilencio** [comment] 2020-07-06 19:14
@P-Zenker The algorithm that the Navigation SDK uses to determine where in the layer stack to put the route line is as follows:

If a specific layer ID is not provided then starting at the top layer, the first layer that is not a Symbol layer and does not contain the text "mapbox-location" is determined and the route line layers are inserted below that layer. In the case of your style that layer is "MediaDocks EG". 

[Here is the source](https://github.com/mapbox/mapbox-navigation-android/blob/c53d7475e5b4344e2753c92dad797281ac007d4f/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt#L951)

In the NavigationMapboxMap class and the MapRouteLine class there is a parameter in the constructors called "belowLayerId" which can be used to specifically override the default layer location. I don't see that parameter is included as an option in the UI SDK NavigationView.

**Comment by cafesilencio** [comment] 2020-07-13 22:00
Since this issue described in this ticket is working as designed I'm going to close this.  However I created a feature request to expose the route line layer as an option in NavigationViewOptions so that the functionality is available when using NavigationView and custom styles as described above.   The feature request ticket is here:  https://github.com/mapbox/mapbox-navigation-android/issues/3334

**Closed by cafesilencio** 2020-07-13 22:00 UTC
Labels: navigation-ui
