### ISSUE TITLE
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.    > Could not find com.mapbox.mapboxsdk:mapbox-android-sdk-gl-core:5.3.0.

### ISSUE THREAD

**Issue by syedwarisalirehmani** [mapbox/mapbox-navigation-android#4937] opened 2021-10-04 10:24 UTC
I have updated MapBox SDK version from com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.1 to com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.0 ,as the old version has shown an error, FATAL EXCEPTION: main : Missing required properties: baseUrl user requested.
Now,I have added a new version of SDK which is com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.0 it has also shown an error of Could not find com.mapbox.mapboxsdk:mapbox-android-sdk-gl-core:5.3.0.

check it out, how my dependency looks like:

 implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-core:3.1.0'
    implementation "com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6"
    implementation "com.mapbox.navigation:core:1.5.1"
    implementation "com.mapbox.navigation:ui:1.5.1"

**Comment by syedwarisalirehmani** [comment] 2021-10-04 12:10
any help?

**Comment by kmadsen** [comment] 2021-10-05 18:24
Hi @syedwarisalirehmani! I haven't setup a similar project to reproduce your issue, but hopefully these details will help.

> implementation "com.mapbox.navigation:core:1.5.1"
implementation "com.mapbox.navigation:ui:1.5.1"

This is this repository, and you can find the release details here https://github.com/mapbox/mapbox-navigation-android/releases/tag/v1.5.1. 

If you are looking to use navigation:ui:1.5.1, it comes bundled with the other libraries including mapbox maps version `v9.6.1` as shown in the release.

Also, there are many new features and improvements in 2.0.0. Have you considered `com.mapbox.navigation:android:2.0.0-rc.4`?

**Comment by kmadsen** [comment] 2021-10-12 21:55
@syedwarisalirehmani The configuration you're looking for, if you were to use `'com.mapbox.navigation:ui:1.5.1'` is in the comment above. It was the gradle file I used in a standalone app (Android Studio > new project), and verified it all worked.

But again, please look to use the latest available ['com.mapbox.navigation:android:2.0.0-x'](https://github.com/mapbox/mapbox-navigation-android/releases) release because it will amazingly better than anything you will try to build on 1.5.1.

Closing this as we can't find an issue, please reach out if you're looking for more guidance!

**Closed by kmadsen** 2021-10-12 21:55 UTC
