### ISSUE TITLE
Return false on RouteListener allowRerouteFrom does not reset Navigation UI

### ISSUE THREAD

**Issue by skienzl** [mapbox/mapbox-navigation-android#862] opened 2018-04-13 15:30 UTC
I am not sure if this is expected behaviour. Maybe I miss-understood the allowRerouteFrom

Mapbox Navigation SDK version: 0.12.0

### Steps to trigger behavior

 1. Set enableOffRouteDetection = true 
 2. return false on allowRerouteFrom callback

### Expected behavior

Should not show reroute state or at least hide it afterwards

### Actual behavior

User is stuck in reroute state

**Comment by danesfeder** [comment] 2018-04-13 18:32
Hey @skienzl I believe this is actually a bug with rerouting itself (resolved by #829).  Do you mind checking if you can reproduce the same with `0.12.0-SNAPSHOT`?

**Comment by skienzl** [comment] 2018-04-16 09:49
Thx! I can look at in about 2 days. But as far as i can see #829  is just checking for valid routing profile name. I don't think this is causing the problem in that case. But i will def try :)

**Comment by danesfeder** [comment] 2018-04-16 20:41
@skienzl the default being passed into the SDK (if no profile provided) was `""`, breaking the API requests for off-route / faster-route detection

**Comment by danesfeder** [comment] 2018-05-21 14:59
This was fixed #829

**Closed by danesfeder** 2018-05-21 14:59 UTC

**Comment by priyankjain28** [comment] 2018-09-13 10:06
Hi @danesfeder,

I drawn the custom route by using MapMatchingAPI. I used NavigationView to navigate user on given route.
The Problem was cursor navigator denote on the starting point of route which came from map matching api, not on my current location. Here not required reroute to draw the route i just want to denote cursor on my current location 

![screenshot_2018-09-13-15-25-21-94 1](https://user-images.githubusercontent.com/5296931/45482066-b374e900-b76a-11e8-9c02-a24130d1f10d.png)
