### ISSUE TITLE
RouteAlternativesCacheManager accumulates unlimited amount of routes

### ISSUE THREAD

**Issue by zeac** [mapbox/mapbox-navigation-android#5308] opened 2021-12-22 16:04 UTC
**Android API:**
**Mapbox Navigation SDK version:** 2.0.1

### Steps to trigger behavior

 1. Start active guidance with `RouteOptions.enableRefresh` enabled.
 2. Wait until app is crashed with OOM.

### Expected behavior
Should RouteAlternativesCacheManager save only a few last routes?

**Comment by Guardiola31337** [comment] 2021-12-22 23:10
It seems that the issue is coming from the old `isDifferentRoute` method that was implemented using `directionsRoute.toJson()` which can lead to OOMs. That method was removed as part of https://github.com/mapbox/mapbox-navigation-android/pull/4892 after integrating the native continuous route alternatives which was released in [Mapbox Navigation SDK `v2.1.0-beta.1`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.1.0-beta.1).

Could you please re-test using the latest stable version [`v2.1.1`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.1.1) and check if the issue is gone? 🙏 

cc @kmadsen

**Comment by zeac** [comment] 2021-12-23 07:25
It seems like 2.2.0-alpha.1 does not have this problem. Can we have 2.0 fixed as well?

**Comment by LukasPaczos** [comment] 2022-01-07 15:48
Closing, this will be fixed in today's v2.0.5, while v2.1 and upcoming v2.2 do not reflect the problem.

**Closed by LukasPaczos** 2022-01-07 15:48 UTC
