### ISSUE TITLE
Android Drop-In UI: Crash in MapboxInfoPanelHeaderArrivalLayoutBinding.java

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#6514] opened 2022-10-27 11:20 UTC
Hi, I am using DropIn-Ui for my app and I am getting below crash often.

Fatal Exception: java.lang.NullPointerException
Missing required view with ID: app.abcourier.ccmobile:id/arrivedText
com.mapbox.navigation.dropin.databinding.MapboxInfoPanelHeaderArrivalLayoutBinding.bind (MapboxInfoPanelHeaderArrivalLayoutBinding.java:72)
com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderArrivalBinder.bind (InfoPanelHeaderArrivalBinder.kt:28)
com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderArrivalBinder.bind (InfoPanelHeaderArrivalBinder.kt:16)
com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderBinder$bind$1.invoke (InfoPanelHeaderBinder.kt:27)
com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderBinder$bind$1.invoke (InfoPanelHeaderBinder.kt:27)
com.mapbox.navigation.dropin.internal.extensions.ReloadingComponent$onAttached$$inlined$observe$default$1$1.emit (Collect.kt:136)
kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt (Channels.kt:62)
kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt (Channels.kt:1)
kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend (Unknown Source:14)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
kotlinx.coroutines.EventLoop.processUnconfinedEvent (EventLoop.common.kt:69)
kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined (DispatchedTask.kt:244)
kotlinx.coroutines.DispatchedTaskKt.dispatch (DispatchedTask.kt:161)
kotlinx.coroutines.CancellableContinuationImpl.dispatchResume (CancellableContinuationImpl.kt:397)
kotlinx.coroutines.CancellableContinuationImpl.completeResume (CancellableContinuationImpl.kt:513)
kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.completeResumeReceive (AbstractChannel.kt:907)
kotlinx.coroutines.channels.ArrayChannel.offerInternal (ArrayChannel.kt:83)
kotlinx.coroutines.channels.AbstractSendChannel.trySend-JP2dKIU (AbstractChannel.kt:154)
kotlinx.coroutines.channels.ChannelCoroutine.trySend-JP2dKIU (Unknown Source:2)
com.mapbox.navigation.core.internal.extensions.MapboxNavigationEx$flowOnFinalDestinationArrival$1$observer$1.onFinalDestinationArrival (MapboxFlowableExtensions.kt:100)
com.mapbox.navigation.core.arrival.ArrivalProgressObserver.doFinalDestinationArrival (ArrivalProgressObserver.kt:106)
com.mapbox.navigation.core.arrival.ArrivalProgressObserver.onRouteProgressChanged (ArrivalProgressObserver.kt:79)
com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress (MapboxTripSession.kt:686)
com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress (MapboxTripSession.kt:60)
com.mapbox.navigation.core.trip.session.MapboxTripSession$navigatorObserver$1.onStatus (MapboxTripSession.kt:376)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)

com.android.internal.os.ZygoteInit.main (ZygoteInit.java:935)

**Mapbox Navigation SDK version: com.mapbox.navigation:ui-dropin:2.9.0-beta.3**

Please check it and let me know how to fix this crash.

**Comment by abhishek1508** [comment] 2022-10-27 15:19
@Sridhar261990 Thank you for cutting the ticket. Can you please share the steps to reproduce the crash. A video along with the steps will be helpful.

**Comment by Sridhar261990** [comment] 2022-10-27 16:11
Hi @abhishek1508, This is not reproducible from my end. So far the crash happened for 35 times to drivers.

**Comment by abhishek1508** [comment] 2022-10-27 18:20
@Sridhar261990 Would it be possible to ask them anything about the steps to reproduce it?

**Comment by Sridhar261990** [comment] 2022-10-28 05:49
@abhishek1508 I am not sure. It is very difficult and let you know. I will try to get you a RouteID and UUID for the route which it caused the crash. Will it be helpful?

**Comment by EricGeiler** [comment] 2022-10-28 10:38
@abhishek1508 Let me see what data I can furnish... as well, I will pass additional firebase data.  Give me a bit, just arrive at the office.

**Comment by EricGeiler** [comment] 2022-10-28 11:06
Last 24 hours
![image](https://user-images.githubusercontent.com/61550186/198569445-d63375be-47fb-4274-86b9-5c50c564648e.png)

![image](https://user-images.githubusercontent.com/61550186/198570331-7165246b-ae33-48fe-8ef0-6badbb09a551.png)

``Fatal Exception: java.lang.NullPointerException: Missing required view with ID: app.abcourier.ccmobile:id/arrivedText
       at com.mapbox.navigation.dropin.databinding.MapboxInfoPanelHeaderArrivalLayoutBinding.bind(MapboxInfoPanelHeaderArrivalLayoutBinding.java:72)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderArrivalBinder.bind(InfoPanelHeaderArrivalBinder.kt:28)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderArrivalBinder.bind(InfoPanelHeaderArrivalBinder.kt:16)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderBinder$bind$1.invoke(InfoPanelHeaderBinder.kt:27)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderBinder$bind$1.invoke(InfoPanelHeaderBinder.kt:27)
       at com.mapbox.navigation.dropin.internal.extensions.ReloadingComponent$onAttached$$inlined$observe$default$1$1.emit(Collect.kt:136)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(:14)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
       at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:244)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
       at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:513)
       at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.completeResumeReceive(AbstractChannel.kt:907)
       at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:83)
       at kotlinx.coroutines.channels.AbstractSendChannel.trySend-JP2dKIU(AbstractChannel.kt:154)
       at kotlinx.coroutines.channels.ChannelCoroutine.trySend-JP2dKIU(:2)
       at com.mapbox.navigation.core.internal.extensions.MapboxNavigationEx$flowOnFinalDestinationArrival$1$observer$1.onFinalDestinationArrival(MapboxFlowableExtensions.kt:100)
       at com.mapbox.navigation.core.arrival.ArrivalProgressObserver.doFinalDestinationArrival(ArrivalProgressObserver.kt:106)
       at com.mapbox.navigation.core.arrival.ArrivalProgressObserver.onRouteProgressChanged(ArrivalProgressObserver.kt:79)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:686)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:60)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession$navigatorObserver$1.onStatus(MapboxTripSession.kt:376)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:174)
       at android.app.ActivityThread.main(ActivityThread.java:7432)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)``




Excerpt from our Driver 797 Log file around the time of the above posted crash.
The delay between 13:24 and 13:26 is when the driver was re-starting the application etc after the crash, so i decided to show you the first few lines after the crash as well.  I"m sorry we don't have more information logged to assist in debugging this.  I've personally spoken to the driver about 10 mins ago, and he does not remember the sequence of event/touches/screens that triggered this.

22-10-27 13:23:52: DRIVER_TYPE--1
2022-10-27 13:23:52: HomeFragment-onResume
2022-10-27 13:23:53: HomeFragment-onStop
2022-10-27 13:23:53: PickedUpOrder-onResume
2022-10-27 13:23:55: PickedUpOrder-onStop
2022-10-27 13:23:55: PUpOrdDetl-onResume
2022-10-27 13:23:57: Parking_params - {"DestinationLatitude":43.5850975073805,"DestinationLongitude":-79.6461540645203,"DriverLatitude":43.58520628,"DriverLongitude":-79.64643167,"MaximumDistanceInMeter":300,"DriverNumber":"797","OrderNumber":8976356,"AvoidParkingId":0,"Mode":2}
2022-10-27 13:23:57: Parking_slot_url - https://abcourier****REDACTRED****
2022-10-27 13:23:58: parkingresponse - {"ParkingSlots":[],"StatusID":100,"StatusDescription":"No Parking slots found for this order.","ModelStateError":null}
2022-10-27 13:23:58: PUpOrdDetl2Map Oview ::oNo::8976356--43.5850975073805,-79.6461540645203
2022-10-27 13:23:59: DirectionsOrderLocation::onCreate
2022-10-27 13:23:59: DirectionsOrderLocation::onResume
2022-10-27 13:24:00: DirectionsOrderLocation - https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-79.6464262,43.5851972;-79.6461541,43.5850975?access_token=****REDACTRED****&geometries=polyline6&alternatives=true&overview=full&steps=true&continue_straight=true&annotations=congestion_numeric%2Cspeed%2Cdistance%2Cduration&language=en&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=metric&exclude=toll&enable_refresh=true&snapping_include_closures=true%3Btrue&snapping_include_static_closures=true%3Btrue&max_height=1.6&max_width=1.9&max_weight=2.5
2022-10-27 13:24:00: DirectionsOrderLocation -onRoutesReady -NavigationRoute#id Q5jn9swVxDqyM03J1GW0MadFVGgl7QUaMTqcpHnZ2mmj1yLUwRrJRw==#0
2022-10-27 13:24:00: DirectionsOrderLocation -onRoutesReady -DirectionsResponse#uuid Q5jn9swVxDqyM03J1GW0MadFVGgl7QUaMTqcpHnZ2mmj1yLUwRrJRw==
2022-10-27 13:24:00: DirectionsOrderLocationDesired Time here : 13:24
2022-10-27 13:24:01: PUpOrdDetl-onStop
2022-10-27 13:24:01: ABCourierBaseActivity-app.abcourier.ccmobile.fragment.pickeduporder.pickedupdetail.PickedUpOrderDetail
2022-10-27 13:26:02: Firebase:title->Msg from CCMobilebody->Please Accept the Order.
OrderNumber:8978286
2022-10-27 13:26:02: Firebase:title->Msg from CCMobilebody->Please Accept the Order.
OrderNumber:8978290
2022-10-27 13:26:02: Firebase:title->Msg from CCMobilebody->Please Accept the Order.
OrderNumber:8978824
2022-10-27 13:26:10: Manual login url-https://abcourier****REDACTRED****
2022-10-27 13:26:10: DRV Login Manual`

**Comment by EricGeiler** [comment] 2022-10-28 11:16
![image](https://user-images.githubusercontent.com/61550186/198574707-7ee25d25-93aa-4b9c-8c68-f1abdbf2bde8.png)

**Comment by EricGeiler** [comment] 2022-11-08 13:40
Has this been resolved in 2.9.0rc.2 ?  looking at the pull req, leads me to think so.  I want to get sridhar to update our Mapbox SDK to a version that has this issue resolved., as its still quite persistent in the sdk we are using currently.

**Comment by abhishek1508** [comment] 2022-11-08 22:32
@EricGeiler We have refactored the code a bit so the lines where the code was crashing as reported originally is not applicable anymore. We haven't been able to reproduce this crash even once. Can you let us know if you can reproduce this with `v2.9.0-rc.2`? If so, it would be great to share a video of the steps and crash logs

**Comment by EricGeiler** [comment] 2022-11-09 11:32
@abhishek1508 I'll let you know if we can reproduce once I receive a working build from our developer with 2.9.0-rc.2

**Comment by EricGeiler** [comment] 2022-11-09 15:45
Well I received a build today from our Dev, same issue is happening just on a diff line #... 71 instead of 72 

@Sridhar261990 says hes positive its not an issue with our code, but I'm not positive either way, as I don't have the expertise to understand all of it.  

I just know i can reproduce this 3 out of 7 times minimum with 2.9.0-rc.2... I will post some video shortly on reproduction steps.. but basically it involves starting a nav session when you are "inside the arrival observer area" if that means anything to the techies, but that essentially what I can reproduce .

I asked @Sridhar261990 if we are possibly missing view or xml info etc.. he said its no possible.


Fatal Exception: java.lang.NullPointerException: Missing required view with ID: app.abcourier.ccmobile:id/arrivedTextContainer
       at com.mapbox.navigation.dropin.databinding.MapboxInfoPanelHeaderArrivalLayoutBinding.bind(MapboxInfoPanelHeaderArrivalLayoutBinding.java:71)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderArrivalBinder.bind(InfoPanelHeaderArrivalBinder.kt:28)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderArrivalBinder.bind(InfoPanelHeaderArrivalBinder.kt:16)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderBinder$bind$1.invoke(InfoPanelHeaderBinder.kt:27)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderBinder$bind$1.invoke(InfoPanelHeaderBinder.kt:27)
       at com.mapbox.navigation.dropin.internal.extensions.ReloadingComponent$onAttached$$inlined$observe$default$1$1.emit(Collect.kt:136)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(:14)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
       at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:245)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
       at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:513)
       at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.completeResumeReceive(AbstractChannel.kt:908)
       at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:83)
       at kotlinx.coroutines.channels.AbstractSendChannel.trySend-JP2dKIU(AbstractChannel.kt:155)
       at kotlinx.coroutines.channels.ChannelCoroutine.trySend-JP2dKIU(:2)
       at com.mapbox.navigation.core.internal.extensions.MapboxNavigationEx$flowOnFinalDestinationArrival$1$observer$1.onFinalDestinationArrival(MapboxFlowableExtensions.kt:100)
       at com.mapbox.navigation.core.arrival.ArrivalProgressObserver.doFinalDestinationArrival(ArrivalProgressObserver.kt:106)
       at com.mapbox.navigation.core.arrival.ArrivalProgressObserver.onRouteProgressChanged(ArrivalProgressObserver.kt:79)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:686)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:60)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession$navigatorObserver$1.onStatus(MapboxTripSession.kt:376)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:174)
       at android.app.ActivityThread.main(ActivityThread.java:7432)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by EricGeiler** [comment] 2022-11-09 15:59
video of re-production uploaded

https://user-images.githubusercontent.com/61550186/200878398-e7d9c98c-e5cd-4da2-81ae-158a08e0da79.mp4

From what I can tell, when a driver starts nav when near / or at the destination, it seems to trigger a crash.... this is only re-produceable when the driver is at/near arrival... this never seems to happen if not near arrival.

I'm testing from a stationary location in my office, with our office as the destination, thereby kinda forcing the issue... due to fact im indoors my puck moves around a bit, as you can see in video.  if puck moves inside "arrival observer area" before i press  the "PLAY / START NAV" button, it triggers the above noted crash.

**Comment by EricGeiler** [comment] 2022-11-09 16:47
Try testing with these values.

2022-11-09 10:53:12: app.abcourier.ccmobile.fragment.parking.ParkingAdapter::oNo:8995476--pLat:44.0620017965985--
pLong:-79.4442595348302--destlat:44.061904--destlong:-79.444406

/v5/mapbox/driving-traffic/-79.4443266,44.0620379;-79.4442595,44.0620018?

NavigationRoute#id -MyLzftPVttHdjNul2HjYzaDuT0WE0O1xlE-5ikOww2f5uXqRsyvOMw==#0
DirectionsResponse#uuid -MyLzftPVttHdjNul2HjYzaDuT0WE0O1xlE-5ikOww2f5uXqRsyvOMw==


https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-79.4443748,44.0622546;-79.4442595,44.0620018?

-NavigationRoute#id -5gopMc-IL1lmpxtcoPgSCHA6AAS0XGNa54inHsdVisi_FOUupBjKTw==#0
-DirectionsResponse#uuid -5gopMc-IL1lmpxtcoPgSCHA6AAS0XGNa54inHsdVisi_FOUupBjKTw==

**Comment by Sridhar261990** [comment] 2022-11-10 07:04
Hi @abhishek1508 , I am using custom infoPanelHeaderBinder. Is it mandatory I should also use infoPanelHeaderArrivalBinder?

**Comment by abhishek1508** [comment] 2022-11-10 07:50
@EricGeiler Thank you for sharing the granular details. This is helpful. We will try to reproduce this with the coordinate pair shared and steps mentioned. 

@Sridhar261990 No it's not necessary to use your own arrival binder if you are using a custom infoPanelHeaderBinder. However, you can use the custom arrival binder as well if you want to.

**Comment by abhishek1508** [comment] 2022-11-18 18:02
@EricGeiler @Sridhar261990 
We have attempted a fix for the crash in `v2.10.0-beta.1. However, there are some known issues with this release. I wouldn't recommend you pick it up for testing the crash fix. I will update you once this is ready to be tested.

**Comment by abhishek1508** [comment] 2022-12-19 18:11
@EricGeiler Sorry for not getting back to you on this one. Can you please share with me the version of Nav SDK you are using at present and if this crash is still relevant?

**Comment by EricGeiler** [comment] 2022-12-19 18:49
2.9.2 and its still present.

**Comment by EricGeiler** [comment] 2022-12-19 18:52
Fatal Exception: java.lang.NullPointerException: Missing required view with ID: app.abcourier.ccmobile:id/arrivedTextContainer
       at com.mapbox.navigation.dropin.databinding.MapboxInfoPanelHeaderArrivalLayoutBinding.bind(MapboxInfoPanelHeaderArrivalLayoutBinding.java:71)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderArrivalBinder.bind(InfoPanelHeaderArrivalBinder.kt:26)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderArrivalBinder.bind(InfoPanelHeaderArrivalBinder.kt:15)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderBinder$bind$1.invoke(InfoPanelHeaderBinder.kt:23)
       at com.mapbox.navigation.dropin.infopanel.InfoPanelHeaderBinder$bind$1.invoke(InfoPanelHeaderBinder.kt:23)
       at com.mapbox.navigation.dropin.internal.extensions.ReloadingComponent$onAttached$$inlined$observe$default$1$1.emit(Collect.kt:136)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(:14)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
       at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:244)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
       at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:513)
       at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.completeResumeReceive(AbstractChannel.kt:907)
       at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:83)
       at kotlinx.coroutines.channels.AbstractSendChannel.trySend-JP2dKIU(AbstractChannel.kt:154)
       at kotlinx.coroutines.channels.ChannelCoroutine.trySend-JP2dKIU(:2)
       at com.mapbox.navigation.core.internal.extensions.MapboxNavigationExtensions$flowOnFinalDestinationArrival$1$observer$1.onFinalDestinationArrival(MapboxNavigationExtensions.kt:136)
       at com.mapbox.navigation.core.arrival.ArrivalProgressObserver.doFinalDestinationArrival(ArrivalProgressObserver.kt:106)
       at com.mapbox.navigation.core.arrival.ArrivalProgressObserver.onRouteProgressChanged(ArrivalProgressObserver.kt:79)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:686)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:60)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession$navigatorObserver$1.onStatus(MapboxTripSession.kt:376)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:174)
       at android.app.ActivityThread.main(ActivityThread.java:7432)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

![image](https://user-images.githubusercontent.com/61550186/208498568-a3481eec-fb76-4c3c-ac3d-d78f2450ee9c.png)

**Comment by abhishek1508** [comment] 2022-12-20 05:29
Thank you for sharing that. This was fixed in v2.10.0-beta.1. The current release is `v2.10.0-rc.1`. Are you planning to switch to `v2.10` release train any time soon?

**Comment by EricGeiler** [comment] 2022-12-20 11:33
@abhishek1508  I received a build this morning from @Sridhar261990 with Mapbox Drop In UI-2.10.0-beta1 as he had some issues with dependencies on 2.10.0-rc.1 he is working to resolve.

**Comment by EricGeiler** [comment] 2022-12-20 17:56
@abhishek1508  Thanks,  I reminded @Sridhar261990 of that this morning. I asked him to keep working on 2.10.0-rc.1 for me as that will be the next build released to production fleet.

**Comment by Sridhar261990** [comment] 2022-12-20 18:59
Hi @abhishek1508, We are using the below dependency for searching places.

`implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0   
 implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v8:0.9.0'`.

The  2.10.0-rc.1 version works fine without plugin-places. I am getting duplicate classes Duplicate class com.mapbox.android.core.location.LocationEngine found in modules jetified-common-23.2.1-runtime (com.mapbox.common:common:23.2.1) and jetified-mapbox-android-core-2.0.1-runtime (com.mapbox.mapboxsdk:mapbox-android-core:2.0.1).

I have tried to exclude as mentioned in the changelog like below.
implementation('com.mapbox.navigation:ui-dropin:2.10.0-rc.1') {
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-core'
    }.

But it was not working. Is there any way I can fix it or should I update search sdk instead of plugin places?

**Comment by abhishek1508** [comment] 2022-12-20 20:41
@LukasPaczos Could you pitch in here when you get a chance?

**Comment by LukasPaczos** [comment] 2022-12-21 09:45
Hey @Sridhar261990! Your exclusion should not target `com.mapbox.navigation:ui-dropin:2.10.0-rc.1` but rather the plugins, something along the lines of:
```
implementation('com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0') {
  exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-core'
}
implementation('com.mapbox.mapboxsdk:mapbox-android-plugin-places-v8:0.9.0') {
  exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-core'
}
```

That said, the plugin dependencies you are declaring were built with Maps SDK v9 and v8 in mind (as the name of the artifacts implies) but you're using them with Maps SDK v10. These plugins are not be compatible at all with the map. I imagine that you're using the `plugin-place` only for features unrelated to the map, is that right? When it comes to the `plugin-annotation`, it should be replaced by https://docs.mapbox.com/android/maps/guides/annotations/annotations/.

**Comment by Sridhar261990** [comment] 2022-12-21 10:19
Hi @LukasPaczos, Thanks for your response. I am using plugin-places for searching locations.

**Comment by LukasPaczos** [comment] 2022-12-21 10:32
Thanks @Sridhar261990, since that plugin is not maintained anymore I'd recommend you to check out https://docs.mapbox.com/android/search/guides/, https://docs.mapbox.com/api/search/search/, and https://docs.mapbox.com/api/search/geocoding/ instead.

**Comment by LukasPaczos** [comment] 2022-12-21 10:32
Or just https://docs.mapbox.com/#search in general :)

**Comment by Sridhar261990** [comment] 2022-12-21 10:39
Thank you @LukasPaczos. I will look into it.

**Comment by LukasPaczos** [comment] 2022-12-21 11:05
Did the exclusion suggestions from https://github.com/mapbox/mapbox-navigation-android/issues/6514#issuecomment-1361086341 unblock your current work?

**Comment by Sridhar261990** [comment] 2022-12-21 11:06
Yes. It works fine @LukasPaczos.

**Comment by LukasPaczos** [comment] 2022-12-21 11:16
Perfect, I'm going to go ahead and close here but please let us know if you run into the issue again.

**Comment by abhishek1508** [comment] 2022-12-21 16:10
Thanks for looking into this @LukasPaczos. Reopening this issue as the OP was about a crash that still needs to be validated has been fixed.

cc @Sridhar261990

**Comment by abhishek1508** [comment] 2023-01-04 18:59
@EricGeiler @Sridhar261990 Can you please confirm if this is still reproducible?

**Comment by EricGeiler** [comment] 2023-01-27 16:47
@abhishek1508 please close this ticket, I'm not seeing this crash triggered anymore in our analytics toolkit.

**Comment by abhishek1508** [comment] 2023-01-27 16:49
Thank you for the update. Closing as per request.

**Closed by abhishek1508** 2023-01-27 16:49 UTC
Labels: jira-sync-complete
