### ISSUE TITLE
[Mapbox Navigation v2] Library inclusion overrides app colours in Dark Mode

### ISSUE THREAD

**Issue by sandyscoffable** [mapbox/mapbox-navigation-android#4165] opened 2021-03-23 16:39 UTC
**Android API:** 30
**Mapbox Navigation SDK version:** 2.0.0-beta.2

### Steps to trigger behaviour

 1. Update from Mapbox Navigation v1 to v2
 2. View app in Dark Mode

### Expected behaviour

Colours of things in unrelated areas of the app (i.e views without any maps or navigation etc) aren't affected by the inclusion or upgrade of a Mapbox library

### Actual behaviour

Including the Mapbox library affects colours in these unrelated views.

### More information

An example of one of the colours I'm having problems with (on an ImageView):
```
app:tint="?attr/colorPrimary"
```

Previously, this would set the ImageView to the app primary colour (in my case, a red colour, but it's irrelevant).
With the inclusion of the new version of the library, this imageview is white (I think it's actually being ignored for some reason).

I've noticed that the library pulls in `com.google.android.material` ... I've tried excluding it, and also setting it to 1.2.1 and 1.3.0 in my project all with the same effect. I was merely clutching at straws though.

Rolling back to the version without Mapbox Navigation v2 fixes the issue.

#### build.gradle (before)

```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.0'
    implementation 'com.mapbox.navigation:ui:1.3.0'
```

#### build.gradle (after)

```
    implementation "com.mapbox.navigation:android:2.0.0-beta.2"
```

**Comment by sandyscoffable** [comment] 2021-03-23 16:47
Navigation v1:
<img src="https://user-images.githubusercontent.com/20515901/112184574-3fe3aa80-8bf7-11eb-957d-e29d35c7ba23.png" width="320"/>

Navigation v2:
<img src="https://user-images.githubusercontent.com/20515901/112184583-4114d780-8bf7-11eb-8214-2b07eb821b4a.png" width="320"/>

**Comment by abhishek1508** [comment] 2021-03-23 16:58
Thanks for adding the issue. 
I would appreciate if you could share your app `styles.xml` so I can try to reproduce on my end.

Thanks @sandyscoffable

**Comment by sandyscoffable** [comment] 2021-03-23 17:35
I've added an example project here which should help you out: https://github.com/sandyscoffable/MapboxThemingBug

To replicate the issue, comment and uncomment the mapbox library in build.gradle
```
    // Commented = Red Android Icon on screen
    // Uncommented = Grey Android Icon on screen
    implementation "com.mapbox.navigation:android:2.0.0-beta.2"
```

Screenshots:

Mapbox library excluded:
<img src="https://user-images.githubusercontent.com/20515901/112191388-e03ccd80-8bfd-11eb-988d-9272a84c8bcc.png" width="320" />

Mapbox library included:
<img src="https://user-images.githubusercontent.com/20515901/112191414-e632ae80-8bfd-11eb-81e3-aebb23f7c67c.png" width="320" />

**Comment by sandyscoffable** [comment] 2021-03-23 17:38
This is based off what the "new project" wizard in Android Studio gives you. I made the following changes:
- I removed the second fragment since it wasn't necessary to show the issue
- I changed the primary colour from purple to red
- I ditched the text and button in the view, and chucked in an android image, with a `tint` attribute. You can see there are other differences in the view though (e.g why has the AppBar changed from red to grey?)

**Comment by sandyscoffable** [comment] 2021-03-23 17:44
Aside, I'm loving v2 ... it's a lot smoother. But a world of pain to upgrade 😹

**Comment by sandyscoffable** [comment] 2021-03-23 18:01
Another piece of (unrelated) feedback. We'd prefer to be billed per request, rather than per MAU, so it would be nice to have that as a billing option in future.

**Comment by zugaldia** [comment] 2021-03-23 18:47
Thank you @sandyscoffable for the great feedback and for trying v2. Please do feel free to reach our directly (my email is public in my GH profile) if there's any additional feedback you want to share. I'm interested in knowing more about your upgrade experience and on anything we can do to improve our documentation and migration guide.

**Comment by abhishek1508** [comment] 2021-03-23 20:37
@sandyscoffable Thank you for sharing the example. I cloned the repository and tried to run the app. I couldn't run it and was getting some gradle issues. I made the following modifications to get the project working:

**`gradle/wrapper/gradle-wrapper.properties`**

Changed `distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip`

**`root/build.gradle`**

Changed `classpath "com.android.tools.build:gradle:4.1.2"` to `classpath "com.android.tools.build:gradle:4.0.1"`

After this change I was able to run the app without any modifications. Please have a look at the `.gif` below

| Device | GIF | Device | GIF |
| --- | --- | --- | --- |
| Pixel_3a_XL_API23 | <img src="https://user-images.githubusercontent.com/9770186/112212867-bb832e80-8bda-11eb-9b23-415973554219.gif" alt="API 23" width="200" height="400"> | Pixel_3a_XL_API24 | <img src="https://user-images.githubusercontent.com/9770186/112213871-c9857f00-8bdb-11eb-9e1e-50f43e018243.gif" alt="API 24" width="200" height="400"> |
| Pixel_3a_XL_API25 | <img src="https://user-images.githubusercontent.com/9770186/112213984-e5892080-8bdb-11eb-86e2-d903fe7e3f63.gif" alt="API 25" width="200" height="400"> | Pixel_3a_XL_API26 | <img src="https://user-images.githubusercontent.com/9770186/112214380-5af4f100-8bdc-11eb-9dca-0799c6ecf937.gif" alt="API 26" width="200" height="400"> |
| Pixel_3a_XL_API27 | <img src="https://user-images.githubusercontent.com/9770186/112214388-5c261e00-8bdc-11eb-9a12-0928be1c6dbf.gif" alt="API 27" width="200" height="400"> | Pixel_3a_XL_API28 | <img src="https://user-images.githubusercontent.com/9770186/112214401-621bff00-8bdc-11eb-8efc-a73bbbcceef0.gif" alt="API 28" width="200" height="400"> |
| Pixel_3a_XL_API29 | <img src="https://user-images.githubusercontent.com/9770186/112214407-63e5c280-8bdc-11eb-838e-68e4463a6acc.gif" alt="API 29" width="200" height="400"> |

Based on the gif's, I see exactly what you expect to see without any problems.
I am not sure what would have happened if I hadn't have to change the `gradle distribution url` and `classpath`. Could you try doing the same and see what colors are you seeing?

**Comment by sandyscoffable** [comment] 2021-03-24 08:45
The plot thickens! I've tested this again this morning, and the bug is _only_ when night / dark mode is enabled

**Comment by sandyscoffable** [comment] 2021-03-24 09:05
I've tested on an emulator just now and it seems to work fine 🤦 

FWIW I'm running a stock Samsung Galaxy A71 SM-A715F, with Android 10. That device seems to exhibit the problem, in dark mode only.

**Comment by sandyscoffable** [comment] 2021-03-24 09:23
I've tested on API 29 and 30 emulators and it works fine, so this seems to be limited to Samsung phones.

**Comment by sandyscoffable** [comment] 2021-03-24 09:41
<img width="556" alt="Screenshot 2021-03-24 at 09 40 38" src="https://user-images.githubusercontent.com/20515901/112288225-078aad80-8c85-11eb-8634-f6d7b20dc46a.png">

I just hit the problem in the emulator, so not just Samsung phones. I had to do a complete project rebuild though (and uninstall the app on the emulator), basically a complete rinse.
<img width="556" alt="Screenshot 2021-03-24 at 09 40 38" src="https://user-images.githubusercontent.com/20515901/112288342-26893f80-8c85-11eb-9332-1aabe52e1e92.png">

**Comment by sandyscoffable** [comment] 2021-03-25 08:16
@abhishek1508 - did you have any success replicating this in Dark Mode?

**Comment by abhishek1508** [comment] 2021-03-25 16:18
@sandyscoffable I have been busy with other priorities so didn't get a chance yet. 
I want to do the exact same steps that you are performing and hence can you share the steps on what version of Android API are you using on the emulator and how are you setting the emulator to dark mode?

**Comment by sandyscoffable** [comment] 2021-03-26 09:03
Here is a screenshot of all my emulator settings
<img width="938" alt="Screenshot 2021-03-26 at 08 46 34" src="https://user-images.githubusercontent.com/20515901/112606683-5a44a080-8e10-11eb-9af7-0b1507faa39a.png">

I couldn't quite get a GIF of me reproducing the issue to fit in the GitHub limit of 10MB. Here is a 30MB webm video of me showing the issue on the above emulator.

The project loaded onto the emulator is exactly the same as what's in the GitHub repo I shared with you earlier.

**Comment by sandyscoffable** [comment] 2021-04-26 12:12
Same bug is in `2.0.0-beta.7`

**Comment by Guardiola31337** [comment] 2021-04-27 13:56
@abhishek1508 could you follow up here when you have a chance? 🙏

**Comment by abhishek1508** [comment] 2021-05-19 07:07
It kind of makes sense that the app is picking up `#212121` from Nav SDK `values-night.xml` because the app is setting a `themes.xml` for night mode but is not defining the colors for night mode. I added `colors.xml` to `values-night` with the same primary color and this is what I see.

<img width="300" alt="Screen Shot 2021-04-14 at 12 31 39 PM" src="https://user-images.githubusercontent.com/9770186/118770182-a7884000-b89e-11eb-805f-ba81c54ed62b.png">

I think the problem isn't that the app is picking up night color from the SDK if not specified as it the correct android behavior. The problem is whether we should expose the resource colors. If `libnavui-resources` are not exposed directly or transitively to the application, this problem shouldn't happen.

I will close this ticket and open a new one to discuss the point if we should be exposing `resources`. For now you can add a `colors.xml` to `values-night` with same or different values and that should fix the problem.

cc @sandyscoffable @Guardiola31337 @LukasPaczos

**Comment by abhishek1508** [comment] 2021-05-20 05:56
Closing this as discussion is moving here > https://github.com/mapbox/mapbox-navigation-android/issues/4422

**Closed by abhishek1508** 2021-05-20 05:56 UTC
Labels: bug

**Comment by sandyscoffable** [comment] 2021-05-24 09:37
Thanks @abhishek1508 - this solution works. I was trying to stay away from duplicating colours but that's a nitpick. 
Thanks for your help.
