### ISSUE TITLE
Kalman Location Engine

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#54] opened 2017-05-24 00:08 UTC
In order to better control when location updates occur, a Kalman filter can be used to force location updates between real GPS updates. 

cc: @zugaldia

**Comment by danesfeder** [comment] 2018-10-03 21:05
With `0.20.0`, `Location` filtering is pushed to `Navigator` and will no longer be on the client as a responsibility, closing

**Closed by danesfeder** 2018-10-03 21:05 UTC
Labels: feature, low priority, topic: location

**Comment by Ohemgi** [comment] 2018-10-23 12:53
hey @danesfeder!  
> Location filtering is pushed to Navigator and will no longer be on the client as a responsibility
Do i understand you right, that a kalman filter is not required client side / on mobile device? I'm looking for smooth location transitions and a proper "location estimation" while in navigation mode and `locationLayer.forceLocationUpdate(location)` in combination with the locationEngine does not provide "enough" accurate updates. The location marker appears to "lag" and the position is always "behind".

If this is the case, can you suggest a different approach for that problem?

**Comment by danesfeder** [comment] 2018-10-23 13:51
> Do i understand you right, that a kalman filter is not required client side / on mobile device?

Hey @Ohemgi 👋 you are correct here - the SDK will ingest the raw locations and filter / snap them (returning in `ProgressChangeListener`).

> The location marker appears to "lag" and the position is always "behind".

We have actually been working on better prediction / projection of the snapped locations returned.  Do you mind providing which version of the SDK you've been testing?  Thanks!

**Comment by Ohemgi** [comment] 2018-10-23 14:11
Hey @danesfeder Thanks for the reply on this. Im currently on `0.19.0`

**Comment by Ohemgi** [comment] 2018-10-23 14:39
@danesfeder ill check that out and comment later on the improvements. Thanks for the hint!

**Comment by danesfeder** [comment] 2018-10-23 14:48
@Ohemgi specifically https://github.com/mapbox/mapbox-navigation-android/pull/1354/ is what I'm referring to - you can adjust that value (`NAVIGATION_LOCATION_ENGINE_INTERVAL_LAG`) in the `MapboxNavigationOptions`, but please test the default before doing so.

**Comment by Ohemgi** [comment] 2018-10-24 09:13
@danesfeder sorry for putting this request here, but you are tracking the sdk changes i think you might be the correct one beeing asked :smiling_imp: :
After updating to `0.21.0` the location prediction / projection seem to improved. Good job on that so far :+1:  

But one "blocking" thing came up for me: Without any further changes (except the dep update) the routeProgress object, raised by the navigation in `ProgressChangeListener`, holds the relevant progress data as before, **except the distance information**. Every distance field is `0.0` (like `routeProgress.distanceRemaining`. Since the navigation setup / input parameters remained the same, you might could give me a hint which part of the sdk i should dive into, to debug this? Just to clarify: There is no exception etc. raised. `onProgressChange` Event is still raised but with the Zero-Distance-Values as described above. 

Thanks in advance, Ben

**Comment by zugaldia** [comment] 2018-10-24 14:59
@Ohemgi could you cut a separate ticket for this new question? Looks like a regression worth looking into.

**Comment by danesfeder** [comment] 2018-10-24 15:18
Hey @Ohemgi have started progressing along the route when you're seeing this behavior?  How are you testing the SDK in this scenario?

In `0.21.0` we saw the the SDK was returning 0 values until progress was made along the route and we had sufficient location updates from the device to be considered "tracking".  Related tickets https://github.com/mapbox/mapbox-navigation-android/issues/1445 and https://github.com/mapbox/mapbox-navigation-android/issues/1404.

Now when the route starts, we should provide full route duration / distance values rather than 0.  This will be fixed in our `0.22.0` release slated for this week.  In the meantime you can test with a `SNAPSHOT` that will have these updates https://github.com/mapbox/mapbox-navigation-android/issues/1404.  

If this doesn't fix your issue, as @zugaldia mentioned, please open a ticket and we will investigate further.  Thanks!

**Comment by Ohemgi** [comment] 2018-10-24 15:41
Hey @danesfeder ,
Hey @zugaldia ,

ok, i was already about creating an issue, but your suggestion sounds like it could directly adress my problem @danesfeder :+1:  :smile:  I'll check the snapshot build and comment on the results after doing so.

Thanks for your participation on that behavior!

Br, Ben

**Comment by Ohemgi** [comment] 2018-10-25 15:43
Hey @Guardiola31337 :wave: nice! thanks for the update on this. I updated to `0.22.0-SNAPSHOT` yesterday. Sadly the first progress instance still holding zero-values but i gonna check my setup and give a feedback tomorrow :+1:

**Comment by Guardiola31337** [comment] 2018-10-25 18:42
Sweet! Thanks for the update @Ohemgi 🙏
