### ISSUE TITLE
Could not GET 'https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom'. Received st atus code 403 from server: Forbidden

### ISSUE THREAD

**Issue by HseinNd98** [mapbox/mapbox-navigation-android#4594] opened 2021-07-10 08:49 UTC
## * Error happens when trying to implement the following dependencies: 
**1. com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6**
**2. com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6**

## * Tried 'gradlew build -i' in Terminal and got the following: 

Failed to get resource: HEAD. [HTTP HTTP/1.1 403 Forbidden: https://mapbox.bintray.com/mapbox/com/mapbox/mapboxsdk/mapbox-android-sdk/9.6.2/mapbox-android-sdk-9.6.
2.pom)]
Failed to get resource: HEAD. [HTTP HTTP/1.1 403 Forbidden: https://mapbox.bintray.com/mapbox/com/mapbox/mapboxsdk/mapbox-android-core/5.0.0/mapbox-android-core-5.
0.0.pom)]
Failed to get resource: HEAD. [HTTP HTTP/1.1 403 Forbidden: https://mapbox.bintray.com/mapbox/com/mapbox/mapboxsdk/mapbox-android-telemetry-okhttp3/8.1.0/mapbox-an
droid-telemetry-okhttp3-8.1.0.pom)]
sdk-gl-core-5.2.2.pom)]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-
native-7.0.0.pom)]
Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom]
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom]
Resource missing. [HTTP GET: https://jcenter.bintray.com/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom]
Resource missing. [HTTP GET: https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.
pom]
Failed to get resource: HEAD. [HTTP HTTP/1.1 403 Forbidden: https://mapbox.bintray.com/mapbox/com/mapbox/mapboxsdk/mapbox-android-sdk/9.6.2/mapbox-android-sdk-9.6.
2.pom)]
Failed to get resource: HEAD. [HTTP HTTP/1.1 403 Forbidden: https://mapbox.bintray.com/mapbox/com/mapbox/mapboxsdk/mapbox-android-telemetry-okhttp3/8.1.0/mapbox-an
droid-telemetry-okhttp3-8.1.0.pom)]
Failed to get resource: HEAD. [HTTP HTTP/1.1 403 Forbidden: https://mapbox.bintray.com/mapbox/com/mapbox/mapboxsdk/mapbox-android-sdk-gl-core/5.2.2/mapbox-android-
sdk-gl-core-5.2.2.pom)]
Failed to get resource: HEAD. [HTTP HTTP/1.1 403 Forbidden: https://mapbox.bintray.com/mapbox/com/mapbox/mapboxsdk/mapbox-android-core/5.0.0/mapbox-android-core-5.
0.0.pom)]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-
native-7.0.0.pom)]

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.mapbox.navigator:mapbox-navigation-native:7.0.0.
     Required by:
         project :app > com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:7.0.0.
         > Could not get resource 'https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom'.
            > Could not GET 'https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom'. Received st
atus code 403 from server: Forbidden

## Project level build.gradle dependencies 
dependencies {
    implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.2'){
        exclude group: 'group-name', 'module': 'module-name'
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v9:0.4.0' // MarkerView
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6'
}

## My Module build.gradle file looks like this 
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven{ url 'https://mapbox.bintray.com/mapbox' }
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = 'mapbox'
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

### 6. Removed proxy settings

**Comment by ljubo87bg** [comment] 2021-07-12 01:29
I'm in the exact same boat. Same versions, same output.

**Comment by zugaldia** [comment] 2021-07-12 14:25
I believe this is a dupe of https://github.com/mapbox/mapbox-navigation-android/issues/4533, please check that ticket for more information.

**Closed by zugaldia** 2021-07-12 14:25 UTC
