### ISSUE TITLE
Navigation Stops/cannot start while in background

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#1703] opened 2019-01-28 10:50 UTC
We are having an issue on some devices (OnePlus) where if the app is in the background for too long, the app is force killed by the system for "excessive battery use". There doesn't appear to be a way to stop this, but the app being in the background is a legitimate use case.

We have an idea to run a monitoring service to detect if the app has been killed, and simple restart navigation from where the user was up to. The problem is we can't seem to start navigation with the app in the background (e.g. screen off), because onNavigationReady() does not get called until the app is in the foreground.

Is there anything that can be done to allow navigation to start in the background, or alternatively is it possible to look into the fact that OnePlus devices seem to kill the app after a while of navigating in the background (OnePlus 6, Android 9. Based on some quick research, the suggestion is that it's a OnePlus feature aimed at increasing battery life)

**Comment by danesfeder** [comment] 2019-01-28 14:22
> where if the app is in the background for too long, the app is force killed by the system for "excessive battery use". There doesn't appear to be a way to stop this, but the app being in the background is a legitimate use case.

Hey @richjhart 👋 yeah we agree and don't want to have any issues while your app is navigating in the background.  Do you have the specific error sent by the OnePlus devices?   That may help us dig into this further. Thanks!

**Comment by danesfeder** [comment] 2019-01-28 14:36
@richjhart thank you!  Just to note, which version of the SDK is this?

> which would also need to be a foreground service, so will require a second icon in the status bar, which is mildly annoying

Yeah agreed, this is not ideal.

**Comment by richjhart** [comment] 2019-01-28 14:39
We're on 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.27.0'.

Also note, we MIGHT have been seeing a similar issue of other devices before (but never fully investigated), but haven't been on the latest SDK.

**Comment by danesfeder** [comment] 2019-01-28 16:54
@richjhart in the UI library a lot of the memory / CPU intensive work happens while updating the map, which should be a non-issue with the map in the background.  

I think the main considerations here would be hitting the GPS antenna (`LocationEngine`) / executing our route-following code, which is much more efficient with our new C++ library we used in the `NavigationService`.  

Maybe we can run some test routes with the app in the background and record profiles to see where we are running into possible bottlenecks with your implementation?  Even if it's not reproducing the crash, we can observe what is using the most resources.  

Possible optimizations we can look into are maybe ramping down GPS hits in the background, as every second (default) may not be necessary to drive the voice announcements / notification.

**Comment by richjhart** [comment] 2019-01-29 16:04
@danesfeder I haven't had much time to look at this one again yet. However, I did do some quick profiling while looking at something else - and OnePlus may have a point. We have a couple of functions which may be using too much CPU for a background app.

I will try to look at improving them ASAP, as it might turn out this is a bit of a non-issue.

Note - we already effectively reduce the number of GPS hits because the first thing we do with a new one is check if the progress or location are still "similar" to the previous calls, and do nothing else if they are.

**Comment by danesfeder** [comment] 2019-01-29 16:33
@richjhart okay keep us posted on your findings there, thank you.

> Note - we already effectively reduce the number of GPS hits because the first thing we do with a new one is check if the progress or location are still "similar" to the previous calls, and do nothing else if they are.

If I'm following this correctly, if you are checking new updates, this still means you're hitting the device GPS antenna and costing battery life.  I mean actually telling location services to ramp down in the background. 

Example pseudocode:

```
    if (isInBackground) {
      LocationEngineRequest request = new LocationEngineRequest.Builder(lessAgressiveInterval)
        .setDisplacement(lessAgressiveDisplacement)
        .build();
      navigationView.retrieveMapboxNavigation().setLocationEngineRequest(request);
    }
```

Disclaimer: this is just a suggestion that may help, we have not done extensive testing updating this "on-the-fly".

**Comment by richjhart** [comment] 2019-01-30 10:03
Unfortunately, the improvements to our functions didn't help.

We are currently simulating, so we are not controlling the real GPS antenna (but as per the other recent bug we discussed, could it be being hit anyway?)

Note - this does seem to be a general problem with OnePlus:
https://www.google.com/search?q=oneplus+killing+apps
returns a lot of results, and no one seems to have an answer. It appears to be a bit of a lazy battery saving technique by OnePlus (which doesn't actually save battery - because it forces people like me to run extra services as a different process to monitor if the OS has killed my app incorrectly...)

**Comment by danesfeder** [comment] 2019-02-05 13:46
> We are currently simulating, so we are not controlling the real GPS antenna (but as per the other recent bug we discussed, could it be being hit anyway?)

If you are simulating with the `NavigationView` then you shouldn't be hitting the GPS antenna, unless your `LocationEngine` (I recall you were providing your own?) is running both location services and simulation simultaneously.

**Comment by danesfeder** [comment] 2019-02-14 15:46
@richjhart any updates here or ideas you feel are actionable on our end?

**Comment by richjhart** [comment] 2019-02-26 13:56
@danesfeder Sorry for the delay in replying. Just to let you know, this project has been paused (we are at the open beta stage), so I'm not currently actively working on it.

Having said that, I haven't thought of anything actionable at your end. We basically handle the situation by allowing the user to quickly continue navigation from where they left off when they re-open the app.

As even apps like Spotify don't seem to have found a way around this, it seems that it is a "feature"/"bug" with OnePlus.

Note, if you're interested in seeing how we use the app - it's available from https://play.google.com/store/apps/details?id=com.bynd.looper

**Comment by danesfeder** [comment] 2019-02-26 14:16
@richjhart yeah that sounds like the best solution for now, thank you for the update.  Let's keep this open for now?  

`Looper` looks great - one of the best custom UI implementations we've seen.  Great work!

**Comment by richjhart** [comment] 2019-02-28 12:35
If you're happy to keep it open for a while, that works for us too. I'll let you know if I discover anything about it or figure out a decent work around.

And thanks, good to hear that you guys like it!

**Comment by Guardiola31337** [comment] 2020-06-01 17:30
@abhishek1508 is this still an issue in `1.0` UI SDK?

**Comment by abhishek1508** [comment] 2020-07-13 18:38
Let's verify
cc @JunDai @langsmith @cafesilencio

**Comment by abhishek1508** [comment] 2020-08-03 18:03
Closing this ticket as we couldn't reproduce it. Please look out for our new v1.0 that is going to be release soon. Feel free to open a ticket if you still see the issue.
cc @richjhart

**Closed by abhishek1508** 2020-08-03 18:03 UTC
Labels: bug, navigation-ui, needs investigation, performance
