### ISSUE TITLE
NullPointerException when when route built with MapboxDirections.builder()

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-navigation-android#930] opened 2018-05-10 22:02 UTC
**Android API:**
**Mapbox Navigation SDK version:**  0.12.0

### Steps to trigger behavior

 1. Create a route using `MapboxDirections.builder()` instead of `NavigationRoute.builder()`
 2. Add a few waypoints using `.addWaypoint()`
 3. Start turn-by-turn navigation

### Expected behavior

Turn-by-turn navigation should progress normally without any issues.

### Actual behavior

A NullPointerException is thrown when the first way point is encountered

**Error log:**
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference 
at com.mapbox.services.android.navigation.v5.milestone.BannerInstructionMilestone.isOccurring(BannerInstructionMilestone.java:29) 
at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.checkMilestones(NavigationHelper.java:201) 
at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleRequest(NavigationEngine.java:76) 
at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleMessage(NavigationEngine.java:41) 
at android.os.Handler.dispatchMessage(Handler.java:101) 
at android.os.Looper.loop(Looper.java:164) 
at android.os.HandlerThread.run(HandlerThread.java:65) 
```

**Comment by danesfeder** [comment] 2018-05-11 00:36
Hey @riastrad, thanks for opening this - the Nav SDK version you referenced looks like the Maps SDK.  Our latest version is `0.13.0`, is this the version you were producing this with?  Thanks!

**Comment by danesfeder** [comment] 2018-05-14 18:08
@riastrad no problem, do you by chance have the route request code that reproduces this?  I'm trying to configure a way to reproduce but can't seem to do so - thanks!

**Comment by danesfeder** [comment] 2018-05-14 19:41
@riastrad let's maybe pair on this tomorrow after ☕️ ?  I'm missing some classes from your java code so it would be easier to see on your computer.  Opening up a work-in-progress PR in the meantime.  Thanks!

**Comment by danesfeder** [comment] 2018-05-21 17:49
@riastrad please keep us posted on the findings regarding this issue, thanks!

**Comment by riastrad** [comment] 2018-05-21 17:52
Sure thing, @danesfeder. It turns out the initial NPE was thrown using SDK version `0.12.0`. I've asked the user to update to `0.13.0` and report back if the problem persists. Will let you know the moment I hear back from them.

**Comment by danesfeder** [comment] 2018-06-11 19:17
Closing this for now - waiting on response from original developer who submitted the issue. Will reopen if needed.  Thanks @riastrad!

**Closed by danesfeder** 2018-06-11 19:17 UTC
Labels: bug
