### ISSUE TITLE
ManeuverProcessor.updateDistanceRemainingForCurrentManeuver fails with index out of bounds exception

### ISSUE THREAD

**Issue by VysotskiVadim** [mapbox/mapbox-navigation-android#5088] opened 2021-11-09 12:18 UTC
The multiple way points example from the [example repo](https://github.com/mapbox/mapbox-navigation-android-examples) is minimal demonstration example. (https://github.com/mapbox/mapbox-navigation-android-examples/pull/57)

**Android API:** 31
**Mapbox Navigation SDK version:** 2.0.0

### Steps to trigger behavior

 1. Open the multiple way points example
 2. Add 2 waypoints 
 3. Push the "Let's go" button.
 4. Wait until you reach the first waypoint

### Expected behavior

Navigation continues without errors

### Actual behavior

An error toast appears at the bottom of the screen because `ManeuverProcessor.updateDistanceRemainingForCurrentManeuver` fails with index out of bounds exception. See the [video](https://user-images.githubusercontent.com/6190346/140322590-9498816d-bd2b-4bb8-86a0-cde7caaab1e3.mp4)

**Comment by VysotskiVadim** [comment] 2021-11-09 12:51
Reproduced one more time: https://user-images.githubusercontent.com/6190346/140927281-b82b516f-8ef4-4ffc-b7c2-6ebaaf918b9e.mp4

`DirectionsRoute.toJson()`:
```json
{"routeIndex":"0","distance":220.458,"duration":54.13,"duration_typical":54.13,"geometry":"}`fagAtcpmhFoBqC{Q{VeCiDkCqDgEyFsc@wl@}E_HaBkCoBoC","weight":63.637,"weight_name":"auto","legs":[{"distance":94.23,"duration":25.042,"duration_typical":25.042,"summary":"Folsom Street","admins":[{"iso_3166_1":"US","iso_3166_1_alpha3":"USA"}],"steps":[{"distance":94.23,"duration":25.042,"duration_typical":25.042,"speedLimitUnit":"mph","speedLimitSign":"mutcd","geometry":"}`fagAtcpmhFoBqC{Q{VeCiDkCqDgEyF","name":"Folsom Street","mode":"driving","maneuver":{"location":[-122.397259,37.785119],"bearing_before":0.0,"bearing_after":46.0,"instruction":"Drive northeast on Folsom Street.","type":"depart"},"voiceInstructions":[{"distanceAlongGeometry":94.23,"announcement":"Drive northeast on Folsom Street. Then, in 300 feet, Your destination will be on the right.","ssmlAnnouncement":"\u003cspeak\u003e\u003camazon:effect name\u003d\"drc\"\u003e\u003cprosody rate\u003d\"1.08\"\u003eDrive northeast on \u003csay-as interpret-as\u003d\"address\"\u003eFolsom Street\u003c/say-as\u003e. Then, in 300 feet, Your destination will be on the right.\u003c/prosody\u003e\u003c/amazon:effect\u003e\u003c/speak\u003e"}],"bannerInstructions":[{"distanceAlongGeometry":94.23,"primary":{"text":"Your destination will be on the right","components":[{"text":"Your destination will be on the right","type":"text"}],"type":"arrive","modifier":"right"}},{"distanceAlongGeometry":55.556,"primary":{"text":"Your destination is on the right","components":[{"text":"Your destination is on the right","type":"text"}],"type":"arrive","modifier":"right"}}],"driving_side":"right","weight":32.454,"intersections":[{"location":[-122.397259,37.785119],"bearings":[46],"entry":[true],"out":0,"geometry_index":0,"is_urban":true,"admin_index":0,"mapbox_streets_v8":{"class":"secondary"}},{"location":[-122.397186,37.785175],"bearings":[45,226],"entry":[true,false],"in":1,"out":0,"geometry_index":1,"is_urban":true,"admin_index":0,"mapbox_streets_v8":{"class":"secondary"}},{"location":[-122.396804,37.785477],"bearings":[45,225],"entry":[true,false],"in":1,"out":0,"lanes":[{"valid":false,"active":false,"indications":["left"]},{"valid":true,"active":false,"valid_indication":"straight","indications":["straight"]},{"valid":true,"active":true,"valid_indication":"straight","indications":["straight"]},{"valid":false,"active":false,"indications":["right"]}],"geometry_index":2,"is_urban":true,"admin_index":0,"mapbox_streets_v8":{"class":"secondary"}},{"location":[-122.396719,37.785544],"bearings":[45,225],"entry":[true,false],"in":1,"out":0,"lanes":[{"valid":true,"active":false,"valid_indication":"straight","indications":["left","straight"]},{"valid":true,"active":false,"valid_indication":"straight","indications":["straight"]},{"valid":true,"active":true,"valid_indication":"straight","indications":["straight","right"]}],"geometry_index":3,"is_urban":true,"admin_index":0,"mapbox_streets_v8":{"class":"secondary"}},{"location":[-122.39663,37.785614],"bearings":[45,225],"entry":[true,false],"in":1,"out":0,"geometry_index":4,"is_urban":true,"admin_index":0,"mapbox_streets_v8":{"class":"secondary"}}]},{"distance":0.0,"duration":0.0,"duration_typical":0.0,"speedLimitUnit":"mph","speedLimitSign":"mutcd","geometry":"cfgagAptnmhF??","name":"Folsom Street","mode":"driving","maneuver":{"location":[-122.396505,37.785714],"bearing_before":45.0,"bearing_after":0.0,"instruction":"Your destination is on the right.","type":"arrive","modifier":"right"},"voiceInstructions":[],"bannerInstructions":[],"driving_side":"right","weight":0.0,"intersections":[{"location":[-122.396505,37.785714],"bearings":[225],"entry":[true],"in":0,"geometry_index":5,"admin_index":0}]}],"annotation":{"distance":[8.9,47.5,10.6,11.0,15.7],"duration":[2.295,12.224,2.716,2.339,3.316],"speed":[3.9,3.9,3.9,4.7,4.7],"maxspeed":[{"speed":40,"unit":"km/h"},{"speed":40,"unit":"km/h"},{"speed":40,"unit":"km/h"},{"speed":40,"unit":"km/h"},{"speed":40,"unit":"km/h"}],"congestion_numeric":[null,null,null,null,null]}},{"distance":126.228,"duration":29.089,"duration_typical":29.089,"summary":"Folsom Street","admins":[{"iso_3166_1":"US","iso_3166_1_alpha3":"USA"}],"steps":[{"distance":126.228,"duration":29.089,"duration_typical":29.089,"speedLimitUnit":"mph","speedLimitSign":"mutcd","geometry":"cfgagAptnmhFsc@wl@}E_HaBkCoBoC","name":"Folsom Street","mode":"driving","maneuver":{"location":[-122.396505,37.785714],"bearing_before":0.0,"bearing_after":45.0,"instruction":"Drive northeast on Folsom Street.","type":"depart"},"voiceInstructions":[{"distanceAlongGeometry":126.228,"announcement":"Drive northeast on Folsom Street. Then, in 400 feet, Your destination will be on the right.","ssmlAnnouncement":"\u003cspeak\u003e\u003camazon:effect name\u003d\"drc\"\u003e\u003cprosody rate\u003d\"1.08\"\u003eDrive northeast on \u003csay-as interpret-as\u003d\"address\"\u003eFolsom Street\u003c/say-as\u003e. Then, in 400 feet, Your destination will be on the right.\u003c/prosody\u003e\u003c/amazon:effect\u003e\u003c/speak\u003e"},{"distanceAlongGeometry":55.556,"announcement":"Your destination is on the right.","ssmlAnnouncement":"\u003cspeak\u003e\u003camazon:effect name\u003d\"drc\"\u003e\u003cprosody rate\u003d\"1.08\"\u003eYour destination is on the right.\u003c/prosody\u003e\u003c/amazon:effect\u003e\u003c/speak\u003e"}],"bannerInstructions":[{"distanceAlongGeometry":126.228,"primary":{"text":"Your destination will be on the right","components":[{"text":"Your destination will be on the right","type":"text"}],"type":"arrive","modifier":"right"}},{"distanceAlongGeometry":55.556,"primary":{"text":"Your destination is on the right","components":[{"text":"Your destination is on the right","type":"text"}],"type":"arrive","modifier":"right"}}],"driving_side":"right","weight":31.183,"intersections":[{"location":[-122.396505,37.785714],"bearings":[45],"entry":[true],"out":0,"geometry_index":0,"is_urban":true,"admin_index":0,"mapbox_streets_v8":{"class":"secondary"}},{"location":[-122.395773,37.7863],"bearings":[46,225],"entry":[true,false],"in":1,"out":0,"geometry_index":1,"is_urban":true,"admin_index":0,"mapbox_streets_v8":{"class":"secondary"}},{"location":[-122.395629,37.786411],"bearings":[48,226],"entry":[true,false],"in":1,"out":0,"geometry_index":2,"is_urban":true,"admin_index":0,"mapbox_streets_v8":{"class":"secondary"}},{"location":[-122.395559,37.78646],"bearings":[45,228],"entry":[true,false],"in":1,"out":0,"geometry_index":3,"is_urban":true,"admin_index":0,"mapbox_streets_v8":{"class":"secondary"}}]},{"distance":0.0,"duration":0.0,"duration_typical":0.0,"speedLimitUnit":"mph","speedLimitSign":"mutcd","geometry":"gxhagA|tlmhF??","name":"Folsom Street","mode":"driving","maneuver":{"location":[-122.395487,37.786516],"bearing_before":45.0,"bearing_after":0.0,"instruction":"Your destination is on the right.","type":"arrive","modifier":"right"},"voiceInstructions":[],"bannerInstructions":[],"driving_side":"right","weight":0.0,"intersections":[{"location":[-122.395487,37.786516],"bearings":[225],"entry":[true],"in":0,"geometry_index":4,"admin_index":0}]}],"annotation":{"distance":[91.7,17.7,8.2,8.9],"duration":[19.409,2.896,1.346,1.454],"speed":[4.7,6.1,6.1,6.1],"maxspeed":[{"speed":40,"unit":"km/h"},{"speed":40,"unit":"km/h"},{"speed":40,"unit":"km/h"},{"speed":40,"unit":"km/h"}],"congestion_numeric":[null,null,null,null]}}],"routeOptions":{"baseUrl":"https://api.mapbox.com","user":"mapbox","profile":"driving-traffic","coordinates":"-122.3972586,37.785119;-122.3964915,37.7857036;-122.3954721,37.7865042","language":"en","continue_straight":true,"roundabout_exits":true,"geometries":"polyline6","overview":"full","steps":true,"annotations":"congestion_numeric,maxspeed,speed,duration,distance,closure","voice_instructions":true,"banner_instructions":true,"voice_units":"imperial","waypoints":"0;1;2","waypoint_names":";;","enable_refresh":true},"voiceLocale":"en-US","requestUuid":"WkeYDlsiLGLzuRQxTOgT7H_V8ZObf7AjGtgTeguDE9R3pULBQV7ehw\u003d\u003d"}
```

**Comment by cafesilencio** [comment] 2022-01-18 18:55
I've tested with the route provided and I can't reproduce this with the current code base.  

cc @abhishek1508

**Comment by cafesilencio** [comment] 2022-01-20 23:25
Closing this as not reproducible.

**Closed by cafesilencio** 2022-01-20 23:25 UTC
