### ISSUE TITLE
Default Text Instructions are hardcoded

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#101] opened 2017-06-27 20:30 UTC
We are currently creating text instructions with hardcoded constants in our `DefaultInstructionEngine` --> this should be in a resource file that can be translated.  Problem is we don't have `Context` to extract those `String`s in the `DefaultInstructionEngine`

**Comment by cammace** [comment] 2017-07-01 16:34
duplicate of #114

**Closed by cammace** 2017-07-01 16:34 UTC
