### ISSUE TITLE
When i use this code  in mapbox there is no voice instruction

### ISSUE THREAD

**Issue by roxic8** [mapbox/mapbox-navigation-android#735] opened 2018-03-05 08:10 UTC
Point origin = originPosition;
        Point destination = destinationPosition;

        // Pass in your Amazon Polly pool id for speech synthesis using Amazon Polly
        // Set to null to use the default Android speech synthesizer
        String awsPoolId = null;

        boolean simulateRoute = true;

        NavigationViewOptions options = NavigationViewOptions.builder()
                .origin(origin)
                .destination(destination)
                .awsPoolId(awsPoolId)
                .shouldSimulateRoute(simulateRoute)
                .build();

        // Call this method with Context from within an Activity
        NavigationLauncher.startNavigation(MainActivity.this, options);

**Comment by danesfeder** [comment] 2018-03-05 14:36
Hey @roxic8, which version of the SDK are you using?  With simulation set to true, navigation should begin and you should start to hear instructions for the default `TextToSpeech` engine..

**Comment by roxic8** [comment] 2018-03-05 14:50
sdk version is 5.3.1 and the navigation is 0.10.0 and also the navigation-ui is 0.10.0 what do you think is wrong ???

**Comment by roxic8** [comment] 2018-03-05 14:51
yes it navigate but there is no voice speaking the direction

**Comment by roxic8** [comment] 2018-03-05 15:10
@danesfeder sdk version is 5.3.1 and the navigation is 0.10.0 and also the navigation-ui is 0.10.0 what do you think is wrong ???

**Comment by roxic8** [comment] 2018-03-05 15:10
@danesfeder yes it navigate but there is no voice speaking the direction

**Comment by Guardiola31337** [comment] 2018-03-22 10:30
cc: @devotaaabel who is actively working on voice-related PRs and can confirm if this is going to be fixed as part of https://github.com/mapbox/mapbox-navigation-android/pull/751 work.

**Comment by devotaaabel** [comment] 2018-03-22 15:54
@roxic8 I'm not sure what the issue is, but this shouldn't be an issue when our new `MapboxSpeech` is integrated, which should be within a week or so.

**Comment by Guardiola31337** [comment] 2018-04-06 16:38
https://github.com/mapbox/mapbox-navigation-android/pull/751 has landed 🎉 and will ship with the upcoming release.

@roxic8 feel free to comment/open a new ticket if you can still reproduce OP! Thanks again for reaching out and reporting your issue. Closing.

**Closed by Guardiola31337** 2018-04-06 16:38 UTC
Labels: bug, topic: instructions, topic: voice
