### ISSUE TITLE
CustomUIComponentStyleActivity.routesReqCallback is leaking

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#2823] opened 2020-04-21 22:14 UTC
When testing the examples test app `CustomUIComponentStyleActivity` run into the following leak

![custom_ui_component_style_activity_leak](https://user-images.githubusercontent.com/1668582/79918061-b2ea0d00-83f9-11ea-9a23-f778c20dc2f1.png)

![custom_ui_component_style_activity_leak_1](https://user-images.githubusercontent.com/1668582/79918068-b67d9400-83f9-11ea-8088-13b3c0ca301c.png)

![custom_ui_component_style_activity_leak_2](https://user-images.githubusercontent.com/1668582/79918075-baa9b180-83f9-11ea-9182-978398b22c01.png)

**Comment by JunDai** [comment] 2020-04-21 22:32
@Guardiola31337 - any special test steps? I tried it a few times with different test cases but couldn't reproduce it 🤔

**Comment by Guardiola31337** [comment] 2020-04-21 22:35
Hard to tell, I run into it and took screenshots. Will try to reproduce consistently.

**Comment by Guardiola31337** [comment] 2020-04-23 22:28
Not able to reproduce anymore. Think it was resolved by https://github.com/mapbox/mapbox-navigation-android/pull/2828

Closing for now, let's re-open if needed cc @JunDai @korshaknn

**Closed by Guardiola31337** 2020-04-23 22:28 UTC
Labels: bug, test app
