### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/mapboxsdk/Mapbox;

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-navigation-android#3894] opened 2021-01-07 10:34 UTC
I use mapbox navigation ui sdk and build an aar for other app to use it.

My aar build.gradle

```
plugins {
    id 'com.android.library'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            //proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    //mapbox
    api "com.mapbox.navigation:ui:1.1.0"
}
```

build.gradle(project)
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.1.1"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://mapbox.bintray.com/mapbox' }
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = 'mapbox'
                // Use the secret token you stored in gradle.properties as the password
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

My aar include a fragment
```
package com.nuro.customlib;

import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;

import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.mapbox.mapboxsdk.Mapbox;
import com.mapbox.mapboxsdk.maps.MapView;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;
import com.mapbox.mapboxsdk.maps.Style;

public class MapboxFragment extends Fragment {

    private MapView mapView;

    public MapboxFragment() {
        // Required empty public constructor
        Log.d("customlib","MapboxFragment");
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.d("customlib","MapboxFragment onCreate");
        Mapbox.getInstance(getActivity(), getString(R.string.access_token));
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        Log.d("customlib","MapboxFragment onCreateView");
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_mapbox, container, false);
        mapView = (MapView) view.findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);
        //mapView.getMapAsync(this);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                Log.d("customlib","MapboxFragment onMapReady1");
                mapboxMap.setStyle(Style.MAPBOX_STREETS, new Style.OnStyleLoaded() {
                    @Override
                    public void onStyleLoaded(@NonNull Style style) {

// Map is set up and the style has loaded. Now you can add data or make other map adjustments

                        Log.d("customlib","MapboxFragment onMapReady2");
                    }
                });
            }
        });
        return view;
    }

    @Override
    public void onResume() {
        super.onResume();
        if(mapView != null) {
            mapView.onResume();
        }
    }

    @Override
    public void onPause() {
        super.onPause();
        if(mapView != null) {
            mapView.onPause();
        }
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        if (mapView != null) {
            mapView.onSaveInstanceState(outState);
        }
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        if (mapView != null) {
            mapView.onLowMemory();
        }
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        if (mapView != null) {
            mapView.onDestroy();
        }
    }
}
```

I create an app to use this aar.
There are some error occurred while running the app.
Process: com.nuro.sdktest1, PID: 6767
```
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/mapboxsdk/Mapbox;
        at com.nuro.customlib.MapboxFragment.onCreate(MapboxFragment.java:32)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
        at android.app.Activity.performStart(Activity.java:6109)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
        at android.app.ActivityThread.access$1000(ActivityThread.java:164)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:5541)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:975)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxsdk.Mapbox" on path: DexPathList[[zip file "/data/app/com.nuro.sdktest1-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.nuro.customlib.MapboxFragment.onCreate(MapboxFragment.java:32) 
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838) 
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197) 
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080) 
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613) 
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236) 
        at android.app.Activity.performStart(Activity.java:6109) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:159) 
        at android.app.ActivityThread.main(ActivityThread.java:5541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:975) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 
    	Suppressed: java.lang.ClassNotFoundException: com.mapbox.mapboxsdk.Mapbox
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 28 more
```

**Comment by LukasPaczos** [comment] 2021-01-07 12:47
Hey @KayHung, could you try enabling multidex support for your app? Check out https://developer.android.com/studio/build/multidex.

**Comment by KayHung** [comment] 2021-01-08 07:36
@LukasPaczos 
I try enabling multidex support in my app, but still get same error.

**Comment by KayHung** [comment] 2021-01-18 03:18
@LukasPaczos 
Do you have any ideas about this issue?

**Comment by LukasPaczos** [comment] 2021-01-26 13:20
Hey @KayHung, I pasted your library setup into a sample project and didn't run into any issues when inflating the map.

Would you be able to create a small, self-contained sample project that reproduces the issue and provide it here so that we can verify what are the differences?

**Comment by KayHung** [comment] 2021-02-03 02:40
@LukasPaczos 
You have try to use my library to build an aar file and put the aar file into another project, it's can work well?

**Comment by LukasPaczos** [comment] 2021-02-03 11:19
If you are using a raw AAR and adding it to another, it won't package transitive dependencies. The navigation SDK depends on [a lot of other projects](https://github.com/mapbox/mapbox-navigation-android/blob/master/gradle/dependencies.gradle) and when you're using Maven distribution, Gradle downloads them for you automatically. This is not the case when you manually import an AAR, then you need to manually define those dependencies as well.

I think this is the root cause for the issue you're seeing, so I'm gonna go ahead and close this as not actionable.

**Closed by LukasPaczos** 2021-02-03 11:19 UTC
Labels: support

**Comment by KayHung** [comment] 2021-02-04 02:44
@LukasPaczos 
Because I need provide my AAR file to other people to use, if i also need to  implementation dependencies on project, I have to provide my secret token, so this is the only way for this case?

**Comment by LukasPaczos** [comment] 2021-02-04 11:16
@KayHung you should distribute your library via Maven and all of the consumers should use their own Mapbox tokens, subject to the [Mapbox ToS](https://www.mapbox.com/legal/tos).

/cc @jyrigo @zugaldia @truburt
