### ISSUE TITLE
OutOfMemoryError at DirectionsJsonObject.toJson

### ISSUE THREAD

**Issue by zeac** [mapbox/mapbox-navigation-android#5101] opened 2021-11-11 20:19 UTC
**Android API:** 6.0.1
**Mapbox Navigation SDK version:** 2.0.0

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 2093584 byte allocation with 1904296 free bytes and 1859KB until OOM
       at java.lang.StringFactory.newStringFromChars(StringFactory.java)
       at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:629)
       at java.lang.StringBuffer.toString(StringBuffer.java:723)
       at java.io.StringWriter.toString(StringWriter.java:100)
       at com.google.gson.Gson.toJson(Gson.java:639)
       at com.google.gson.Gson.toJson(Gson.java:618)
       at com.mapbox.api.directions.v5.models.DirectionsJsonObject.toJson(DirectionsJsonObject.java:28)
       at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl$setRoute$2.invokeSuspend(MapboxNativeNavigatorImpl.kt:176)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```
### Steps to trigger behavior

Exact steps to reproduce are unknown. Anyway, trying to get a string with a json, that can grow to 2MB, is a bad idea. Because of memory fragmentation it can lead to crash even if there is a free memory in the system.

**Comment by LukasPaczos** [comment] 2021-11-12 15:28
Thanks @zeac, closing for now as a duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/4153.

**Closed by LukasPaczos** 2021-11-12 15:28 UTC
