### ISSUE TITLE
Crash With Mapbox Navigation Android

### ISSUE THREAD

**Issue by jkpatel1463** [mapbox/mapbox-navigation-android#4590] opened 2021-07-09 10:35 UTC
Hello there

When using Mapbox Navigation Android SDK with demo, app is crashing. We have created a support ticket in Mapbox support center as well, Here is the link as well.
You can download source code from there with crash log as well: https://support.mapbox.com/hc/en-us/requests/108854?page=1

**Device: Redmi Note 7s**
**Android API: 10 API 29**
**Mapbox Navigation SDK version: https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.0.0-beta.17**

### Steps to trigger behavior

 1. Run attached demo
 2. Click on turn by turn navigation
 3. Long tap on map to start navigation
 4. Its crash

### Expected behavior
- It should show navigation

### Actual behavior
- App is crashing

**Comment by LukasPaczos** [comment] 2021-11-01 12:30
Thanks for reporting the issue @jkpatel1463, closing here since it's resolved already. Let's reopen if this is still reproducible with `v2.1.0-beta.2`.

**Closed by LukasPaczos** 2021-11-01 12:30 UTC
Labels: bug
