### ISSUE TITLE
Voice instructions not overridden anymore after toggling to night mode in EmbeddedNavigationActivity

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1243] opened 2018-08-28 08:19 UTC
Noticed that voice instructions get messed up after clicking multiple times on the `fabNightModeToggle`. Instead of being overridden to [`"All announcements will be the same."`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EmbeddedNavigationActivity.java#L172) are spoken normally (not overridden anymore). Found when running the [`EmbeddedNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EmbeddedNavigationActivity.java) example from the test app.

**Comment by JunDai** [comment] 2020-05-22 21:30
ok, checked this issue for a while and found that there was a race condition in this case. The `EmbeddedNavigationActivity` was just re-created and in middle of `fetching route` at the time that NavigationViewModel, because the NavigationViewModel is an activity lifecycle awareness component and in this case it's singleton I believe, received the voiceInstruction callback.

I think this issue was caused by the implementation of the example doesn't consider this corner case. But this is something worth to verify when refactor the voice in 2.0 UI SDK.

**Comment by Guardiola31337** [comment] 2020-07-08 14:10
@asinghal22 is this something we want to support in `1.0`?

cc @JunDai @abhishek1508

**Comment by abhishek1508** [comment] 2020-07-14 19:07
I am going to close this as this will involve working with lifecycle changes on the `NavigationViewModel`, which is kind of a big lift and a major refactor. We can revisit this after the launch of 1.0

**Closed by abhishek1508** 2020-07-14 19:07 UTC
Labels: bug, test app, topic: voice
