### ISSUE TITLE
Android: Incorrect Direction Images

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#396] opened 2017-10-18 11:36 UTC
Being In The UK we drive on the left side of the road, i approached a rounder-bout well testing the Navigation yesterday, the Instructions told me to `At the rounder-bout take the second exit`

Below is the image that was presented to me - this is showing driving the wrong way around the rounder-bout.

![screenshot_20171017-154758](https://user-images.githubusercontent.com/32104383/31716697-ed885d3e-b400-11e7-8020-ebe759298b67.png)

**Comment by cammace** [comment] 2017-10-18 13:00
Hey @Danny-James, thanks for reporting, that doesn't look like a roundabout which is most likely an issue with our data rather than an issue with the navigation client. Could you report this upstream using [this tool](https://www.mapbox.com/directions-feedback/mapbox/#15/-122.4365/37.7794) so we can get the proper eyes on it and get it fixed?

**Comment by Danny-James** [comment] 2017-10-18 13:43
@cammace the navigation image isn't a rounder-bout as i hadn't approached the rounder-bout, their was actually a rounderbout around the right bend shown above, what im saying is we don't drive on the right side of the road.

**Comment by Danny-James** [comment] 2017-11-27 14:52
@cammace this still seems to be an issue, in the UK we drive on the left side of the road, the images are showing as if we drive on the right hand side of the road see the image below this is showing for take the third exit.

The image actually looks like take the first exit if driving on the right side of the road.

See 2nd Instuction in Screenshot Below.

![screenshot_20171122-135352](https://user-images.githubusercontent.com/32104383/33272610-91ff0638-d382-11e7-9e1d-ed44aaa15608.png)

**Comment by cammace** [comment] 2017-11-27 15:05
OSRM supports different side of the road driving with the `left_hand_driving` boolean (set to true if driving on the lefthand side). This isn't yet supported by the directions API though which means we can't fix this issue yet. Since this is something that needs to be worked out in the directions API before resolving here, we will keep tracking progress there.

**Comment by Danny-James** [comment] 2017-11-27 16:18
@cammace no problem thanks for looking at this issue 👍

**Comment by mdakram** [comment] 2018-06-05 07:07
Hi @cammace any timeline on this?

**Comment by danesfeder** [comment] 2018-06-05 11:53
@Danny-James @mdakram the solution here would be flipping all maneuver images if the driving side is on the left side correct?

**Comment by Danny-James** [comment] 2018-06-05 13:02
@danesfeder is their an option for this if we are using the `NavigationLauncher` ?

**Comment by mdakram** [comment] 2018-06-05 14:27
@danesfeder not exactly as turn right in case of right hand or left hand driving will remain same. Issue i found is with u-Turn and roundabout. @Danny-James you can share your experience.

**Comment by danesfeder** [comment] 2018-06-05 14:32
@mdakram uturns should be fixed with #908 and roundabouts now consider the actual angle at which you exit the roundabout #854

**Comment by danesfeder** [comment] 2018-06-05 14:34
@Danny-James the `ManeuverView` doesn't consider the driving side currently (we should do this automatically, no need for options imo)

**Comment by Danny-James** [comment] 2018-06-05 14:35
@danesfeder Thank You.

**Comment by Danny-James** [comment] 2018-08-02 08:44
@danesfeder I seem to still be getting issue with the Maneuver Images, take a look at the two below images, they don't match and the notification image is showing as driving on the right side of the road.

![screenshot_20180731-115116_route info](https://user-images.githubusercontent.com/32104383/43572904-187275a4-9630-11e8-8858-1f5386f954f4.jpg)
![screenshot_20180731-115128_route info](https://user-images.githubusercontent.com/32104383/43572905-1893c790-9630-11e8-99e5-80d7f2d39d55.jpg)

**Comment by 1ec5** [comment] 2018-11-02 17:19
The screenshots above appear to be 180° off, not flipped. [The Directions API documentation](https://www.mapbox.com/api-documentation/#banner-instruction-object) states that the roundabout degrees in banner instruction objects are measured head-on, not from the driver’s perspective:

> The degrees at which you will be exiting a roundabout, assuming `180` indicates going straight through the roundabout.

**Comment by 1ec5** [comment] 2018-11-03 17:10
Also tracking this issue for iOS in mapbox/mapbox-navigation-ios#1812.

**Comment by andrewharvey** [comment] 2019-04-02 12:03
:+1:

> @mdakram uturns should be fixed with #908 and roundabouts now consider the actual angle at which you exit the roundabout #854

This is still an issue as of 0.33.2, for both uturns and roundabouts.

> @Danny-James @mdakram the solution here would be flipping all maneuver images if the driving side is on the left side correct?

Not quite. The left hand side driving icon for turn right at the roundabout would be the turn left at the roundabout's right hand side driving icon, but mirrored on the vertical axis.

Would it be simpler to just embed separate icons or build in this flipping logic?

Happy to try to help, but I wouldn't know where to start.

**Comment by Danny-James** [comment] 2019-07-04 12:38
@danesfeder I'm now using the `latest stable` version of `NavigationUI` and this issue is still present; The images below I seem to be getting problems with `Left Turns` showing a `Right Turn` manoeuvre image 

I've just taken a 1 hour journey and every `Left Turn` was a `Right Turn` image I also came across one issue with a Traffic Circle. The manoeuvre image was showing the driving line on the wrong side of the road for UK Driving.

**Images**
![Screenshot_20190704-103137](https://user-images.githubusercontent.com/32104383/60667258-00908b80-9e61-11e9-9fc0-568180bc5577.png)
![Screenshot_20190704-103333](https://user-images.githubusercontent.com/32104383/60667259-00908b80-9e61-11e9-9c4d-cd348a3fd317.png)
![Screenshot_20190704-110105](https://user-images.githubusercontent.com/32104383/60667260-01292200-9e61-11e9-9184-96bab9e188e8.png)
![Screenshot_20190704-125049](https://user-images.githubusercontent.com/32104383/60667262-01292200-9e61-11e9-875f-0537a7237565.png)

**Comment by dhodge229** [comment] 2019-08-29 19:31
Have noted similar issue with backwards instruction images on occasion. Using InstructionView library version 0.41.0

**Comment by 1ec5** [comment] 2019-09-04 02:22
The issue is that the maneuver view is horizontally flipped for left-hand driving, regardless of the maneuver type:

https://github.com/mapbox/mapbox-navigation-android/blob/5036133b0e3efd40ddeb16ef785dd7f41a4c50ad/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/maneuver/ManeuverView.java#L237-L240

On iOS, we flip based on the driving side for [`roundabout`, `rotary`, `roundaboutTurn`](https://github.com/mapbox/mapbox-navigation-ios/blob/2d97062caa6ba140e90a7a11e142a31c375d96d3/MapboxNavigation/ManeuverView.swift#L97-L99) because the `degrees` field is specific to those maneuver types only. Left turns are also flipped because the image assets are for right turns; `uturn` is a special case based on the driving side.

**Closed** 2019-09-16 15:41 UTC
Labels: bug, high priority, navigation-ui, topic: directions, topic: instructions

**Comment by 1ec5** [comment] 2019-10-11 20:55
Continued in #2191.
