### ISSUE TITLE
Unsure whether to use MapView or NavigationView for in-app-navigation usecase

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3477] opened 2020-08-20 11:20 UTC
**Android API:** 29 / Android 10
**Mapbox Navigation SDK version:** 
`implementation 'com.mapbox.navigation:ui-v1:1.0.0-SNAPSHOT'`
`implementation 'com.mapbox.navigation:core:1.0.0-rc.4'`

Hello there, I'm still trying to get Mapbox in-app-navigation working on our app ;).

My colleague began working on this and he has used MapView + MapboxNavigation, NavigationMapRoute and MapboxMap. Now I took this over and some things are not working. For example, I have gotten the MapboxReplayer to work, but the instructions don't update. Also, the volume button does nothing, there are no voice outputs and also the camera is not tracking the driver :D.

I've now looked at the mapbox examples, specifically `NavigationViewActivity`. There, a `NavigationView` is used.

Sooo.... what should I use? We want to implement a custom view which shows the remaining duration and distance etc at the bottom. We want to dynamically update the route when we receive an event from our API.

**Comment by carstenhag** [comment] 2020-08-24 07:08
cc @LukasPaczos or any colleague 🥇  :).

**Comment by abhishek1508** [comment] 2020-08-27 17:57
> We want to implement a custom view which shows the remaining duration and distance etc at the bottom. We want to dynamically update the route when we receive an event from our API.

Since you want to implement a custom view, I would not suggest using `NavigationView`. The idea behind `NavigationView` is to take care of complete TBT scenario. It has different views arranged specifically and those cannot be customized from the outside except for the colors. The best path forward would be to use a combination of `MapView` + `MapboxNavigation` to listen to all the events emitted from the Core portion of the SDK and use `NavigationMapRoute` and `MapboxMap` to handle any UI changes on the map. Look at `BasicNavigationActivity`, `NavigationMapRouteActivity` and [others](https://github.com/mapbox/mapbox-navigation-android/tree/master/examples/src/main/java/com/mapbox/navigation/examples/core) for better understanding on how to use them

cc @carstenhag

**Comment by carstenhag** [comment] 2020-08-27 18:39
Thanks a lot! Did not get that NavigationView is a more simplified/restricted version, good to know. So on my side this is sorta closable, just that on the docs side this can be improved imo.

**Comment by abhishek1508** [comment] 2020-08-27 18:48
Sounds good. Closing as confirmed.

**Closed by abhishek1508** 2020-08-27 18:48 UTC
