### ISSUE TITLE
No voice in 0.13

### ISSUE THREAD

**Issue by chooble** [mapbox/mapbox-navigation-android#922] opened 2018-05-07 09:11 UTC
Since 0.13 I am not getting any voice instructions. 
I get my routes via an external server which gets the DirectionRoute from Mapbox. Then I process the json to create a DirectionRoute via the Builder. When using the builder I set the RouteOptions.language: 

```
RouteOptions routeOptions = RouteOptions.builder()
                    .language("en")
```
And the DirectionRoute.voiceLanguage

```
directionsRoute = DirectionsRoute.builder()
                    .voiceLanguage("en")  //since 0.13 
```

I start the navigation this way:

```
navigationOptions = MapboxNavigationOptions.builder()
      .locale(Locale.forLanguageTag("en"))

NavigationViewOptions options = NavigationViewOptions.builder()
      .navigationOptions(navigationOptions)
      .directionsRoute(route)

navigationView.startNavigation(options);
```

I also tried different combinations of .language, .voiceLanguage and .locale. Also not setting them, but with no result.

There are no logs or errors describing what is happening.

Android API: 27 (OnePlus 5) and 24 (Samsung J5)
Mapbox Navigation SDK version: 0.13

### Expected behavior
I expected that the navigationView would give me voice instruction without the need to change anything in code when transferring from 0.12 to 0.13

### Actual behavior
No voice instructions

**Comment by devotaaabel** [comment] 2018-05-11 18:35
Hi @chooble , were you using an `awsPoolId` previously? And are you using `NavigationView` or a custom view implementation?

**Comment by chooble** [comment] 2018-05-14 06:52
Hi @devotaaabel! No I wasn't using `awsPoolId` previously and I'm using the default NavigationView.

**Comment by danesfeder** [comment] 2018-05-16 15:15
@chooble Can you add a `MilestoneEventListener` via [`NavigationViewOptions#milestoneEventListener`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewOptions.java#L67)?  

After adding this, can you verify that `VoiceInstructionMilestone` is being sent via this callback as you travel along the route?  Thanks, this will help us determine the source of the bug you're seeing.

**Comment by tonyc10** [comment] 2018-05-16 15:40
I am also not getting voice in 0.13, and, like @chooble, am constructing my own DirectionsRoute based on a response from our own OSRM route server.   It worked fine earlier and still works well except for the voice.

I've got nothing else to add at this point and have been drawn off to another urgent project for a few days -- I can spend some time troubleshooting with you early next week if it's still a mystery.

**Comment by danesfeder** [comment] 2018-05-16 15:43
@tonyc10 Do you mind trying the same suggestion https://github.com/mapbox/mapbox-navigation-android/issues/922#issuecomment-389556517?  Voice instructions are provided by the response from the directions API, so I think something may be going on with that.

**Comment by chooble** [comment] 2018-05-16 16:06
@danesfeder Hi! I added the MilestoneEventListener and getting this output (instruction is in dutch):

I'm logging this:



    @Override
    public void onMilestoneEvent(RouteProgress routeProgress, String instruction, Milestone milestone) {
        Log.d("NavigationActivity", "\n");
        Log.d("NavigationActivity", "onMilestoneEvent, instruction:" + instruction);
        if(milestone.getInstruction()!=null) Log.d("NavigationActivity", "onMilestoneEvent, milestone.getInstruction:" + milestone.getInstruction().toString());
        Log.d("NavigationActivity", "onMilestoneEvent, milestone.getIdentifier:" + milestone.getIdentifier());
        if(progress!=null) Log.d("NavigationActivity", "onMilestoneEvent, milestone.isOccurring:" + milestone.isOccurring(progress, routeProgress));
        Log.d("NavigationActivity", "\n");

        progress = routeProgress;
    }


And the output is:

`05-16 18:01:21.404 2578-2578/ D/NavigationActivity: 
    onMilestoneEvent, instruction:Over 700 meter, ga rechtsaf naar Universiteitsweg (N412)
    onMilestoneEvent, milestone.getInstruction:com.mapbox.services.android.navigation.v5.milestone.VoiceInstructionMilestone$1@3031b59
    onMilestoneEvent, milestone.getIdentifier:1
    onMilestoneEvent, milestone.isOccurring:false`

`05-16 18:01:39.384 2578-2578/ D/NavigationActivity: 
    onMilestoneEvent, instruction:Ga rechtsaf naar Universiteitsweg (N412)
    onMilestoneEvent, milestone.getInstruction:com.mapbox.services.android.navigation.v5.milestone.VoiceInstructionMilestone$1@232e733
    onMilestoneEvent, milestone.getIdentifier:1
    onMilestoneEvent, milestone.isOccurring:false`

`05-16 18:01:39.389 2578-2578/ D/NavigationActivity: 
    onMilestoneEvent, instruction:
    onMilestoneEvent, milestone.getIdentifier:2
    onMilestoneEvent, milestone.isOccurring:false`

`05-16 18:01:47.405 2578-2578/ D/NavigationActivity: 
    onMilestoneEvent, instruction:Neem Utrechtseweg (N237) in oostelijke richting, daarna links aanhouden op de splitsing naar Utrechtseweg (N237)
    onMilestoneEvent, milestone.getInstruction:com.mapbox.services.android.navigation.v5.milestone.VoiceInstructionMilestone$1@3d58648
    onMilestoneEvent, milestone.getIdentifier:1
    onMilestoneEvent, milestone.isOccurring:false`

`05-16 18:01:47.408 2578-2578/ D/NavigationActivity: 
    onMilestoneEvent, instruction:
    onMilestoneEvent, milestone.getIdentifier:2
    onMilestoneEvent, milestone.isOccurring:false`

`05-16 18:02:16.384 2578-2578/ D/NavigationActivity: 
    onMilestoneEvent, instruction:Links aanhouden op de splitsing naar Utrechtseweg (N237), daarna ga linksaf naar Utrechtseweg (N225)
    onMilestoneEvent, milestone.getInstruction:com.mapbox.services.android.navigation.v5.milestone.VoiceInstructionMilestone$1@e7dbb29
    onMilestoneEvent, milestone.getIdentifier:1
    onMilestoneEvent, milestone.isOccurring:false`

`05-16 18:02:16.387 2578-2578/ D/NavigationActivity: 
    onMilestoneEvent, instruction:
    onMilestoneEvent, milestone.getIdentifier:2
    onMilestoneEvent, milestone.isOccurring:false`

`05-16 18:02:24.376 2578-2578/ D/NavigationActivity: 
    onMilestoneEvent, instruction:
    onMilestoneEvent, milestone.getIdentifier:2
    onMilestoneEvent, milestone.isOccurring:false`

**Comment by tonyc10** [comment] 2018-05-16 17:09
I used @chooble's logging code and looks like my results are the same:

```
Turn right onto East 36th Street
onMilestoneEvent, milestone.getInstruction:com.mapbox.services.android.navigation.v5.milestone.VoiceInstructionMilestone$1@b08c6dc
onMilestoneEvent, milestone.getIdentifier:1

onMilestoneEvent, instruction:
onMilestoneEvent, milestone.getIdentifier:2
onMilestoneEvent, milestone.isOccurring:false

onMilestoneEvent, instruction:Turn left onto 46th Avenue South
onMilestoneEvent, milestone.getInstruction:com.mapbox.services.android.navigation.v5.milestone.VoiceInstructionMilestone$1@d731fdd
onMilestoneEvent, milestone.getIdentifier:1
onMilestoneEvent, milestone.isOccurring:false

onMilestoneEvent, instruction:
onMilestoneEvent, milestone.getIdentifier:2
onMilestoneEvent, milestone.isOccurring:false

onMilestoneEvent, instruction:Turn left onto East 46th Street (CR 46)
onMilestoneEvent, milestone.getInstruction:com.mapbox.services.android.navigation.v5.milestone.VoiceInstructionMilestone$1@590a6eb
onMilestoneEvent, milestone.getIdentifier:1
onMilestoneEvent, milestone.isOccurring:false

onMilestoneEvent, instruction:
onMilestoneEvent, milestone.getIdentifier:2
onMilestoneEvent, milestone.isOccurring:false

onMilestoneEvent, instruction:Continue onto Ford Parkway (CR 42)
onMilestoneEvent, milestone.getInstruction:com.mapbox.services.android.navigation.v5.milestone.VoiceInstructionMilestone$1@b8de496
onMilestoneEvent, milestone.getIdentifier:1
onMilestoneEvent, milestone.isOccurring:false
 
onMilestoneEvent, instruction:
onMilestoneEvent, milestone.getIdentifier:2
onMilestoneEvent, milestone.isOccurring:false

onMilestoneEvent, instruction:Turn right
onMilestoneEvent, milestone.getInstruction:com.mapbox.services.android.navigation.v5.milestone.VoiceInstructionMilestone$1@9dd0517
onMilestoneEvent, milestone.getIdentifier:1
onMilestoneEvent, milestone.isOccurring:false
```

**Comment by danesfeder** [comment] 2018-05-18 13:40
@chooble @tonyc10 Okay great, thank you both.  So this means valid voice instructions are being fired, but something may be happening with the speech player code on our side.  We will look into this - thanks for the help.

**Comment by danesfeder** [comment] 2018-05-31 18:15
Hey @chooble @tony-cj can you both check out the newest release of the SDK `0.14.0` - please note - there are API breaking changes: https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.14.0

**Comment by chooble** [comment] 2018-06-01 09:26
I don't seem to get it working. The MilestoneEvent is not triggered, but the RouteProgress has the voice instructions.  I've set the .language and .voiceUnit like you described in the release notes.

**Comment by chooble** [comment] 2018-06-01 09:28
I don't seem to get it working. I've set the .language and .voiceUnit in RouteOptions like you described in the release notes. Also the .voiceLanguage in de DirectionRoute builder.

**Comment by skienzl** [comment] 2018-06-04 14:08
@danesfeder i think the error could be related to a missing error case during the download of the mapbox voice file: [MapboxSpeechPlayer.java](https://github.com/mapbox/mapbox-navigation-android/blob/7a3a704fc443aa9d63e2bf76498bf691221e5d77/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java#L152)

If the response is not successful (`if (response.isSuccessful())`) there is no error callback.

**Comment by tonyc10** [comment] 2018-06-04 16:44
No luck for me either.  I put in 0.14.0, fixed the breaking API changes,
and ran it — still no voice.  I also played around with the RouteOptions
like Tristan.

I construct my DirectionsRoute from the JSON of our OSRM server, with a
RouteOptions I build.  All worked, including voice, prior to 0.13.0.

- Tony

**Comment by devotaaabel** [comment] 2018-06-06 17:39
@skienzl I'll get that in the next release.

**Comment by chooble** [comment] 2018-06-18 08:43
@devotaaabel @danesfeder , do you have an ETA for the solution? Did you already found cause of the problem?

**Comment by devotaaabel** [comment] 2018-06-18 18:39
@chooble we have still been unable to reproduce your error, but I did add an extra call to retry using native TTS if `MapboxSpeech` fails here: https://github.com/mapbox/mapbox-navigation-android/commit/01aefe0da32dbc081d7b69d33f2d9ee51a2f4a35. I also have a PR open right now to log errors to hopefully help you find your issue if the latter doesn't help: https://github.com/mapbox/mapbox-navigation-android/pull/1036. There will most likely be a release this week including both.

**Comment by Guardiola31337** [comment] 2018-06-25 12:41
Hey @chooble 👋 `0.15.0` was released including @devotaaabel's above-mentioned changes.

Could you retest your issues again with our newest release of the SDK [`0.15.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.15.0)?

cc @tonyc10 @skienzl

**Comment by tonyc10** [comment] 2018-06-25 15:21
0.15.0 brings back the voice for my app!  Hooray!!

To summarize my experience, 0.13.0, 0.14.0 = no voice;  0.15.0 = voice.

Thank you.

**Comment by tonyc10** [comment] 2018-06-25 15:34
I do now get a crash when selecting the mute button (speaker icon) on the
turn by turn display:

    java.lang.NullPointerException: Attempt to invoke virtual method 'void
com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.setMuted(boolean)'
on a null object reference
        at
com.mapbox.services.android.navigation.ui.v5.voice.NavigationInstructionPlayer.setMuted(NavigationInstructionPlayer.java:50)
        at
com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.setMuted(NavigationViewModel.java:100)
        at
com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView$6.onClick(InstructionView.java:593)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)


When voice wasn't working, selecting that button had no effect.

**Comment by chooble** [comment] 2018-06-25 15:40
@Guardiola31337 Great! It's working now! 👍 🥇

**Comment by danesfeder** [comment] 2018-06-25 15:50
@tonyc10 Unfortunately this is a known issue and is being addressed in https://github.com/mapbox/mapbox-navigation-android/pull/1054.  Thanks for the feedback and glad to hear we are working towards a solution here.

**Comment by Guardiola31337** [comment] 2018-07-02 19:29
Going to go ahead and close this as OP should be fixed since `0.15.0` (we have also released `0.16.0-beta.1` afterwards) - if you find the issue persists, please feel free to re-open and we will continue to dig on this issue. Thanks for bringing this to our attention!

cc @chooble @tony-cj @skienzl

**Closed by Guardiola31337** 2018-07-02 19:29 UTC
Labels: bug, navigation-ui, needs research, release blocker

**Comment by JFDionne** [comment] 2019-07-30 23:14
@tonyc10 
Hi, I know this is a old thread, but any chance you can share how you do the conversion of OSRM to mapbox?

**Comment by tonyc10** [comment] 2019-07-31 19:44
@JFDionne 

It's been a year since I thought about this (or looked at this app) but I can share some code.    Looking over this, it was pretty thick stuff — the key was migrating the polylines to version 6.

From our OSRM server, I got a response that fit into this Kotlin data class:

```
data class RouteResponse(
        val code: String,
        val routes: Array<JsonObject>,
        val waypoints: Array<Waypoint>
)
```
With Waypoint being:
```
data class Waypoint(
        val name: String,
        val hint: String,
        val location: Array<Double>
)
```
I got one or two objects in the `routes` array, depending on my request, With each one of these, I did the following conversion, using mapbox, v5, classes `RouteOptions` and `DirectionsRoute`, `com.mapbox.geojson.utils.PolylineUtils`, and 
a `JsonObject` extension function I wrote called `toDirectionsRoute`

```
fun JsonObject.toDirectionsRoute(options: RouteOptions): DirectionsRoute {

    this.migratePolylinesTo6()

    val tempRoute = DirectionsRoute.fromJson(this.toString())
    return  tempRoute
            .toBuilder()
            .routeOptions(options)
            .build()
}

fun JsonObject.migratePolylinesTo6() {

    fun switchGeometryTo6(jsonObj: JsonObject): List<Point> {

        val geometryJson = jsonObj.get("geometry") ?: throw IllegalArgumentException(
                "Attempt to modify geometry on Json route object with no geometry.  Does this Json object represent an OSMR route?")

        // decode / recode
        try {
            val points = PolylineUtils.decode(geometryJson.asString, 5)
            val geometryAmended = PolylineUtils.encode(points, 6)
            // put back corrected encoding
            jsonObj.addProperty("geometry", geometryAmended)
            return points
        }
        catch (e: Exception) {
            throw IllegalArgumentException(
                    "Unable to modify geometry on JsonObject -- Does this object represent an OSMR route?")
        }
    }

    val legsJson = get("legs") ?: throw IllegalArgumentException(
            "Attempt to modify geometry on Json route object with no legs.  Does this Json object represent an OSMR route?")
    if (! legsJson.isJsonArray) throw IllegalArgumentException(
            "Attempt to modify geometry on Json route where legs element not an array.  Does this Json object represent an OSMR route?")

    val legsArray = legsJson.asJsonArray
    val allThePoints = mutableListOf<Point>()

    for (leg in legsArray) {

        val stepsJson = leg.asJsonObject.get("steps")
        if (stepsJson == null) throw IllegalArgumentException(
                "Attempt to modify steps geometry on Json route object with no steps.  Does this Json object represent an OSMR route?")
        if (! stepsJson.isJsonArray) throw IllegalArgumentException(
                "Attempt to modify steps geometry on Json route where steps element not an array.  Does this Json object represent an OSMR route?")

        val stepsArray = stepsJson.asJsonArray


        for (stepObj in stepsArray) {
            allThePoints.addAll(
                    switchGeometryTo6(stepObj.asJsonObject))
        }
    }
    val geometryAmended = PolylineUtils.encode(allThePoints, 6)
    // put back corrected encoding
    addProperty("geometry", geometryAmended)

}
```

Good luck!

**Comment by JFDionne** [comment] 2019-07-31 20:07
@tonyc10

Thanks, but I’m curious, how did you build the var options (routeOptions)

Osrm can now return polyline6.

**Comment by JFDionne** [comment] 2019-07-31 21:07
@tonyc10 
And I'm wondering, the way you are doing it, it was filling the voiceInstructions and bannerInstruction ?

**Comment by tonyc10** [comment] 2019-07-31 21:49
Here is the code I had to build routeOptions:

fun routeOptions(
   start: Point,
   end: Point,
   includeAlternatives: Boolean = false,
   uuid: String = start.to(end).hashCode().toString()   // just a
unique string here
): RouteOptions {

    return RouteOptions.builder()
       .baseUrl(BuildConfig.BASE_URL)
       .accessToken(Mapbox.getAccessToken()!!)
       .user("mapbox")
       .profile("driving-traffic")
       .alternatives(includeAlternatives)
       .geometries(DirectionsCriteria.GEOMETRY_POLYLINE6)
       .continueStraight(true)
       .voiceInstructions(true)
       .steps(true)
       .roundaboutExits(true)
       .overview(DirectionsCriteria.OVERVIEW_FULL)
       .voiceUnits(DirectionsCriteria.IMPERIAL)
       .language(Locale.US.getLanguage())
       .bannerInstructions(true)
       .coordinates(listOf(start, end))
       .requestUuid(uuid)
       .build()
}


> the way you are doing it, it was filling the voiceInstructions and bannerInstruction ?

If you say so.  Does the RouteOptions code above provide more insight?

**Comment by JFDionne** [comment] 2019-07-31 22:20
@tonyc10 
Sorry, it was more a question :) with your code do the voiceInstructions got filled?

I'll try your code, but what was the value of BuildConfig.BASE_URL? The url of your osrm server? or api.mapbox.com?

**Comment by tonyc10** [comment] 2019-08-01 00:35
The URL was to our own OSRM instance.  I had voice working, that was always
required, although there was an issue I had to work around at some point --
maybe it wasn't working in an SDK version release.

**Comment by JFDionne** [comment] 2019-08-01 02:41
@tonyc10 
Strange, because I can't have the voice working since the voiceInstructions is null. 

Thanks you for all those information :)
