### ISSUE TITLE
Instruction banner abbreviates too aggressively

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-android#3097] opened 2020-06-03 19:19 UTC
The instruction banner is abbreviating road names too aggressively. In the screenshot below, the banner should say “Park Road Northwest” or “Park Road NW” if that doesn’t fit. Compare to the current road name label, which says “Park Rd NW”. It should only be abbreviated “Pk Rd NW” under extremely space-constrained conditions.

![abbreviations](https://user-images.githubusercontent.com/1231218/83679291-03758e00-a594-11ea-9f5a-29cc2eb5eac8.png)

Reproduces in v1.0.0-qa-w22. Might be related to #1201.

/cc @Guardiola31337 @abhishek1508

**Comment by 1ec5** [comment] 2020-06-03 19:22
This code appears to be what’s responsible for progressively abbreviating the label:

https://github.com/mapbox/mapbox-navigation-android/blob/a138a0119d3cfc6b6a133259ef0373035d9cce86/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/AbbreviationCreator.java#L77-L94

In case it helps, the corresponding iOS implementation is in https://github.com/mapbox/mapbox-navigation-ios/blob/6e311dd4b40c634d094721fa880b63f9ea2a6044/MapboxNavigation/InstructionPresenter.swift#L61-L79.

**Comment by JunDai** [comment] 2020-06-04 23:21
@1ec5 - hey, which device did you use for this testing? 
I tried `Nexus 5X` and `Samsung S9+`, they can show the full `Park Road Northwest` in the banner instruction view in portrait mode. btw, I am referring to this position: `Park Rd NWWashington, DC`

If the position is different, please also share the route to me. Thanks!

**Comment by JunDai** [comment] 2020-06-04 23:22
forgot to mention that I can reproduce the #1201 . I will fix it with this issue.

**Comment by JunDai** [comment] 2020-06-05 18:54
@zugaldia - @1ec5 mentioned the issue was found in a recording shared by you? If that's the case, do you still remember which device were you using for the test?

**Comment by zugaldia** [comment] 2020-06-05 23:36
@JunDai yup, this was a Pixel 3.

**Comment by JunDai** [comment] 2020-06-06 00:27
@zugaldia - can you share with me the route you were testing if you still remember?
I use the latest master code and test it on a Pixel 3 emulator with Android API 28. It seems working fine.
![Screenshot_1591403104](https://user-images.githubusercontent.com/3918950/83931481-d66eda00-a751-11ea-9337-0ca2d4efd01f.png)

**Comment by JunDai** [comment] 2020-06-06 00:28
@Guardiola31337 - do you have a Pixel 3 device can run a quick test of this case? 🙏

**Comment by abhishek1508** [comment] 2020-06-06 00:58
@JunDai I have a PIXEL 3. I will test it for you and inform you. Can you share the source and destination?

**Comment by abhishek1508** [comment] 2020-06-06 01:08
I cannot reproduce this in Pixel 3. Please see the attached.

![Screenshot_20200605-180632](https://user-images.githubusercontent.com/9770186/83932448-79762280-a757-11ea-9a45-b9587fdee868.png)

cc @JunDai @zugaldia

**Comment by JunDai** [comment] 2020-06-06 15:29
@zugaldia - I will close this one since we couldn't reproduce it. Feel free to reopen it if you still have issue. I can take a look then.

**Closed by JunDai** 2020-06-06 15:29 UTC
Labels: UI SDK v1+, beta blocker, bug, navigation-ui, topic: instructions

**Comment by Guardiola31337** [comment] 2020-06-08 14:06
@JunDai 
> do you have a Pixel 3 device can run a quick test of this case? 🙏

I couldn't reproduce either 🎉

**Comment by zugaldia** [comment] 2020-06-09 00:00
Could this be a night mode issue? Are there any other differences between the two besides color palette?
