### ISSUE TITLE
Location puck's velocity

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4140] opened 2021-03-16 15:37 UTC
This ticket analyzes possible improvements to the puck's location interpolation that's executed by the `NavigationLocationProvider`.

We currently recommend and set by default all location transition durations to 1 second, for both camera and puck linear transition. However, the puck can also accept a list of keypoints, which are intermediate points on a maneuver that prevent the puck from cutting the corners. Since keypoints are not universally distributed between the current location on the route line (or road edge) and target location, they significantly change the velocity of the puck.

If I understand the Android Animator's API correctly, the linear interpolation that the puck is animated with will take the list of provided points and split the timeline evenly between those points, but since the distance between the points is not constant, using constant time with variable distance will result in the puck slowing down and speeding up when keypoints are available.

There are a couple of options we can explore:
- Ensure keypoints are universally distributed. This sounds rather challenging since keypoints need to land precisely on the apexes of maneuvers. cc @mskurydin for thoughts
- When target location with keypoints is provided, instead of scheduling one animation with a list of points, schedule X animations with a single point that have variable duration based on the distance to make sure that the puck's pixel velocity is constant.

I'd like to explore option 2, and maybe even implement it in the Maps SDK (as an optional approach) if it turns out satisfactory.

For example, notice how on straight the puck's velocity is rather constant but that dramatically changes when we're on curves and keypoints are showing up:

https://user-images.githubusercontent.com/16925074/111336349-72305d80-8675-11eb-909a-36e6196da1ac.mp4

Is this problem already resolved on the iOS side @mapbox/navigation-ios?

/cc @mapbox/navigation-android @mapbox/maps-android @OttyLab for visibility and other ideas

**Comment by LukasPaczos** [comment] 2021-03-16 15:41
cc @d-prukop

**Comment by 1ec5** [comment] 2021-03-16 16:20
> Is this problem already resolved on the iOS side

The iOS navigation SDK isn’t using keypoints with its puck implementation yet.

**Comment by zugaldia** [comment] 2021-03-17 18:02
@1ec5 could you cut a ticket for iOS if one isn't available yet?

**Comment by LukasPaczos** [comment] 2021-04-27 11:57
cc @mapbox/navnative for visibility and ideas or alternative solutions

**Comment by SiarheiFedartsou** [comment] 2021-04-27 12:24
@LukasPaczos 

> When target location with keypoints is provided, instead of scheduling one animation with a list of points, schedule X animations with a single point that have variable duration based on the distance to make sure that the puck's pixel velocity is constant.

NN provides timestamps for each of keypoints and it probably can be utilized here. AFAIR this timestamps are already based on distances between key points, so you don't have to calculate these distances on your own, but you can take those timestamps as basis for animation timings.

**Comment by jstratman** [comment] 2021-05-14 20:52
Is this potentially the same issue from Rivian? https://github.com/mapbox-collab/rivian-collab/issues/192#issuecomment-841463091  Supposedly it's mostly apparent z19 and up and they are only noticing now because they just unlocked the ability for users to zoom past 17.5 while tracking. 

Previous Rivian complaints of a jittery puck were addressed in Maps SDK here, but unsure if that relates at all vs the above issue: https://github.com/mapbox/mapbox-maps-android-internal/issues/274#issuecomment-804103027

**Comment by 1ec5** [comment] 2021-09-03 16:08
> could you cut a ticket for iOS if one isn't available yet?

mapbox/mapbox-navigation-ios#3324

**Comment by LukasPaczos** [comment] 2021-09-13 09:40
For anyone reading along - to work around the problem, disable keypoints location animation. For example, instead of:
```kotlin
val navigationLocationProvider: NavigationLocationProvider = ...
navigationLocationProvider.changePosition(
    enhancedLocation,
    keyPoints
)
```
do:
```kotlin
val navigationLocationProvider: NavigationLocationProvider = ...
navigationLocationProvider.changePosition(
    enhancedLocation,
    emptyList() // do not pass keypoints to work around animation problem
)
```

**Comment by tomaszrybakiewicz** [comment] 2022-06-17 01:57
Need to re-open this issue.

We performed more real-world tests and notice strange "jumpy" puck behaviour after merging ["Puck Velocity Fix PR"](https://github.com/mapbox/mapbox-navigation-android/pull/5925).

We've disabled ["the Fix here"](https://github.com/mapbox/mapbox-navigation-android/pull/5933) and we will re-enable it once we identify the root cause of the glitch.

_(thanks to @abhishek1508 for screen recording of the real-world test)_

https://user-images.githubusercontent.com/2678039/174207047-6719eeb9-5d77-422f-bcb3-529ae8bb6cfc.mp4

**Comment by tomaszrybakiewicz** [comment] 2022-06-21 14:11
The root cause of the glitch has been identified and [patched here](https://github.com/mapbox/mapbox-navigation-android/pull/5943).

**Closed** 2022-06-22 18:08 UTC
Labels: bug
