### ISSUE TITLE
Android: Navigation turn-by-turn UI Problem (I want to know if i missing something )

### ISSUE THREAD

**Issue by mohamed3la2** [mapbox/mapbox-navigation-android#960] opened 2018-05-21 20:24 UTC
I am doing a simple Navigation turn-by-turn UI between 2 points (i get them from Google Map) best route take 2 min (400 m).
I Follow This link https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/fragment/NavigationFragment.java    And read navigation ui documentation and use 
 **'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0'**  only , and i get weird output 
![test](https://user-images.githubusercontent.com/28600103/40328022-317233a6-5d45-11e8-9aaa-8f6968e0b6e5.PNG)
I hope i get help soon . Ty

**Comment by Guardiola31337** [comment] 2018-05-22 10:07
Hey @mohamed3la2 👋 thanks for reaching out and report your question.

How are you creating the `origin` and `destination` points? I guess that the problem is that `longitude` and `latitude` are messed up (upside down). `NavigationViewOptions` requests a `Point` which could be created using `Point.fromLngLat` which requests `longitude` and `latitude` (in that order) 👀 https://github.com/mapbox/mapbox-navigation-android/blob/5f66e491bf342e30f950b011e77111dfebd088fb/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/fragment/NavigationFragment.java#L94-L95

In any case, this issue tracker is only for bug reports with test cases and feature requests. In the future, please direct these kind of questions to https://stackoverflow.com/questions/tagged/mapbox. We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues. Thanks again!

**Comment by mohamed3la2** [comment] 2018-05-22 13:11
I told you that i follow that link https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/fragment/NavigationFragment.java
and create it like in the link. here is my origin and destination code :
**_import com.mapbox.geojson.Point;_**
   **private static final double ORIGIN_LONGITUDE = 31.254159;
    private static final double ORIGIN_LATITUDE = 32.317315;
    private static final double DESTINATION_LONGITUDE =31.247383;
    private static final double DESTINATION_LATITUDE = 32.321202;**

Then
    @Override
    public void onNavigationReady() {

        Point originPoint=Point.fromLngLat(ORIGIN_LONGITUDE,ORIGIN_LATITUDE) ;
        Point destinationPoint=Point.fromLngLat(DESTINATION_LONGITUDE,DESTINATION_LATITUDE);

        NavigationViewOptions options = NavigationViewOptions.builder()
                                         .origin(originPoint)
                                         .destination(destinationPoint)
                                         .shouldSimulateRoute(true)
                                         .navigationListener(this)
                                         .build();
                         navigationView.startNavigation(options);
    }
And i think that bug because it works with me but with 2 different points 
and i tired different **directionsProfile** Same issue.

**Comment by mohamed3la2** [comment] 2018-05-22 13:16
And here is Full code its look like i copy github code and paste it 

import android.app.Fragment;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import com.mapbox.services.android.navigation.ui.v5.NavigationView;
import com.mapbox.services.android.navigation.ui.v5.NavigationViewOptions;
import com.mapbox.services.android.navigation.ui.v5.OnNavigationReadyCallback;
import com.mapbox.services.android.navigation.ui.v5.listeners.NavigationListener;
import com.mapbox.geojson.Point;

public class My_Fragment extends Fragment implements NavigationListener,OnNavigationReadyCallback {

    private static final double ORIGIN_LONGITUDE = 31.254159;
    private static final double ORIGIN_LATITUDE = 32.317315;
    private static final double DESTINATION_LONGITUDE =31.247383;
    private static final double DESTINATION_LATITUDE = 32.321202;
    public NavigationView navigationView;

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater , @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.navigation_view_fragment_layout, container,false);
    }


    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        
        super.onViewCreated(view, savedInstanceState);
        navigationView = view.findViewById(R.id.navigationView);
        navigationView.onCreate(savedInstanceState);

        navigationView.initialize(this);
    }

    @Override
    public void onStart() {
        super.onStart();
        navigationView.onStart();
    }

    @Override
    public void onResume() {
        super.onResume();
        navigationView.onResume();
    }

    @Override
    public void onSaveInstanceState(@NonNull Bundle outState) {
        navigationView.onSaveInstanceState(outState);
        super.onSaveInstanceState(outState);
    }

    @Override
    public void onViewStateRestored(@Nullable Bundle savedInstanceState) {
        super.onViewStateRestored(savedInstanceState);
        if (savedInstanceState != null) {
            navigationView.onRestoreInstanceState(savedInstanceState);
        }
    }

    @Override
    public void onPause() {
        super.onPause();
        navigationView.onPause();
    }

    @Override
    public void onStop() {
        super.onStop();
        navigationView.onStop();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        navigationView.onLowMemory();
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        navigationView.onDestroy();
    }

    @Override
    public void onNavigationReady() {

        Point originPoint=Point.fromLngLat(ORIGIN_LONGITUDE,ORIGIN_LATITUDE) ;
        Point destinationPoint=Point.fromLngLat(DESTINATION_LONGITUDE,DESTINATION_LATITUDE);

        NavigationViewOptions options = NavigationViewOptions.builder()
                                         .origin(originPoint)
                                         .destination(destinationPoint)
                                         .shouldSimulateRoute(true)
                                         .navigationListener(this)
                
                                         .build();
                         navigationView.startNavigation(options);
    }

    @Override
    public void onCancelNavigation() {

        if (getActivity() != null) {
            getActivity().finish();
        }
    }

    @Override
    public void onNavigationFinished() {
        if (getActivity() != null) {
            getActivity().finish();
        }
    }

    @Override
    public void onNavigationRunning() {
        // no-op
    }
}

**Comment by Guardiola31337** [comment] 2018-05-22 16:50
Hey @mohamed3la2 👋 

The points you're using as `origin` and `destination` are in the sea and requesting directions with those points have no result.

`originPoint`

![origin](https://user-images.githubusercontent.com/1668582/40376894-d68cb8c0-5def-11e8-9245-c4728f04ae40.png)

`destinationPoint`

![destination](https://user-images.githubusercontent.com/1668582/40376910-debfa0d4-5def-11e8-80fc-019a43d10aea.png)

You can see here https://www.mapbox.com/api-playground/#/directions?_k=bfrg2s that the Directions API doesn't return a response when using those points (`31.254159,32.317315;31.247383,32.321202`).

BTW, thanks for bringing this to us we should not start the navigation session if no response is received.

**Comment by Guardiola31337** [comment] 2018-05-22 16:55
Closing here as 
> we should not start the navigation session if no response is received

was already reported in https://github.com/mapbox/mapbox-navigation-android/issues/774

Thanks again @mohamed3la2

**Closed by Guardiola31337** 2018-05-22 16:55 UTC

**Comment by Guardiola31337** [comment] 2018-05-23 08:29
> I thought all Longitude and Latitude is same with google maps. I get these points from google maps and they aren't in the sea ? .

Yeah that's the problem. Those that you see are latitude / longitude 👀

> I guess that the problem is that `longitude` and `latitude` are messed up (upside down).

If you flip them you get the proper route 👀 

![route](https://user-images.githubusercontent.com/1668582/40412597-134f6346-5e74-11e8-90ef-60b4c03b6fa4.png)

**Comment by mohamed3la2** [comment] 2018-05-23 18:08
@Guardiola31337 ha all clear now , before these points i tried another two messed up points and its work i think by luck :D ,
Thanks man its help me a lot keep it up :+1: ,And sorry again for wasting your time for this stupid error .

**Comment by Guardiola31337** [comment] 2018-05-24 08:12
@mohamed3la2 great to hear 🙂 Thanks for the update!

> Another think feel free if u don't want to answer it :D when i press X onNavigationFinished() is triggered then onCancelNavigation() .

That's the expected behavior, it's working as designed 👀 [`NavigationListener`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/listeners/NavigationListener.java)
