### ISSUE TITLE
When `Balanced` location accuracy is used with Google Location Engine, no raw locations are provided (just enhanced).

### ISSUE THREAD

**Issue by kavalerov** [mapbox/mapbox-navigation-android#4431] opened 2021-05-21 08:45 UTC
We are building an asset tracking SDK that uses Mapbox NavSDK as a source of location updates (https://github.com/ably/ably-asset-tracking-android). 

We rely on getting both "raw" and "enhanced" location updates from Mapbox within the SDK. 

We have noticed an unusual behaviour recently, that when `Balanced` accuracy is set, and GoogleLocationEngine is used, the raw locations are just not provided anymore (`onRawLocationChanged` is not called).

Is this something your team sees as well, and what is the intended workaround? 

Also, with "enhanced" location updates (from `onEnhancedLocationChanged`), is there a way to see how "stale" is the location, in terms of what is the "age" of the last raw location update that enahncement algorithms rely on? 

**Android API:**
API level 30
**Mapbox Navigation SDK version:**
implementation 'com.mapbox.navigation:core:2.0.0-beta.4'
implementation 'com.mapbox.mapboxsdk:mapbox-android-core:3.1.1'
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:5.7.0'

### Steps to trigger behavior

 1. Use the MapboxNavSDK using the android and sdk versions provided above
 2. Set up listeners for `onRawLocationChanged` and `onEnhancedLocationChanged`
 3. Run it on a device where GoogleLocationEngine is used

### Expected behavior
Both listeners should be triggered occasionally. 

### Actual behavior
Only the enhanced location update listener (`onEnhancedLocationChanged`) is triggered.

**Comment by Guardiola31337** [comment] 2021-05-21 11:15
@tarigo @mr1sunshine could you check this out when you have a chance? 🙏 

It seems related to [`GoogleLocationEngineImpl`](https://github.com/mapbox/mapbox-events-android/blob/main/liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngineImpl.java) implementation cc @nkukday @brunoabinader 

> Also, with "enhanced" location updates (from `onEnhancedLocationChanged`), is there a way to see how "stale" is the location, in terms of what is the "age" of the last raw location update that enahncement algorithms rely on? 

@mskurydin @SiarheiFedartsou could you advice here when you have a chance? 🙏

**Comment by mskurydin** [comment] 2021-05-21 14:58
@kavalerov we track the information about the age internally, however, it's not exposed in public APIs. Would you mind sharing how you could benefit from having it? Thanks!

**Comment by kavalerov** [comment] 2021-06-09 13:44
So in our product the following happens: 
- Locations are collected in the Publisher SDK. As map-matching is one of the important features of our product we mostly care about enhanced location. 
- then they are sent via Ably
- Finally the locations are provided to user on another device via the Subscriber SDK

In case of the situation described in the issue, when no raw locations are being provided, NavSDK still provides enhanced locations.  However, my understanding is that these enhanced locations will not be correct, as they still have to be calculated on some raw ones. 

When these wrong enhanced locations are sent over to another device, there is currently no way to tell how reliable these enhanced locations are. 

We can't predict all possible situations, so instead we would like to include the "age" of the predicted locations in the information that we send to subscribers, so that they could make a decision wether they can rely on these locations. 

@mskurydin do you think there is something else we could use for this purpose? 

cc: @andynicks @kacperkluka

**Comment by kavalerov** [comment] 2021-06-09 13:45
@Guardiola31337 / @tarigo / @mr1sunshine Have you had time by any chance to look at this as well? It would be good to know if this is going to be fixed soon :)

**Comment by kavalerov** [comment] 2021-07-05 08:38
Hi Mapbox team, is there any update on this by any chance?

**Comment by mskurydin** [comment] 2021-07-06 12:52
Right now we only have a `stale` indicator in route progress which tells if we can really trust the value.
If the route progress is computed based on the raw location older than 7 seconds, it's considered stale.
Unfortunately, this works only for active guidance (and not in the free drive).
We plan on adding more information (including the age) into the `MapMatcherResult`.

**Comment by KacperKluka** [comment] 2021-07-06 15:36
@mskurydin thanks for the response :bow: 

Are there any news in terms of missing raw locations for the `GoogleLocationEngineImpl` with `Balanced` accuracy? :wink:

**Comment by nagineni** [comment] 2021-08-03 10:10
@KacperKluka :wave: We are not able to reproduce the issue on Android 10 and 11 using our reference applications. We can see both raw and enhanced location updates when `Balanced` location accuracy option is set to the `GoogleLocationEngine`. Here are the location update logs:

```
2021-08-03 12:09:01.624 15527-15527/com.mapbox.navigation.examples D/Enhanced location:: Location[ReplayRoute 60,169665,24,810380 hAcc=3 et=+1d12h18m41s268ms vel=28.386427 bear=88.57904 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:02.315 15527-15527/com.mapbox.navigation.examples D/Raw location:: Location[ReplayRoute 60,169664,24,810288 hAcc=3 et=+1d12h18m40s866ms vel=26.772856 bear=88.57904 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:02.324 15527-15527/com.mapbox.navigation.examples D/Enhanced location:: Location[ReplayRoute 60,169670,24,810795 hAcc=3 et=+1d12h18m41s968ms vel=26.772856 bear=88.57904 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:02.918 15527-15527/com.mapbox.navigation.examples D/Raw location:: Location[ReplayRoute 60,169670,24,810799 hAcc=3 et=+1d12h18m41s469ms vel=29.772856 bear=89.22441 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:02.927 15527-15527/com.mapbox.navigation.examples D/Enhanced location:: Location[ReplayRoute 60,169678,24,811390 hAcc=3 et=+1d12h18m42s572ms vel=29.772856 bear=88.57904 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:03.620 15527-15527/com.mapbox.navigation.examples D/Raw location:: Location[ReplayRoute 60,169677,24,811339 hAcc=3 et=+1d12h18m42s171ms vel=30.0 bear=89.98573 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:03.633 15527-15527/com.mapbox.navigation.examples D/Enhanced location:: Location[ReplayRoute 60,169678,24,811935 hAcc=3 et=+1d12h18m43s280ms vel=30.0 bear=90.10414 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:04.321 15527-15527/com.mapbox.navigation.examples D/Raw location:: Location[ReplayRoute 60,169678,24,811881 hAcc=3 et=+1d12h18m42s872ms vel=30.0 bear=90.5561 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:04.331 15527-15527/com.mapbox.navigation.examples D/Enhanced location:: Location[ReplayRoute 60,169677,24,812477 hAcc=3 et=+1d12h18m43s975ms vel=30.0 bear=90.10414 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:04.922 15527-15527/com.mapbox.navigation.examples D/Raw location:: Location[ReplayRoute 60,169677,24,812423 hAcc=3 et=+1d12h18m43s473ms vel=30.0 bear=91.111244 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:04.927 15527-15527/com.mapbox.navigation.examples D/Enhanced location:: Location[ReplayRoute 60,169672,24,813019 hAcc=3 et=+1d12h18m44s576ms vel=30.0 bear=91.21443 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:05.624 15527-15527/com.mapbox.navigation.examples D/Raw location:: Location[ReplayRoute 60,169672,24,812965 hAcc=3 et=+1d12h18m44s175ms vel=30.0 bear=91.41873 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:05.629 15527-15527/com.mapbox.navigation.examples D/Enhanced location:: Location[ReplayRoute 60,169666,24,813561 hAcc=3 et=+1d12h18m45s278ms vel=30.0 bear=91.21443 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:06.326 15527-15527/com.mapbox.navigation.examples D/Raw location:: Location[ReplayRoute 60,169667,24,813507 hAcc=3 et=+1d12h18m44s877ms vel=30.0 bear=91.97613 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:06.335 15527-15527/com.mapbox.navigation.examples D/Enhanced location:: Location[ReplayRoute 60,169658,24,814103 hAcc=3 et=+1d12h18m45s981ms vel=30.0 bear=92.32942 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:06.928 15527-15527/com.mapbox.navigation.examples D/Raw location:: Location[ReplayRoute 60,169659,24,814049 hAcc=3 et=+1d12h18m45s479ms vel=30.0 bear=92.3296 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:06.938 15527-15527/com.mapbox.navigation.examples D/Enhanced location:: Location[ReplayRoute 60,169647,24,814645 hAcc=3 et=+1d12h18m46s582ms vel=30.0 bear=92.32942 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:07.632 15527-15527/com.mapbox.navigation.examples D/Raw location:: Location[ReplayRoute 60,169648,24,814591 hAcc=3 et=+1d12h18m46s182ms vel=30.0 bear=92.91792 vAcc=??? sAcc=??? bAcc=???]
2021-08-03 12:09:07.658 15527-15527/com.mapbox.navigation.examples D/Enhanced location:: Location[ReplayRoute 60,169636,24,815187 hAcc=3 et=+1d12h18m47s308ms vel=30.0 bear=93.75161 vAcc=??? sAcc=??? bAcc=???]
...
```

If you are able to reproduce this issue always, could you please add some more information around your test setup and also used device?

**Comment by KacperKluka** [comment] 2021-08-05 15:43
@nagineni thanks for the response :bow: 

I can reproduce it each time on an Android emulator in the Android Studio.
The emulator is Pixel 2 API 24 (Android 7.0) with Google Play Store (and services). It's important to use a device with Google as the issue only occurs for the `GoogleLocationEngine`.
I'm using the Mapbox library in version 1.6.1
I'm just starting the trip session, then I receive a single raw location and an infinite stream of the same enhanced locations. If I change the engine accuracy to `HIGH` then it works. When I change it back to `BALANCED` it stops working.

Please let me know if you'll need some more information. Looking forward to your response :wink:

**Comment by KacperKluka** [comment] 2021-08-17 10:39
I've checked and the issue seems to be present only on some emulators but I wasn't able to reproduce it on a real device. My guess is that maybe those emulators have outdated Play Services or some other Google libraries that cause this trouble. 

Given that it's only an emulator problem I think that we can probably close this issue :wink: Thanks for your time and help :bow:

**Comment by Guardiola31337** [comment] 2021-08-17 13:35
Thanks @KacperKluka for your thorough testing.

Closing as solved.

**Closed by Guardiola31337** 2021-08-17 13:35 UTC
Labels: support
