### ISSUE TITLE
Map Matching issue with underpass

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#1204] opened 2018-08-10 09:35 UTC
Sorry, wasn't quite sure where to post this - happy to be pointed in the right direction.

We have found a couple of places where map matching/navigation doesn't recognise tunnels and overpasses. We just wanted to check if this a generic problem or if these are just specific items missing (and if so, what's the easiest way to report these issues?)

Two such queries are:

https://api.mapbox.com/matching/v5/mapbox/walking/-0.158398,51.555640;-0.158556,51.556398?access_token=[token]&geometries=polyline6&overview=full&steps=true&voice_instructions=true&banner_instructions=true&waypoints=0;1&timestamps=1514764800000;1514764810000
which should just take you straight over the overpass over the railway

and

https://api.mapbox.com/matching/v5/mapbox/walking/-0.084486,51.492721;-0.082919,51.492861?access_token=[token]&geometries=polyline6&overview=full&steps=true&voice_instructions=true&banner_instructions=true&waypoints=0;1&timestamps=1514764800000;1514764810000
which should take you through the underpass under the main road

In both case, the directions returned take you a long way round.

**Comment by Guardiola31337** [comment] 2018-08-13 10:59
Hey @richjhart 👋 thanks for reaching out and report your issue.

You're right here. It's a data issue though.

Looking at the data in OSM, this way appears to only be tagged as a `cycleway` https://www.openstreetmap.org/way/606885681 (also this whole bit https://www.openstreetmap.org/way/58779733) and we don't include ways that are strictly only tagged `cycleway` in our walk profile.

BTW, if you know for sure that that stretch of cycleway is used for walking too, I encourage you to map it or add an OSM note to get the confirmation from community. Ultimately, that's how 🗺 are built 😉

Thanks again!

Closing as non actionable here.

cc @karenzshea @srividyacb

**Closed by Guardiola31337** 2018-08-13 10:59 UTC

**Comment by richjhart** [comment] 2019-01-10 12:04
@Guardiola31337 I am looking to start editing these in OSM, but I just wanted to check something:

If the way is tagged as a "Cycle Path" (highway=cycleway), but is also marked as allowing foot traffic (foot="designated" or "yes"), will that allow it to be included in the walking profile. Or does it need to be highway=footway (with bicycle="yes" or "designated")?

Is there documentation anywhere describing the rules for each profile?

**Comment by 1ec5** [comment] 2019-01-10 20:10
> If the way is tagged as a "Cycle Path" (highway=cycleway), but is also marked as allowing foot traffic (foot="designated" or "yes"), will that allow it to be included in the walking profile. Or does it need to be highway=footway (with bicycle="yes" or "designated")?

It can be a `highway=cycleway`, but it also needs to be tagged with `foot` set to `yes`, `designated`, `permissive`, or `destination`, as appropriate. If a cycleway is missing a `foot` tag, OSRM’s walking profile assumes that the cycleway disallows pedestrians.

> Is there documentation anywhere describing the rules for each profile?

The specific profiles used by the Mapbox Directions API are technically private, but the walking profile especially is just a straight copy of [OSRM’s default walking profile](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/foot.lua). In this case, I think the distinction is that the cycling profile has [a sophisticated cycleway handler](https://github.com/Project-OSRM/osrm-backend/blob/714719c3776c5985a8881cba32f48f8a4de5a70a/profiles/bicycle.lua#L390-L442) that isn’t present in the walking profile, so the only thing that can make a cycleway visible to the walking profile is the `foot` access tag.

Unfortunately, I’m unaware of any prose documentation for the profiles, but there are lots of [very readable test cases](https://github.com/Project-OSRM/osrm-backend/blob/82b5648c97edf1d2edec7aecebc35aa8a8033c82/features/foot/access.feature#L107-L110) that give a sense of the intended behavior.
