### ISSUE TITLE
Camera rotates more than would be expected

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2676] opened 2020-03-30 19:57 UTC
When testing the `examples` test app noticed that the camera sometimes does rotate too much unnecessarily like doing a counter-clockwise rotation 👀 

![unnecessary_camera_rotation](https://user-images.githubusercontent.com/1668582/77955603-76197300-729e-11ea-9beb-04c75ffe8ae7.gif)

Noticed in [`GuidanceViewActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/examples/src/main/java/com/mapbox/navigation/examples/core/GuidanceViewActivity.kt) but I remember seeing this behavior in other examples too.

We've recently added changes to the `NavigationCamera` / `DynamicCamera` to the `1.0` UI SDK implementation so wondering if there's any regression from there because we don't experience such a behavior in the legacy.

cc @abhishek1508 @cafesilencio

**Comment by cafesilencio** [comment] 2020-03-30 20:51
It probably has to do with the initial values used for the camera mode and
render mode in the activity. There were no changes to how DynamicCamera
makes its calculations.

**Comment by Guardiola31337** [comment] 2020-03-30 22:07
🆗 Thanks for looking @cafesilencio 

Wanted to confirm that wasn't a regression from latest changes added. Feel free to fix the example and close here 👍

**Comment by Guardiola31337** [comment] 2020-04-02 14:01
Experienced the same weird camera rotation when running [`NavigationLauncherActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java) example from the test `app` (legacy) 👀 

![camera_unnecessary_rotation](https://user-images.githubusercontent.com/1668582/78258215-e3105100-74c8-11ea-84a8-7fa1a3c66ca1.gif)

cc @LukasPaczos

**Comment by LukasPaczos** [comment] 2020-04-02 15:39
@cafesilencio @Guardiola31337 this is probably due to how we calculate the initial rotation angle in 
https://github.com/mapbox/mapbox-gl-native-android/blob/620bda356cf082bc56f8bf82b071dd79ee5ace39/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java#L95-L108

Just a guess at this point though.

**Comment by Guardiola31337** [comment] 2020-04-02 16:52
Good point @LukasPaczos thanks for chiming in!

So it seems a recent downstream change 👍 - as @cafesilencio mentioned we haven't changed the logic in the Navigation SDK.

**Comment by LukasPaczos** [comment] 2020-04-02 17:01
Are you sure this is a completely new issue? There has only been one change to this codebase in the last couple of months and I can't spot the culprit - https://github.com/mapbox/mapbox-gl-native-android/pull/166/files.

**Comment by LukasPaczos** [comment] 2020-04-02 17:02
Maybe the normalization that happens in a different place now, like
https://github.com/mapbox/mapbox-gl-native-android/pull/166/files#diff-a68cf278b310c868830d0f2b6ff7d90bR250.

If you can reproduce - could you step through the code and see whether the values look correct?

**Comment by Guardiola31337** [comment] 2020-04-02 17:27
> If you can reproduce - could you step through the code and see whether the values look correct?

Great idea! Could you take a stab at this @cafesilencio? Pretty simple to reproduce as described above https://github.com/mapbox/mapbox-navigation-android/issues/2676#issuecomment-607865379 Let us know if you need more context or questions.

**Comment by cafesilencio** [comment] 2020-04-17 17:48
this issue was resolved with PR #2781

**Closed by cafesilencio** 2020-04-17 17:48 UTC
Labels: UI SDK v1+, topic: camera
