### ISSUE TITLE
NavigationLauncher::startNavigation() not working. 

### ISSUE THREAD

**Issue by aecarlosae** [mapbox/mapbox-navigation-android#1529] opened 2018-11-13 18:08 UTC
**Android API:** 28.0.0
**Mapbox Navigation SDK version:** 0.23.0

### Steps to trigger behavior

 1. Detected current location
 2. Add marker and generate path
 3. Click a button to start navigation

### Expected behavior
It should start Navigation with:
`NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                        .directionsRoute(currentRoute)
                        .shouldSimulateRoute(true)
                        .build();
                // Call this method with Context from within an Activity
                NavigationLauncher.startNavigation(HomeActivity.this, options);`

### Actual behavior

Crash immediately after `NavigationLauncher.startNavigation(HomeActivity.this, options);`

### Activity

package com.exampledom.examplemapboxapp;

import android.location.Location;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.design.widget.FloatingActionButton;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Toast;

// classes needed to initialize map
import com.mapbox.android.core.location.LocationEngine;
import com.mapbox.android.core.location.LocationEnginePriority;
import com.mapbox.android.core.location.LocationEngineProvider;
import com.mapbox.mapboxsdk.Mapbox;
import com.mapbox.mapboxsdk.camera.CameraUpdateFactory;
import com.mapbox.mapboxsdk.maps.MapView;
// classes needed to add the location component
import com.mapbox.geojson.Point;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;
import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.location.LocationComponent;
import com.mapbox.mapboxsdk.location.modes.CameraMode;
import com.mapbox.services.android.navigation.ui.v5.NavigationLauncherOptions;
import com.mapbox.android.core.permissions.PermissionsListener;
import com.mapbox.android.core.permissions.PermissionsManager;
// classes needed to add a marker
import com.mapbox.mapboxsdk.annotations.Marker;
import com.mapbox.mapboxsdk.annotations.MarkerOptions;
// classes to calculate a route
import com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute;
import com.mapbox.services.android.navigation.v5.navigation.NavigationRoute;
import com.mapbox.api.directions.v5.models.DirectionsResponse;
import com.mapbox.api.directions.v5.models.DirectionsRoute;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import timber.log.Timber;

// classes needed to launch navigation UI
import com.mapbox.services.android.navigation.ui.v5.NavigationLauncher;

import java.util.List;

public class DefaultHomeActivity extends AppCompatActivity implements OnMapReadyCallback, PermissionsListener, MapboxMap.OnMapClickListener {

    private MapView mapView;
    // variables for adding location layer
    private MapboxMap mapboxMap;
    private PermissionsManager permissionsManager;
    private Location originLocation;// variables for adding a marker
    private Marker destinationMarker;
    private LatLng originCoord;
    private LatLng destinationCoord;
    // variables for calculating and drawing a route
    private Point originPosition;
    private Point destinationPosition;
    private DirectionsRoute currentRoute;
    private static final String TAG = "HomesActivity";
    private NavigationMapRoute navigationMapRoute;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Mapbox.getInstance(this, getString(R.string.mapbox_access_token));
        setContentView(R.layout.activity_default_home);

        mapView = findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(this);

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        FloatingActionButton fab = findViewById(R.id.star_navigate);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                boolean simulateRoute = true;
                NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                        .directionsRoute(currentRoute)
                        .shouldSimulateRoute(simulateRoute)
                        .build();
                // Call this method with Context from within an Activity
                NavigationLauncher.startNavigation(DefaultHomeActivity.this, options);
            }
        });
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_home, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so longz
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    @Override
    public void onMapReady(MapboxMap mapboxMap) {
        this.mapboxMap = mapboxMap;
        enableLocationComponent();
        originCoord = new LatLng(originLocation.getLatitude(), originLocation.getLongitude());
        mapboxMap.addOnMapClickListener(this);
    }

    private void getRoute(Point origin, Point destination) {
        NavigationRoute.builder(this)
                .accessToken(Mapbox.getAccessToken())
                .origin(origin)
                .destination(destination)
                .build()
                .getRoute(new Callback<DirectionsResponse>() {
                    @Override
                    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                        // You can get the generic HTTP info about the response
                        Timber.tag(TAG).d("Response code: " + response.code());
                        if (response.body() == null) {
                            Timber.tag(TAG).e("No routes found, make sure you set the right user and access token.");
                            return;
                        } else if (response.body().routes().size() < 1) {
                            Timber.tag(TAG).e("No routes found");
                            return;
                        }

                        currentRoute = response.body().routes().get(0);

                        // Draw the route on the map
                        if (navigationMapRoute != null) {
                            navigationMapRoute.removeRoute();
                        } else {
                            navigationMapRoute = new NavigationMapRoute(null, mapView, mapboxMap, R.style.NavigationMapRoute);
                        }
                        navigationMapRoute.addRoute(currentRoute);
                    }

                    @Override
                    public void onFailure(Call<DirectionsResponse> call, Throwable throwable) {
                        Timber.tag(TAG).e("Error: " + throwable.getMessage());
                    }
                });
    }

    @SuppressWarnings( {"MissingPermission"})
    private void enableLocationComponent() {
        // Check if permissions are enabled and if not request
        if (PermissionsManager.areLocationPermissionsGranted(this)) {
            // Activate the MapboxMap LocationComponent to show user location
            // Adding in LocationComponentOptions is also an optional parameter
            LocationComponent locationComponent = mapboxMap.getLocationComponent();
            locationComponent.activateLocationComponent(this);
            locationComponent.setLocationComponentEnabled(true);
            // Set the component's camera mode
            locationComponent.setCameraMode(CameraMode.TRACKING);
            originLocation = locationComponent.getLastKnownLocation();
            if(originLocation!=null) {
                mapboxMap.animateCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(originLocation.getLatitude(), originLocation.getLongitude()), 13.0));
            }else{
                LocationEngine locationEngine = new LocationEngineProvider(this).obtainBestLocationEngineAvailable();
                locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
                locationEngine.activate();
                originLocation = locationEngine.getLastLocation();
                mapboxMap.animateCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(originLocation.getLatitude(), originLocation.getLongitude()), 13.0));
            }

        } else {
            permissionsManager = new PermissionsManager(this);
            permissionsManager.requestLocationPermissions(this);
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        permissionsManager.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    public void onExplanationNeeded(List<String> permissionsToExplain) {
        Toast.makeText(this, "onExplanationNeeded", Toast.LENGTH_LONG).show();
    }

    @Override
    public void onPermissionResult(boolean granted) {
        if (granted) {
            enableLocationComponent();
        } else {
            Toast.makeText(this, "onPermissionResult", Toast.LENGTH_LONG).show();
            finish();
        }
    }

    @Override
    public void onMapClick(@NonNull LatLng point) {
        if (destinationMarker != null) {
            mapboxMap.removeMarker(destinationMarker);
        }
        destinationCoord = point;
        destinationMarker = mapboxMap.addMarker(new MarkerOptions()
                .position(destinationCoord)
        );

        destinationPosition = Point.fromLngLat(destinationCoord.getLongitude(), destinationCoord.getLatitude());
        originPosition = Point.fromLngLat(originCoord.getLongitude(), originCoord.getLatitude());
        getRoute(originPosition, destinationPosition);
    }

    @Override
    public void onStart() {
        super.onStart();
        mapView.onStart();
    }

    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    public void onStop() {
        super.onStop();
        mapView.onStop();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
    }
}

### Lotcat

11-13 13:31:23.899 14463-14463/com.exampledom.examplemapboxapp W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
11-13 13:31:24.106 14463-14463/com.exampledom.examplemapboxapp I/art: Thread[1,tid=14463,Native,Thread*=0xb4034500,peer=0x743e4258,"main"] recursive attempt to load library "/data/app/com.exampledom.examplemapboxapp-1/lib/x86/libmapbox-gl.so"
11-13 13:31:24.185 14463-14463/com.exampledom.examplemapboxapp I/art: Thread[1,tid=14463,Native,Thread*=0xb4034500,peer=0x743e4258,"main"] recursive attempt to load library "/data/app/com.exampledom.examplemapboxapp-1/lib/x86/libmapbox-gl.so"
11-13 13:31:24.192 14463-14463/com.exampledom.examplemapboxapp I/art: Thread[1,tid=14463,Native,Thread*=0xb4034500,peer=0x743e4258,"main"] recursive attempt to load library "/data/app/com.exampledom.examplemapboxapp-1/lib/x86/libmapbox-gl.so"
11-13 13:31:24.337 14463-14463/com.exampledom.examplemapboxapp I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
    Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
11-13 13:31:24.480 14463-14473/com.exampledom.examplemapboxapp I/art: Background partial concurrent mark sweep GC freed 1122(164KB) AllocSpace objects, 0(0B) LOS objects, 41% free, 1436KB/2MB, paused 59.885ms total 199.966ms
11-13 13:31:24.798 14463-14595/com.exampledom.examplemapboxapp D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
11-13 13:31:24.840 14463-14463/com.exampledom.examplemapboxapp V/Mbgl-ConnectivityReceiver: Connected: true
11-13 13:31:24.886 14463-14595/com.exampledom.examplemapboxapp I/OpenGLRenderer: Initialized EGL, version 1.4
11-13 13:31:24.934 14463-14595/com.exampledom.examplemapboxapp D/EGL_emulation: eglCreateContext: 0xaaecf760: maj 2 min 0 rcv 2
11-13 13:31:24.985 14463-14595/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0xaaecf760: ver 2 0 (tinfo 0xadd456e0)
11-13 13:31:25.036 14463-14595/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0xaaecf760: ver 2 0 (tinfo 0xadd456e0)
11-13 13:31:25.076 14463-14590/com.exampledom.examplemapboxapp I/Mbgl-EGLConfigChooser: In emulator: true
11-13 13:31:25.158 14463-14590/com.exampledom.examplemapboxapp D/EGL_emulation: eglCreateContext: 0xaefe48a0: maj 2 min 0 rcv 2
11-13 13:31:25.301 14463-14590/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0xaefe48a0: ver 2 0 (tinfo 0xaeffe6e0)
11-13 13:31:25.348 14463-14590/com.exampledom.examplemapboxapp I/Mbgl: {GLThread 565}[General]: GPU Identifier: Android Emulator OpenGL ES Translator (Google SwiftShader)
11-13 13:31:26.514 14463-14473/com.exampledom.examplemapboxapp I/art: Background sticky concurrent mark sweep GC freed 7414(317KB) AllocSpace objects, 0(0B) LOS objects, 17% free, 2030KB/2MB, paused 6.038ms total 68.074ms
11-13 13:31:28.633 14463-14463/com.exampledom.examplemapboxapp I/Choreographer: Skipped 207 frames!  The application may be doing too much work on its main thread.
11-13 13:31:28.943 14463-14473/com.exampledom.examplemapboxapp I/art: Background partial concurrent mark sweep GC freed 761(69KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 2MB/4MB, paused 5.487ms total 22.472ms
11-13 13:31:29.141 14463-14473/com.exampledom.examplemapboxapp I/art: Background partial concurrent mark sweep GC freed 795(76KB) AllocSpace objects, 3(60KB) LOS objects, 40% free, 5MB/9MB, paused 8.340ms total 35.336ms
11-13 13:31:43.997 14463-14595/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0xaaecf760: ver 2 0 (tinfo 0xadd456e0)
11-13 13:31:44.004 14463-14595/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0xaaecf760: ver 2 0 (tinfo 0xadd456e0)
11-13 13:31:44.046 14463-14609/com.exampledom.examplemapboxapp I/Mbgl-EGLConfigChooser: In emulator: true
11-13 13:31:44.067 14463-14609/com.exampledom.examplemapboxapp D/EGL_emulation: eglCreateContext: 0x9e468420: maj 2 min 0 rcv 2
11-13 13:31:44.086 14463-14609/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0x9e468420: ver 2 0 (tinfo 0x9e362190)
11-13 13:31:44.384 14463-14595/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0xaaecf760: ver 2 0 (tinfo 0xadd456e0)
11-13 13:31:44.979 14463-14595/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0xaaecf760: ver 2 0 (tinfo 0xadd456e0)
11-13 13:31:45.075 14463-14463/com.exampledom.examplemapboxapp I/Choreographer: Skipped 45 frames!  The application may be doing too much work on its main thread.
11-13 13:31:45.097 14463-14595/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0xaaecf760: ver 2 0 (tinfo 0xadd456e0)
11-13 13:31:45.143 14463-14595/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0xaaecf760: ver 2 0 (tinfo 0xadd456e0)
11-13 13:31:45.356 14463-14473/com.exampledom.examplemapboxapp I/art: Background sticky concurrent mark sweep GC freed 33394(1640KB) AllocSpace objects, 2(40KB) LOS objects, 14% free, 8MB/9MB, paused 7.011ms total 83.348ms
11-13 13:31:45.398 14463-14463/com.exampledom.examplemapboxapp I/TextToSpeech: Sucessfully bound to com.svox.pico
11-13 13:31:45.595 14463-14463/com.exampledom.examplemapboxapp I/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
11-13 13:31:45.635 14463-14590/com.exampledom.examplemapboxapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0xab649a00
11-13 13:31:45.636 14463-14595/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0xaaecf760: ver 2 0 (tinfo 0xadd456e0)
11-13 13:31:45.638 14463-14595/com.exampledom.examplemapboxapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb403d480
11-13 13:31:45.663 14463-14463/com.exampledom.examplemapboxapp I/TextToSpeech: Connected to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
11-13 13:31:45.671 14463-14595/com.exampledom.examplemapboxapp D/EGL_emulation: eglMakeCurrent: 0xaaecf760: ver 2 0 (tinfo 0xadd456e0)
11-13 13:31:45.692 14463-14622/com.exampledom.examplemapboxapp I/TextToSpeech: Set up connection to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
11-13 13:31:45.695 14463-14463/com.exampledom.examplemapboxapp D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
11-13 13:31:45.695 14463-14463/com.exampledom.examplemapboxapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.exampledom.examplemapboxapp, PID: 14463
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setPackage(java.lang.String)' on a null object reference
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.createPendingOpenIntent(MapboxNavigationNotification.java:147)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.initialize(MapboxNavigationNotification.java:93)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.<init>(MapboxNavigationNotification.java:63)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.buildNotificationFrom(NavigationNotificationProvider.java:40)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.<init>(NavigationNotificationProvider.java:14)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initializeNotificationProvider(NavigationService.java:107)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initialize(NavigationService.java:93)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.startNavigation(NavigationService.java:65)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.onServiceConnected(MapboxNavigation.java:724)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-13 13:31:47.345 14463-14618/com.exampledom.examplemapboxapp D/Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified
11-13 13:31:49.737 14463-14619/com.exampledom.examplemapboxapp D/Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified
11-13 13:31:49.762 14463-14616/com.exampledom.examplemapboxapp V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
11-13 13:32:50.426 14463-14643/com.exampledom.examplemapboxapp V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).

**Comment by danesfeder** [comment] 2018-11-14 14:34
Hey @aecarlosae thanks for brining this to us.

It looks like this is an NPE occurring during the initialization of `MapboxNavigationNotification`:

```
1-13 13:31:45.695 14463-14463/com.exampledom.examplemapboxapp E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.exampledom.examplemapboxapp, PID: 14463
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setPackage(java.lang.String)' on a null object reference
at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.createPendingOpenIntent(MapboxNavigationNotification.java:147)
at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.initialize(MapboxNavigationNotification.java:93)
at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.(MapboxNavigationNotification.java:63)
at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.buildNotificationFrom(NavigationNotificationProvider.java:40)
at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.(NavigationNotificationProvider.java:14)
at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initializeNotificationProvider(NavigationService.java:107)
at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initialize(NavigationService.java:93)
at com.mapbox.services.android.navigation.v5.navigation.NavigationService.startNavigation(NavigationService.java:65)
at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.onServiceConnected(MapboxNavigation.java:724)
```

We will work on a fix to close this.  Thanks for your patience here.

**Comment by aecarlosae** [comment] 2018-11-14 15:51
Ok, I'll be wait for it. I'm creating tutorials about how to use mapbox. Its pros and cons.

**Closed** 2018-11-20 17:51 UTC

**Comment by jhoncho** [comment] 2019-07-24 05:24
**Pasos para desencadenar el comportamiento**
Ubicación actual detectada
Añadir marcador y generar camino.
Haga clic en un botón para iniciar la navegación
Comportamiento esperado
Se debe iniciar la navegación con:
NavigationLauncherOptions options = NavigationLauncherOptions.builder() .directionsRoute(currentRoute) .shouldSimulateRoute(true) .build(); // Call this method with Context from within an Activity NavigationLauncher.startNavigation(HomeActivity.this, options);

Comportamiento real
Crash inmediatamente después NavigationLauncher.startNavigation(HomeActivity.this, options);
2019-07-24 01:12:50.826 30674-30688/com.bayoex.mapbox E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
2019-07-24 01:12:51.900 30674-30716/com.bayoex.mapbox E/GED: Failed to get GED Log Buf, err(0)
2019-07-24 01:12:51.909 30674-30716/com.bayoex.mapbox E/iGraphics: failed to load file<error id: 3>: /product/etc/xml/igraphics_config_cust.xml
2019-07-24 01:12:51.973 30674-30706/com.bayoex.mapbox E/GED: Failed to get GED Log Buf, err(0)
2019-07-24 01:12:52.084 30674-30706/com.bayoex.mapbox E/GED: Failed to get GED Log Buf, err(0)
2019-07-24 01:13:03.709 30674-30674/com.bayoex.mapbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bayoex.mapbox, PID: 30674
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
        at android.view.View.performClick(View.java:6648)
        at android.view.View.performClickInternal(View.java:6620)
        at android.view.View.access$3100(View.java:787)
        at android.view.View$PerformClick.run(View.java:26167)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:6648) 
        at android.view.View.performClickInternal(View.java:6620) 
        at android.view.View.access$3100(View.java:787) 
        at android.view.View$PerformClick.run(View.java:26167) 
        at android.os.Handler.handleCallback(Handler.java:891) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
     Caused by: java.lang.NullPointerException: Null directionsRoute
        at com.mapbox.services.android.navigation.ui.v5.AutoValue_NavigationLauncherOptions$Builder.directionsRoute(AutoValue_NavigationLauncherOptions.java:168)
        at com.bayoex.mapbox.MainActivity.startNavigationBtnClick(MainActivity.java:72)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:6648) 
        at android.view.View.performClickInternal(View.java:6620) 
        at android.view.View.access$3100(View.java:787) 
        at android.view.View$PerformClick.run(View.java:26167) 
        at android.os.Handler.handleCallback(Handler.java:891) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by jhoncho** [comment] 2019-07-24 05:25
> Ok, voy a estar esperando por ello. Estoy creando tutoriales sobre cómo usar mapbox. Sus pros y sus contras.

Pudiste solucionar el problema?
