### ISSUE TITLE
Dual-use lane icons are highlighted incorrectly

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-android#3934] opened 2021-02-08 19:51 UTC
In the lane view that appears below the turn banner, the icon for a dual use lane – a lane that can be used for multiple maneuvers – is highlighted incorrectly.

## Problem

If the user is supposed to turn left at an intersection and one of the lanes can be used for going straight or turning right, the lane icon is highlighted as if the user is supposed to turn right from that lane. It should not be highlighted at all.

## Diagnosis

`TurnLaneViewData.buildDrawData()` takes the lane indications for a given lane along with the overall maneuver that the lane may or may not be used for. In this case, `laneIndications` would be `STRAIGHT` and `RIGHT`, while `maneuverModifier` would be `LEFT`. However, the logic in `setDrawMethodWithModifier()` assumes the `maneuverModifier` has already been flipped just like the icon will be flipped, which is not the case. So `drawMethod` will be `DRAW_LANE_RIGHT_ONLY`, which looks like a straight-right icon. (`shouldFlip` will be `false` because the lane lacks a `LEFT` indication.)

https://github.com/mapbox/mapbox-navigation-android/blob/c5dc6c4238f5fd1e1bafd8e219dede40ab04c5d5/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/instruction/turnlane/TurnLaneViewData.java#L66-L72 https://github.com/mapbox/mapbox-navigation-android/blob/c5dc6c4238f5fd1e1bafd8e219dede40ab04c5d5/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/instruction/turnlane/TurnLaneViewData.java#L75-L83

By sheer coincidence, this is the same symptom seen in mapbox/mapbox-navigation-ios#2796. However, on iOS, the drawing logic was working correctly in this case, but the maneuver modifier was no longer being passed in as context, leaving a fallback pointing to the right.

## Next steps

`setDrawMethodWithModifier()` needs to consider whether the `maneuverModifier` matches one of the `laneIndications`. Conceptually, we should only highlight a lane use going in the same direction as the overall maneuver.

/cc @mapbox/navigation-android @avi-c

**Comment by abhishek1508** [comment] 2021-02-09 03:21
As you can see in v2.0 as well, we are supposed to show `SLIGHT RIGHT` instead of `STRAIGHT`, but we show the reverse. 

<img width="311" alt="Screen Shot 2021-02-08 at 6 45 51 PM" src="https://user-images.githubusercontent.com/9770186/107311030-7cda5000-6a42-11eb-8ccb-98780d86efda.png">

I am using this URL > (https://api.mapbox.com/directions/v5/mapbox/driving/-121.971323,37.502502;-121.935586,37.491613?access_token=pk.ey&alternatives=true&geometries=polyline6&overview=full&steps=true&continue_straight=false&annotations=congestion%2Cdistance&language=en&roundabout_exits=false&voice_instructions=true&banner_instructions=true&voice_units=imperial&enable_refresh=false) to fetch a route. [Access Token hidden]. 
Looking at the `sub` in `BannerInstruction`, you can see the 3rd `component` with directions `straight` and `slight right` and the lane being active, but the `modifier` under `primary` is `right`. When the above mentioned logic is executed, the maneuver modifier doesn't match and hence we get the result as we see in the screenshot above.
```
"bannerInstructions": [
    {
        "sub": {
            "components": [
                {
                    "active": false,
                    "directions": [
                        "straight"
                    ],
                    "type": "lane",
                    "text": ""
                },
                {
                    "active": false,
                    "directions": [
                        "straight"
                    ],
                    "type": "lane",
                    "text": ""
                },
                {
                    "active_direction": "slight right",
                    "active": true,
                    "directions": [
                        "straight",
                        "slight right"
                    ],
                    "type": "lane",
                    "text": ""
                }
            ],
            "text": ""
        },
        "primary": {
            "components": [
                {
                    "type": "exit",
                    "text": "Exit"
                },
                {
                    "type": "exit-number",
                    "text": "1"
                },
                {
                    "type": "text",
                    "text": "Kato Road"
                }
            ],
            "type": "off ramp",
            "modifier": "right",
            "text": "Exit 1 Kato Road"
        },
        "distanceAlongGeometry": 315
    }
]
```

To fix this issue is very simple in a sense that we shouldn't tap into `primary.modifier` because that can be incorrect. Looking at the json response you will see `active_direction` in 3rd `sub.component`. Also, `active_direction` is only available in the component that is `active`. However, as simple as the solution is, the problem is that this is only available to customers who have access to Valhalla based access tokens. We would have to find out from directions, when is it going to be available to all the customers, but until then we can probably fix it for Valhalla based customers, but this feature itself in SDK will not be completely bug free.

cc @1ec5 @avi-c @lxbarth

**Comment by 1ec5** [comment] 2021-02-10 06:55
> To fix this issue is very simple in a sense that we shouldn't tap into `primary.modifier` because that can be incorrect. Looking at the json response you will see `active_direction` in 3rd `sub.component`. Also, `active_direction` is only available in the component that is `active`. However, as simple as the solution is, the problem is that this is only available to customers who have access to Valhalla based access tokens. We would have to find out from directions, when is it going to be available to all the customers, but until then we can probably fix it for Valhalla based customers, but this feature itself in SDK will not be completely bug free.

Please see #3935, which tracks adopting `active_direction` when available.

This issue is simpler and smaller in scope, so I hope we can keep the two tasks separate. Modifying `setDrawMethodWithModifier()` to check whether `maneuverModifier` is contained in `laneIndications` won’t fix the particular example you point out above, but it will fix other cases that are more straightforward, such as the second screenshot in https://github.com/mapbox/mapbox-navigation-ios/issues/2796#issuecomment-772017797 and also the following ways:

https://www.openstreetmap.org/way/419427390
https://www.openstreetmap.org/way/419097183

mapbox/mapbox-navigation-ios#2796 has just been fixed in time for iOS navigation SDK v1.3.0, so it would be good to get parity with iOS in the short term, even if the more robust fix will take longer.

**Comment by 1ec5** [comment] 2021-02-10 20:04
Here’s what we need to draw:

Lane | User turns left | User goes straight | User turns right
----|----|----|----
[<img src="https://upload.wikimedia.org/wikipedia/commons/6/62/MUTCD_R3-6L.svg" height="32" alt="straight and left" align="top">](https://commons.wikimedia.org/wiki/File:MUTCD_R3-6L.svg) | `DRAW_LANE_RIGHT_ONLY` (flipped) | `DRAW_LANE_STRAIGHT_ONLY` | _Unhighlighted straight-turn lane_ (flipped)
[<img src="https://upload.wikimedia.org/wikipedia/commons/5/5d/MUTCD_R3-6R.svg" height="32" alt="straight and right" align="top">](https://commons.wikimedia.org/wiki/File:MUTCD_R3-6R.svg) | _Unhighlighted straight-turn lane_ | `DRAW_LANE_STRAIGHT_ONLY` | `DRAW_LANE_RIGHT_ONLY`

Here’s some pseduocode to explain how the v1._x_ codebase decides what to draw:

* For a [<img src="https://upload.wikimedia.org/wikipedia/commons/5/5d/MUTCD_R3-6R.svg" height="24" alt="straight and right" align="top">](https://commons.wikimedia.org/wiki/File:MUTCD_R3-6R.svg) lane:
   * If the user should turn right, highlight the right arrow.
   * If the user should go straight, highlight the straight arrow.
   * Otherwise [if the user should turn left], highlight the right arrow. 🙅‍♂️
* Otherwise, for a [<img src="https://upload.wikimedia.org/wikipedia/commons/6/62/MUTCD_R3-6L.svg" height="24" alt="straight and left" align="top">](https://commons.wikimedia.org/wiki/File:MUTCD_R3-6L.svg) lane:
   * If the user should turn right, highlight the right arrow. 🙅‍♂️
   * If the user should go straight, highlight the straight arrow.
   * Otherwise [if the user should turn left], highlight the right arrow.
   * Then flip the icon horizontally.

The pseudocode should look more like this:

* If the user should go straight, highlight the straight arrow.
* Otherwise, if the lane is [<img src="https://upload.wikimedia.org/wikipedia/commons/6/62/MUTCD_R3-6L.svg" height="24" alt="straight and left" align="top">](https://commons.wikimedia.org/wiki/File:MUTCD_R3-6L.svg) and the user should turn left, **or** if the lane is [<img src="https://upload.wikimedia.org/wikipedia/commons/5/5d/MUTCD_R3-6R.svg" height="24" alt="straight and right" align="top">](https://commons.wikimedia.org/wiki/File:MUTCD_R3-6R.svg) and the user should turn right, highlight the right arrow.
* Then, if the lane is [<img src="https://upload.wikimedia.org/wikipedia/commons/6/62/MUTCD_R3-6L.svg" height="24" alt="straight and left" align="top">](https://commons.wikimedia.org/wiki/File:MUTCD_R3-6L.svg), flip the icon horizontally.

Unfortunately, as far as I can tell, there’s no asset for a straight-turn icon that should not be highlighted at all.

Also, for now, the logic should conflate `sharp left` and `slight left` with `left` and `sharp right` and `slight right` with `right`. It is possible for a lane to be usable for both a right turn and a slight right turn at the same time, but for that edge case, we would need to consider the `active_direction` (#3935) and create a new asset (mapbox/navigation-ui-resources#8). So I think that should be outside the scope of this particular issue.

**Comment by LukasPaczos** [comment] 2021-08-23 15:28
Will be resolved by integrating https://github.com/mapbox/navigation-ui-resources/issues/23.

**Comment by 1ec5** [comment] 2021-09-17 16:01
mapbox/navigation-ui-resources#26 introduces a reasonably comprehensive set of assets and a more straightforward algorithm for selecting them. [This gist](https://gist.github.com/1ec5/45242ec5ca71fa4865c4731d9c9f538d) ports the algorithm to Python for convenience.

mapbox/mapbox-navigation-ios#3374 tracks a corresponding refactor on iOS, where we have a fix for the original issue above, but the fix is less elegant and not as comprehensive as what we want on both platforms.

**Closed** 2021-09-22 20:37 UTC
Labels: bug, UI
