### ISSUE TITLE
Failed to resolve: com.mapbox.navigator:mapbox-navigation-native:3.1.3

### ISSUE THREAD

**Issue by Hashir524** [mapbox/mapbox-navigation-android#1402] opened 2018-10-08 13:56 UTC
maven { url 'https://mapbox.bintray.com/mapbox' }
i added this repository link
This Error doesn't seems to go away.

**Android API: 28**
**Mapbox Navigation SDK version: 6.5.0**

### Steps to trigger behavior

 1.Gradle Build

**Comment by Guardiola31337** [comment] 2018-10-08 14:47
Hey @Hashir524 👋 

As noted in [`v0.21.0` release notes](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.21.0)

> **Important Note**: With this release, you _must_ include the following snippet in your project’s `build.gradle`:
>```
>repositories {
>    maven { url 'https://mapbox.bintray.com/mapbox' }
>}
>```
>
>This will ensure the `mapbox` dependency is properly downloaded.

Have you added it to the root project's `build.gradle`? Could you add some more information for reproducing the error or any other specifics around your setup? Could you share your `build.gradle` files / config? That would be really helpful because without having additional information, I'm unable to reproduce.

**Comment by Hashir524** [comment] 2018-10-08 15:42
Issue Resolved! (i Still Don't Know, What was the issue though. It just Worked) Thanks For your Response. 
Much Appreciated.

**Comment by Guardiola31337** [comment] 2018-10-08 15:51
Awesome! I guess some dependency cached 😂 

Thanks for the update @Hashir524

Closing as fixed.

**Closed by Guardiola31337** 2018-10-08 15:51 UTC
