### ISSUE TITLE
New here and need help with current 0.12.0

### ISSUE THREAD

**Issue by excapade** [mapbox/mapbox-navigation-android#839] opened 2018-04-09 22:32 UTC
Hi Guys,
I am new here so please forgive me if I am not as descriptive as possible or if this problem has been addressed. We are close to launching our app to beta but these issues are holding us back. I don't know if this has been solved, but If it has please point it out. But in the in-term our issues are listed below.

**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior
 1. On current driving route, during re-route
 2. initiating cycling and walking. 

### Expected behavior
1. Re-route worked in 0.11.0 but fails in 0.12.0.
2. Initiating walking and cycling worked in 0.11.0 but fails and continues loading in 0.12.0. 

### Actual behavior
1. Using 0.12.0, during navigation, the re-route fails on every time and doesn't re-route
2. Launching cycling and walking nav crashes.

**Comment by Guardiola31337** [comment] 2018-04-10 10:03
Hey @excapade 👋 Thanks for reaching out and report your problem.

Could you add some more information for reproducing the crash (minimal example) or any other specifics around your test setup? Do you have some more information on used device? If there is any sample or pseudo code you can provide, that would be really helpful (especially the differences between what was working on `0.11.0` and not working on `0.12.0` anymore).

**Comment by danesfeder** [comment] 2018-04-10 12:55
Hey @excapade, thank you for bringing these issues to us.  Both of the issues you found are on our side and have been addressed.  

The index exception was fixed in #784 and tests were added to ensure this won't happen again.  

The profile issues you're seeing in `0.12.0` is being fixed with #829 - where previously we were allowing invalid profiles to be set.  It looks like `get_directions_profile()` has a default value of `return "";` - this would cause the issues you're seeing.  Please replace `""` with something like `DirectionsCriteria.PROFILE_DRIVING_TRAFFIC` as the default and should fix this issue until that PR lands.  Thanks for checking out the SDK!

**Closed by danesfeder** 2018-04-10 12:55 UTC
Labels: bug
