### ISSUE TITLE
NPE when comparing a new route

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2727] opened 2020-04-08 09:24 UTC
Here's a crash caught by the 1Tap's robo tests. This might be related to https://github.com/mapbox/mapbox-navigation-android/issues/2654.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
	at com.mapbox.navigation.ui.route.MapRouteProgressChangeListener.isANewRoute(MapRouteProgressChangeListener.java:52)
	at com.mapbox.navigation.ui.route.MapRouteProgressChangeListener.addNewRoute(MapRouteProgressChangeListener.java:44)
	at com.mapbox.navigation.ui.route.MapRouteProgressChangeListener.onProgressChange(MapRouteProgressChangeListener.java:34)
	at com.mapbox.navigation.ui.route.MapRouteProgressChangeListener.onRouteProgressChanged(MapRouteProgressChangeListener.java:24)
	at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:289)
	at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:31)
	at com.mapbox.navigation.core.trip.session.MapboxTripSession$fireOffStatusPolling$1.invokeSuspend(MapboxTripSession.kt:267)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:132)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:126)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:102)
	at androidx.test.espresso.action.Tap$2.a(Tap.java:7)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:33)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

/cc @mapbox/1tap-android @abhishek1508 @cafesilencio

**Comment by evabishchevich** [comment] 2020-04-08 10:53
It should be fixed by https://github.com/mapbox/mapbox-navigation-android/pull/2703. Duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/2693

**Closed by evabishchevich** 2020-04-08 10:53 UTC
Labels: UI SDK v1+, bug
