### ISSUE TITLE
App module. ExampleActivity. Flow is broken

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#2492] opened 2020-02-18 12:36 UTC
Example activity. `Where to?` field
Flow is broken: 
1. tap on `Where to?` field
2. start typing
3. get crash: `Failed resolution of: Lcom/mapbox/geojson/gson/PointDeserializer;`

will be available after [pr](https://github.com/mapbox/mapbox-navigation-android/pull/2464) will be merged

**Comment by JunDai** [comment] 2020-02-19 01:12
@Guardiola31337 - this issue isn't caused by @RingerJK 's PR #2464 
It exists in the current legacy code. What it happens is `PointDeserializer` class has been removed in map-android-sdk but the autoCompleteInputTextView is still relying on it.

Do you know where is the code of `com.mapbox.android.search.storage.PreferencesHistoryStorage` so we could update that UI plugin lib accordingly to fix this issue.

```
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/geojson/gson/PointDeserializer;
        at com.mapbox.android.search.storage.PreferencesHistoryStorage.<init>(PreferencesHistoryStorage.java:39)
        at com.mapbox.android.search.MapboxSearch.getHistoryStorage(MapboxSearch.java:114)
        at com.mapbox.android.search.MapboxSearch.getSearchClient(MapboxSearch.java:107)
        at com.mapbox.android.search.MapboxSearch.searchSync(MapboxSearch.java:77)
        at com.mapbox.android.search.autocomplete.AutocompleteFilter.performFiltering(AutocompleteFilter.java:59)
```

**Comment by RingerJK** [comment] 2020-02-19 08:03
@JunDai great catch!

**Comment by Guardiola31337** [comment] 2020-03-02 23:27
Testing https://github.com/mapbox/mapbox-navigation-android/pull/2516 I run into the same crash above-mentioned

```
03-02 18:12:18.052 19226-30554/com.mapbox.services.android.navigation.app E/AndroidRuntime: FATAL EXCEPTION: Filter
    Process: com.mapbox.services.android.navigation.app, PID: 19226
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/geojson/gson/PointDeserializer;
        at com.mapbox.android.search.storage.PreferencesHistoryStorage.<init>(PreferencesHistoryStorage.java:39)
        at com.mapbox.android.search.MapboxSearch.getHistoryStorage(MapboxSearch.java:114)
        at com.mapbox.android.search.MapboxSearch.getSearchClient(MapboxSearch.java:107)
        at com.mapbox.android.search.MapboxSearch.searchSync(MapboxSearch.java:77)
        at com.mapbox.android.search.autocomplete.AutocompleteFilter.performFiltering(AutocompleteFilter.java:59)
        at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.geojson.gson.PointDeserializer" on path: DexPathList[[zip file "/data/app/com.mapbox.services.android.navigation.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.services.android.navigation.app-1/lib/arm, /data/app/com.mapbox.services.android.navigation.app-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.mapbox.android.search.storage.PreferencesHistoryStorage.<init>(PreferencesHistoryStorage.java:39) 
        at com.mapbox.android.search.MapboxSearch.getHistoryStorage(MapboxSearch.java:114) 
        at com.mapbox.android.search.MapboxSearch.getSearchClient(MapboxSearch.java:107) 
        at com.mapbox.android.search.MapboxSearch.searchSync(MapboxSearch.java:77) 
        at com.mapbox.android.search.autocomplete.AutocompleteFilter.performFiltering(AutocompleteFilter.java:59) 
        at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
    	Suppressed: java.lang.ClassNotFoundException: com.mapbox.geojson.gson.PointDeserializer
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 10 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by Guardiola31337** [comment] 2020-06-01 15:18
Any updates here @JunDai @RingerJK?

**Comment by JunDai** [comment] 2020-06-01 15:22
@Guardiola31337 - I didn't work on this issue. I just verified this issue is still in the `app` example.

> Do you know where is the code of com.mapbox.android.search.storage.PreferencesHistoryStorage so we could update that UI plugin lib accordingly to fix this issue.

If anyone know ☝️ where `PreferencesHistoryStorage` is, we might be able to have a fix.

**Comment by Guardiola31337** [comment] 2020-06-01 18:20
This example is not available anymore.

Closing here.

cc @abhishek1508

**Closed by Guardiola31337** 2020-06-01 18:20 UTC
Labels: navigation-ui, new API(s), quick fix

**Comment by RingerJK** [comment] 2020-06-02 08:42
Issue is a part of pre `1.0` samples
