### ISSUE TITLE
NoSuchMethodError: No static method formatCoordinate(D)

### ISSUE THREAD

**Issue by retuner87** [mapbox/mapbox-navigation-android#89] opened 2017-06-20 10:34 UTC
Hi, I'm trying to implement this library on my application but, when I try "MockNavigationActivity.java" I find this runtime message:

java.lang.NoSuchMethodError: No static method formatCoordinate(D)Ljava/lang/String; in class Lcom/mapbox/services/commons/utils/TextUtils; or its super classes (declaration of 'com.mapbox.services.commons.utils.TextUtils' appears in ...

when I try:

navigation.getRoute(origin, destination, new Callback<DirectionsResponse>() {
    @Override
    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
        DirectionsRoute route = response.body().getRoutes().get(0);
        NavigationActivity.this.route = route;
        drawRouteLine(route);
    }

    @Override
    public void onFailure(Call<DirectionsResponse> call, Throwable throwable) {
        Timber.e("onFailure: navigation.getRoute()", throwable);
    }
});
How can I resolve it? Please help me!

Thanks,
Mattia

**Comment by cammace** [comment] 2017-06-20 17:14
The stack trace goes back to [these methods](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libjava-core/src/main/java/com/mapbox/services/commons/utils/TextUtils.java#L57-L84) but getRoute isn't using that method and I am unable to reproduce. Are you using the latest code found in Master?

**Comment by cammace** [comment] 2017-06-27 01:28
Going ahead and closing this issue, if you are still running into issues, please comment and I'll be happy to help out.

**Closed by cammace** 2017-06-27 01:28 UTC

**Comment by retuner87** [comment] 2017-06-27 10:17
Yes, thanks for the reply!
