### ISSUE TITLE
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.    > Could not find com.mapbox.mapboxsdk:mapbox-android-sdk-gl-core:5.3.0.

### ISSUE THREAD

**Issue by syedwarisalirehmani** [mapbox/mapbox-navigation-android#4936] opened 2021-10-04 10:17 UTC
I have updated MapBox SDK version from 
 com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.2
to 
com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.0 bec

**Comment by kmadsen** [comment] 2021-10-05 18:27
Closing this issue since it seems to be a duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/4937

The library it seems you are trying to resolve is published from this repository https://github.com/mapbox/mapbox-java/releases. But let's resolve your issues through the other ticket https://github.com/mapbox/mapbox-navigation-android/issues/4937. Thanks!!

**Closed by kmadsen** 2021-10-05 18:27 UTC
