### ISSUE TITLE
Navigation Voice Changes to the Device TTS Voice

### ISSUE THREAD

**Issue by billyking991** [mapbox/mapbox-navigation-android#1986] opened 2019-06-27 22:29 UTC
When the device has a poor connection, the Amazon Polly voice switches to the device TTS voice.  The iOS SDK doesn't seem to have this issue.  Is there a way to keep the voice on the Polly voice all the time?  It's jarring and I get emails from users wondering why the voice changes abruptly.  If it's not possible, it's totally OK.  I was just hoping there was a way to fix the issue.

**Android API:**
Android 5 - 9
**Mapbox Navigation SDK version:**
Mapbox 0.20.0 - 0.40.0

### Steps to trigger behavior

 1.   Start Navigation
 2.  Go someplace with a very poor connection
 3.  Wait for the next voice instruction.

### Expected behavior
The iOS app doesn't exhibit this issue.  The voice is always the Amazon Polly voice.  Is there a way to make the Android app behave the same way?
### Actual behavior
The voice switches to the device TTS voice when there is a poor connection.  This is jarring and people have been emailing me and asking why it's happening.  

Thank you for the help!!

**Comment by Guardiola31337** [comment] 2019-06-28 22:31
Hey @billyking991 👋 thanks for reaching out and report your question.

> When the device has a poor connection, the Amazon Polly voice switches to the device TTS voice.

You're right and this is on purpose. We actually do that as a backup so all the instructions are always announced and users don't missed any (in our opinion missing instructions hurt considerably the navigation experience). You can check out the implementation details here 👀 https://github.com/mapbox/mapbox-navigation-android/blob/e6d0e2882c7aac50f2a11623331f8c3d7da5cf88/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechPlayerProvider.java#L56-L62

> The iOS SDK doesn't seem to have this issue.

Not completely sure how the iOS SDK is handling this scenario but @1ec5 can speak about it.

> Is there a way to keep the voice on the Polly voice all the time?

You can pass in a custom `SpeechPlayer` via [`NavigationViewOptions.Builder#speechPlayer`](https://github.com/mapbox/mapbox-navigation-android/blob/e6d0e2882c7aac50f2a11623331f8c3d7da5cf88/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewOptions.java#L99). By default we're using the [`NavigationSpeechPlayer`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechPlayer.java) which implements the fallback logic described above but you can either:

- Implement something similar to [`MapboxSpeechPlayer`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java) which will use the Amazon Polly voice but when poor connectivity the announcement could be missed.
- Implement something similar to [`AndroidSpeechPlayer`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/AndroidSpeechPlayer.java) which will use the the device TTS voice always and all of the announcements are guaranteed but without SSML support.
- Go wild and implement a fully custom `SpeechPlayer`.

Hope ☝️ answers your question. Thanks again!

**Comment by Guardiola31337** [comment] 2020-07-08 13:53
@JunDai could we check if this would be an issue in `1.0`? Probably fixed by #3297, right?

**Comment by abhishek1508** [comment] 2020-07-13 18:23
Let's verify.
cc @JunDai @cafesilencio @langsmith

**Comment by JunDai** [comment] 2020-07-14 00:54
> @JunDai could we check if this would be an issue in `1.0`? Probably fixed by #3297, right?

unfortunately, v1.0 will have this issue too. We will fallback to TTS when network is poor and the coming voice instruction isn't cached. But as @Guardiola31337  mentioned, the developer can provide their own implementation of `SpeechPlayer` to stick on the Polly voice.

**Comment by JunDai** [comment] 2020-07-14 00:55
> > The iOS SDK doesn't seem to have this issue.

> Not completely sure how the iOS SDK is handling this scenario but @1ec5 can speak about it.

@1ec5 - do you remember how iOS SDK handle this issue so it will always go to Polly?

**Comment by JunDai** [comment] 2020-07-24 18:40
> > > The iOS SDK doesn't seem to have this issue.
> 
> > Not completely sure how the iOS SDK is handling this scenario but @1ec5 can speak about it.
> 
> @1ec5 - do you remember how iOS SDK handle this issue so it will always go to Polly?

@1ec5 - any input is appreciated 👍

**Comment by 1ec5** [comment] 2020-07-24 19:11
> do you remember how iOS SDK handle this issue so it will always go to Polly?

By default, the iOS navigation SDK tries to use Amazon Polly through the Mapbox Voice API and falls back to VoiceOver if it’s unable to reach the API for any reason. To minimize usage of that fallback, the SDK prefetches a small number of voice instructions ahead of the current instruction (determined by `MapboxSpeechSynthesizer.stepsAheadToCache`). @billyking991, you may be seeing a situation where the iOS navigation SDK got lucky and has already prefetched the instructions before the connection went bad.

The other difference between platforms, which I haven’t appreciated until now, is that the iOS implementation doesn’t explicitly check the quality of the connection or the Voice API’s reachability before attempting to request a voice instruction from the API. This is because iOS, by design, does not expose a reliable network reachability API to applications. It only exposes a way to [check if the system is correctly configured](https://developer.apple.com/documentation/systemconfiguration/scnetworkreachability-g7d) to connect to the Internet in general and not, say, subject to a captive network or Airplane Mode. As Apple recommends, we just try the connection and deal with any failure after the fact, which probably differs from the norm on Android. I suppose this could account for the difference you’re seeing between platforms, but it’s more likely to be lucky prefetching.

**Comment by JunDai** [comment] 2020-07-27 14:21
Thanks for clarifying the iOS behavior. @1ec5

**Comment by JunDai** [comment] 2020-07-27 14:25
@billyking991 - Did you manage the speechPlayer by yourself or just use the Mapbox offered default implementation of voice instruction?
May I know which component you were using, like The `NavigationView` or the stand-alone UI component like `InstructionView` and the `SpeechPlayer`?

**Comment by billyking991** [comment] 2020-07-27 14:28
I just used the standard Mapbox implementation with the NavigationView on Android.  I have a SpeechAnouncementListener that is set in the NavigationViewOptions.

**Comment by JunDai** [comment] 2020-07-27 14:55
> I just used the standard Mapbox implementation with the NavigationView on Android. I have a SpeechAnouncementListener that is set in the NavigationViewOptions.

thanks for the quick reply.

As you can see that iOS should have the same behavior like Android, but due to slightly different API restriction, it's not easy to be found on iOS.

I am considering we could add some options to disable the TTS fallback. We will be discussing this with team.

**Closed** 2020-08-11 14:28 UTC
Labels: bug, low priority, navigation-ui, topic: instructions, topic: voice

**Comment by JunDai** [comment] 2020-08-11 14:32
@billyking991 - https://github.com/mapbox/mapbox-navigation-android/pull/3415 is merged. You should be able to get the same behavior as iOS now on Android. Feel free to report new issue.
