### ISSUE TITLE
NullPointerException inside MapRouteLine.updateTraveledRouteLine 

### ISSUE THREAD

**Issue by yuryybk** [mapbox/mapbox-navigation-android#3836] opened 2020-11-30 15:21 UTC
Android API: 27
Mapbox Navigation SDK version: 1.2.0-alpha.5

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.geojson.Point com.mapbox.navigation.ui.route.RouteLineDistancesIndex.getPoint()' on a null object reference
       at com.mapbox.navigation.ui.route.MapRouteLine.updateTraveledRouteLine(MapRouteLine.kt:1053)
       at com.mapbox.navigation.ui.route.NavigationMapRoute$1.onIndicatorPositionChanged(NavigationMapRoute.java:343)
       at com.mapbox.mapboxsdk.location.LocationComponent$10.onIndicatorPositionChanged(LocationComponent.java:1880)
       at com.mapbox.mapboxsdk.location.LocationLayerController$1.onNewAnimationValue(LocationLayerController.java:269)
       at com.mapbox.mapboxsdk.location.LocationLayerController$1.onNewAnimationValue(LocationLayerController.java:265)
       at com.mapbox.mapboxsdk.location.MapboxAnimator.postUpdates(MapboxAnimator.java:106)
       at com.mapbox.mapboxsdk.location.MapboxAnimator.onAnimationUpdate(MapboxAnimator.java:93)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1522)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1316)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1446)
       at android.animation.ValueAnimator.pulseAnimationFrame(ValueAnimator.java:1465)
       at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1163)
       at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1054)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.-wrap2()
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:655)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6747)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by LukasPaczos** [comment] 2020-11-30 15:23
Thanks for reporting @yuryybk! Closing as a duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/3690.

**Closed by LukasPaczos** 2020-11-30 15:23 UTC
