### ISSUE TITLE
Could not find com.mapbox.navigator:mapbox-navigation-native:7.0.0.

### ISSUE THREAD

**Issue by markvanheerden** [mapbox/mapbox-navigation-android#3743] opened 2020-11-06 11:26 UTC
I am currently building an android navigation app and have run into an issue. The full error is:

> Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.mapbox.navigator:mapbox-navigation-native:7.0.0.
    > Searched in the following locations:
       >- https://dl.google.com/dl/android/maven2/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom
      > - https://jcenter.bintray.com/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom
       >- https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom
     >Required by:
         >project :app > com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6 > com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6

>Possible solution:
 >- Declare repository providing the artifact, see the documentation at >https://docs.gradle.org/current/userguide/declaring_repositories.html

 I am following this tutorial: https://docs.mapbox.com/help/tutorials/android-navigation-sdk/?size=n_10_n

So in my app-level build.gradle file, I added this dependency: 
`implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'`

And in my module-level build.gradle file, under repositories, I added this: 
`maven { url 'https://mapbox.bintray.com/mapbox' }`

So I am really not sure why it is giving me this issue. Could anyone possibly assist?

**Comment by ziadesm** [comment] 2020-11-15 15:45
Same as you ..

Could not find com.mapbox.navigator:mapbox-navigation-native:7.0.0.
Required by:
    project :app
    project :app > com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6

**Comment by Guardiola31337** [comment] 2020-12-21 17:59
Hey @markvanheerden and @ziadesm thanks for reaching out and report your issue.

Would you mind re-testing / confirming if OP is still an issue in 1.x (latest stable available is [`1.3.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v1.3.0))? You can review the developer [documentation](https://docs.mapbox.com/android/beta/navigation/overview/) to start building with the Mapbox Navigation SDK v1.0 for Android and check out the [migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide) to transition your project from the "legacy" Navigation SDK to the 1.0 version and let us know if you have any questions or run into issues. We would love your feedback.

**Comment by Luisa-98** [comment] 2021-02-28 16:38
Hi, I have the same issue and was not able to found a solution yet. Does anybody know how to solve this?

**Comment by LukasPaczos** [comment] 2021-07-15 16:50
Closing as a duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/4533.

**Closed by LukasPaczos** 2021-07-15 16:50 UTC
