### ISSUE TITLE
Question: Low Signal Navigation

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1985] opened 2019-06-27 09:17 UTC
We have had some users who are using our app complain when they are in bad phone signal areas, the Navigation is crashing, I still yet have to see this for myself and retrieve some log files, i'm just wondering if this is something you've seen before.

Some of our drivers are going through Tunnels, loosing internet connectivity then the application is crashing.

**Gradle Implentation**
```java
    // Mapbox Maps SDK
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.33.2') {
        transitive = true
        changing = true
    }
```

If you have anything you could recommend until i can replicate the issue or retrieve log files.

**Comment by Guardiola31337** [comment] 2019-06-28 21:33
Hey @Danny-James 👋 Current release version is [`0.40.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.40.0). To confirm that the issue is still present in the latest version, would you mind retesting it using `0.40.0` version? As you can imagine there have been a bunch of improvements and new features plus lots of bug fixes since `0.33.2`. Also a lot of our underlying route-following logic for tunnels has been updated.

Please consult the [migration guides](https://github.com/mapbox/mapbox-navigation-android/wiki#recent-migration-guides) for the necessary updates required and reach out to us if you have any questions or if you run into any issues. Thanks in advance!

**Comment by Danny-James** [comment] 2019-07-04 12:40
@Guardiola31337 I've just been through a long underwater tunnel and the Navigation worked fine with the Latest Stable Version.

Thank You!

**Comment by Guardiola31337** [comment] 2019-07-04 14:40
Awesome :tada: Thanks for the update @Danny-James 

Closing as solved.

**Closed by Guardiola31337** 2019-07-04 14:40 UTC
