### ISSUE TITLE
Voice instruction cache - no such file ex

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3134] opened 2020-06-08 12:49 UTC
The voice mp3s downloader crashed when in an active guidance session:
```
Caused by java.io.FileNotFoundException: /data/user/0/com.mapbox.onetap.app/cache/mapbox_instruction_cache/37.mp3: open failed: ENOENT (No such file or directory)
       at libcore.io.IoBridge.open(IoBridge.java:496)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
       at com.mapbox.navigation.ui.legacy.DownloadTask.saveAsFile(DownloadTask.java:64)
       at com.mapbox.navigation.ui.legacy.DownloadTask.doInBackground(DownloadTask.java:42)
       at com.mapbox.navigation.ui.legacy.DownloadTask.doInBackground(DownloadTask.java:20)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```
```
Caused by android.system.ErrnoException: open failed: ENOENT (No such file or directory)
       at libcore.io.Linux.open(Linux.java)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
       at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
       at libcore.io.IoBridge.open(IoBridge.java:482)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
       at com.mapbox.navigation.ui.legacy.DownloadTask.saveAsFile(DownloadTask.java:64)
       at com.mapbox.navigation.ui.legacy.DownloadTask.doInBackground(DownloadTask.java:42)
       at com.mapbox.navigation.ui.legacy.DownloadTask.doInBackground(DownloadTask.java:20)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

/cc @abhishek1508

**Comment by Guardiola31337** [comment] 2020-06-08 12:59
Duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/2837

Closing.

cc @kmadsen @JunDai @LukasPaczos

**Closed by Guardiola31337** 2020-06-08 12:59 UTC
