### ISSUE TITLE
NavigationCancelEvent is sent after arrival

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3818] opened 2020-11-25 13:18 UTC
Steps to repro:
1. Start a route.
2. Reach the destination.
3. Close the activity.

Even though we have successfully arrived, the closure of the activity still triggers a `NavigationCancelEvent`.
```
D/MAPBOX_TELEMETRY: Valid initialization
D/MAPBOX_TELEMETRY: onRoutesChanged. size = 1
D/MAPBOX_TELEMETRY: session state is ACTIVE_GUIDANCE
D/MAPBOX_TELEMETRY: flush buffer. Pending events = 0
D/MAPBOX_TELEMETRY: Lifecycle monitor created
D/MAPBOX_TELEMETRY: sessionStart
D/MAPBOX_TELEMETRY: populateNavigationEvent
D/MAPBOX_TELEMETRY: class com.mapbox.navigation.core.telemetry.events.NavigationDepartEvent event sent
D/MAPBOX_TELEMETRY: onFinalDestinationArrival
D/MAPBOX_TELEMETRY: you have arrived
D/MAPBOX_TELEMETRY: populateNavigationEvent
D/MAPBOX_TELEMETRY: class com.mapbox.navigation.core.telemetry.events.NavigationArriveEvent event sent
D/MAPBOX_TELEMETRY: session state is IDLE
D/MAPBOX_TELEMETRY: sessionStop
D/MAPBOX_TELEMETRY: handleSessionCanceled
D/MAPBOX_TELEMETRY: flush buffer. Pending events = 0
D/MAPBOX_TELEMETRY: populateNavigationEvent
D/MAPBOX_TELEMETRY: class com.mapbox.navigation.core.telemetry.events.NavigationCancelEvent event sent
D/MAPBOX_TELEMETRY: resetOriginalRoute
D/MAPBOX_TELEMETRY: resetRouteProgress
D/MAPBOX_TELEMETRY: MapboxNavigation onDestroy
```

/cc @Guardiola31337 @korshaknn @baddleydone

**Comment by korshaknn** [comment] 2020-11-25 13:35
@LukasPaczos it's expected. `cancel` event is a final event in a session.

**Comment by LukasPaczos** [comment] 2020-11-25 13:45
@baddleydone @asinghal22 is that your expectation as well?

**Comment by Guardiola31337** [comment] 2020-11-25 13:47
That's by design. Every trip should always have depart and cancel events, irrespective of arrival.

> is that your expectation as well?

Yes.

Closing here.

**Closed by Guardiola31337** 2020-11-25 13:47 UTC
Labels: Core

**Comment by LukasPaczos** [comment] 2020-11-25 13:50
Thanks for confirming @korshaknn @Guardiola31337 :+1:
