### ISSUE TITLE
Not receiving Milestone and ProgressChange Events 

### ISSUE THREAD

**Issue by sm-azure** [mapbox/mapbox-navigation-android#694] opened 2018-02-12 15:33 UTC
Following the example here - https://www.mapbox.com/help/android-navigation-sdk/

Application works as described. Implemented the interfaces MilestoneEventListener, ProgressChangeListener in the MainActivity and passed to NavigationLauncher as part of the NavigationViewOptions. No callback occurs. 

Here is the NavigationViewOption being passed. 
`NavigationViewOptions options = NavigationViewOptions.builder()
                                .origin(origin)
                                .destination(destination)
                                .awsPoolId(awsPoolId)
                                .shouldSimulateRoute(simulateRoute)
                                .milestoneEventListener(MainActivity.this)
                                .progressChangeListener(MainActivity.this)
                                .build();`

Expected Response: Callback happens
Actual Response: No Callback

In fact the code in https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationLauncher.java does not indicate that the milestone/progress change is being passed on. 

How do I get the callbacks?

**Comment by Guardiola31337** [comment] 2018-03-21 18:11
Hey @sm-azure 👋 thanks for reaching out and report your problem.

Closing here as duplicate of #752 

BTW, this should be fixed by https://github.com/mapbox/mapbox-navigation-android/pull/782

Let us know if you have any other questions!

**Closed by Guardiola31337** 2018-03-21 18:11 UTC
