### ISSUE TITLE
Puck layout is not updated when switching modes

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2867] opened 2020-04-29 22:22 UTC
When testing the `examples` test app noticed that the puck appearance is not updated when switching between _Active Guidance_ and _Free Drive_ 👀 

`DebugMapboxNavigationKt` (`SimpleMapboxNavigationKt`)

![debug_mapbox_navigation_kt_free_drive](https://user-images.githubusercontent.com/1668582/80652199-7778bf80-8a45-11ea-88d1-a373f5964c45.png)

![debug_mapbox_navigation_kt_free_drive_notification](https://user-images.githubusercontent.com/1668582/80652209-7a73b000-8a45-11ea-844d-4973a6a9543f.png)

`FreeDriveNavigationActivity`

![free_drive_navigation_activity_puck](https://user-images.githubusercontent.com/1668582/80652345-b73fa700-8a45-11ea-80a1-bf04440e3f11.png)

Not sure if it's an issue in the examples setup or in the UI SDK when handling the _Free Drive_ use case but we should be consistent either way. It seems that the puck layout is not reset and we keep using the one from _Active Guidance_.

Refs. https://github.com/mapbox/mapbox-navigation-android/pull/2698

cc @cafesilencio @abhishek1508

**Comment by JunDai** [comment] 2020-05-04 22:15
hey @kmadsen : would you mind to take a look at this issue and fix it against the `ReplayHistoryActivity` example?
I have https://github.com/mapbox/mapbox-navigation-android/pull/2881 to fix this issue on most of the examples. But I have difficulty to make changes to `ReplayHistoryActivity`.

The main change of my PR is about when user clicks the `End Navigation` button from the Notification, it needs to do two things:
* clear the route which has been drawn on the mapView.
* reset the puck icon back to normal.

**Comment by kmadsen** [comment] 2020-05-05 03:53
Hey @JunDai, I dug into this. Can you give more details of the issues you're seeing in `ReplayHistoryActivity`?

It's unclear to me whether you're reproducing an issue we need to fix in the SDK, or an issue we need to fix in `ReplayHistoryAcitivty`..

For example, when I dug into this too, the issue I saw was seemed to because of `updateCameraTrackingMode(NavigationCamera.NAVIGATION_TRACKING_MODE_NONE)`
https://github.com/mapbox/mapbox-navigation-android/compare/km-update-camera-tracking-issue?expand=1#diff-816c9a378f2dd5cdea15ad9d1df98ee9R175

**Comment by JunDai** [comment] 2020-05-05 15:55
as we got the agreement on this, the `ReplayHistoryActivity` is not supposed to focus on the overall navigation experience. It's mainly focus on the **ReplayHistory**.

So we could close this issue.

**Closed by JunDai** 2020-05-05 15:55 UTC
Labels: UI SDK v1+, bug, test app

**Comment by Guardiola31337** [comment] 2020-05-05 18:10
We should address the `START NAVIGATION` button inconsistency as part of https://github.com/mapbox/mapbox-navigation-android/issues/2860 that is also reproducible in `ReplayHistoryActivity` cc @JunDai @kmadsen

**Comment by kmadsen** [comment] 2020-05-05 21:00
`ReplayHistoryActivity` doesn't have a `start navigation` button. The call to action, is to start playing history.

**Comment by Guardiola31337** [comment] 2020-05-05 21:23
@kmadsen 
> `ReplayHistoryActivity` doesn't have a `start navigation` button. The call to action, is to start playing history.

It has a `PLAY HISTORY` one

![replay_history_activity_play_history_button](https://user-images.githubusercontent.com/1668582/81117261-c797cc00-8ef4-11ea-9c49-85ab3f53416c.png)

which is enabled if previously clicked (session has started). What happens if in a replaying session this is re-clicked? Also if a session is stopped from the notification, does the session restarts when clicking on `PLAY HISTORY`?
