### ISSUE TITLE
calling HttpServiceFactory.setUserDefined() not correctly

### ISSUE THREAD

**Issue by Romain-gdev** [mapbox/mapbox-navigation-android#4329] opened 2021-04-28 09:21 UTC
**Android API: 30**
**Mapbox Navigation SDK version: ui:1.5.1**

### Steps to trigger behavior

 1. Create an OnclickListener on a button to start Navigation
 2. Select a destination on the map
 3. Click on start Navigation Button and it triggers the error

### Expected behavior
Have an activity with the navigation and its time to go to the destination
### Actual behavior
![image](https://user-images.githubusercontent.com/78152569/116379425-46c39580-a813-11eb-8d9d-cd3c0e30f088.png)
The error on debug mode :
`E/MapboxNavNative: User defined HTTP service instance not provided from the module implementation.
Module: com.mapbox.common.module.okhttp.MapboxOkHttpService@5ac496
but present is: com.mapbox.common.module.okhttp.MapboxOkHttpService@5ac496
Are you calling HttpServiceFactory.setUserDefined() correctly?`

**Comment by Romain-gdev** [comment] 2021-04-28 09:22
Someone got the same error but didn't share his solution [https://github.com/mapbox/mapbox-navigation-android/issues/3660](url)

**Comment by ugurcanatas** [comment] 2021-04-28 18:55
![device-2021-04-28-215056](https://user-images.githubusercontent.com/22047299/116457292-e3198680-a86b-11eb-9fe3-ef0ae713a54d.png)

Hey there. Is there any updates on this ? I am receiving the same log message.
`User defined HTTP service instance not provided from the module implementation.
    Module: com.mapbox.common.module.okhttp.MapboxOkHttpService@c8ebc12
    but present is: com.mapbox.common.module.okhttp.MapboxOkHttpService@c8ebc12
    Are you calling HttpServiceFactory.setUserDefined() correctly?`

Some information;

- onNavigationReady gets called
- Simulation stops right after first leg or first stop
- I am using DirectionsRoute.fromJson

**Comment by ugurcanatas** [comment] 2021-04-28 19:36
Okay, so here's what i've tried. I tried using the example directions route in the documentation at [https://docs.mapbox.com/android/navigation/examples/basic-nav-ui-sdk/](url) and simulation works without an issue. 
I think there is a problem with directions route that i am trying to parse. I am going to compare those two JSON to see there is any difference.

I don't know if i should be asking this question here but, can i use the MapMatching response from MapMatching API in MapboxNavigation using `DirectionsRoute.fromJson` ?

Thanks.

**Comment by ugurcanatas** [comment] 2021-04-29 10:14
I am using MapMatching builder to retrieve a match. It's correctly showing matched route but the issue is navigation does not start. 
Here is the MapMatching code
`MapboxMapMatching mapboxMapMatching = MapboxMapMatching.builder()
                    .accessToken(token)
                    .coordinates(pointList)
                    .steps(true)
                    .voiceInstructions(true)
                    .waypointIndices(0,pointList.size() - 1)
                    .bannerInstructions(true)
                    .tidy(true)
                    .profile(DirectionsCriteria.PROFILE_DRIVING)
                    .build();`

After this, i receive a map matched route. But when i try to start the navigation with that route, navigation does not start and banner instructions view seems to be empty. Here is an image.
![device-2021-04-29-130226](https://user-images.githubusercontent.com/22047299/116534439-31ba3580-a8eb-11eb-8b61-2985e7a45efb.png)

- Seems like onRouteProgressChanged is running but i am receiving this log message. I think navigation stays on the same route leg for some reason because i am not seeing any changes in onRouteProgressChanged.
` E/NavigationActivity: onRouteProgressChanged: RouteProgress(route=DirectionsRoute{routeIndex=null, distance=892.041, duration=123.915, durationTypical=null, geometry=wmqeeA_vdaaA|z@huAltBzqExiA|bDti@we@, weight=159.604, weightName=auto, legs=[RouteLeg{distance=892.041, duration=123.915, durationTypical=null, summary=Cemal Paşa Caddesi,.....`

- While this is not working for some reason, if i use DirectionsRoute as shown in the documentation, navigation starts without a problem.
-Still seeing `HTTP service instance not provided from the module implementation. Module: com.mapbox.common.module.okhttp.MapboxOkHttpService@c8ebc12 but present is: com.mapbox.common.module.okhttp.MapboxOkHttpService@c8ebc12 Are you calling HttpServiceFactory.setUserDefined() correctly?` when navigation first starting.

It seems like this is a problem related to map matching.

**Comment by LukasPaczos** [comment] 2021-05-04 16:56
Hey @Romain-gdev @ugurcanatas, this log
```
HTTP service instance not provided from the module implementation. Module: com.mapbox.common.module.okhttp.MapboxOkHttpService@c8ebc12 but present is: com.mapbox.common.module.okhttp.MapboxOkHttpService@c8ebc12 Are you calling HttpServiceFactory.setUserDefined() correctly?
```
is unrelated and is just an incorrect message. There's nothing going wrong and the log is removed in future versions.

For the blank map that you see @Romain-gdev, are you sure you are passing a correct access token? Are there any other error logs?

For that stuck route @ugurcanatas, could you share the resulting route JSON that doesn't work, after the map matching takes place?

**Comment by ugurcanatas** [comment] 2021-05-04 21:11
Thanks for the response @LukasPaczos . 
Here is a .txt file containing Map Matching Response.
[response.txt](https://github.com/mapbox/mapbox-navigation-android/files/6423969/response.txt)

I tried it on a clean empty project but still same result. I switched back to an old version for the time being.

**Comment by LukasPaczos** [comment] 2021-05-06 10:45
Thanks @ugurcanatas! Unfortunately, this string representation is hard to work with, could you share a result of this:
```
mapMatchingResponse.matchings()[0].toDirectionRoute().toJson()
```

I understand that this is the route that you're passing to the SDK, right?

**Comment by ugurcanatas** [comment] 2021-05-12 19:51
Thanks @LukasPaczos . Sorry about that. This should be correct format.
[route.txt](https://github.com/mapbox/mapbox-navigation-android/files/6468742/route.txt)

**Comment by LukasPaczos** [comment] 2021-05-18 14:25
Thanks @ugurcanatas I was able to reproduce the issue, it fails because of an incorrect geometry index. I passed the issue on for investigation whether that's and SDK issue or an API issue. I'll report back here when we know more.

**Comment by ugurcanatas** [comment] 2021-05-18 14:27
Thanks for looking into it @LukasPaczos .

**Comment by LukasPaczos** [comment] 2021-05-19 09:44
@ugurcanatas it looks like the MapMatching API response might be mangled and returns incorrect indices.

Could you pass us the original request? Make sure to redact the token.
```
MapboxMapMatching.builder()
    ...
    .build()
    .cloneCall()
    .request()
    .url
```

**Comment by ugurcanatas** [comment] 2021-05-19 09:56
@LukasPaczos Here it is.
`https://api.mapbox.com/matching/v5/mapbox/driving/34.642247,36.812749;34.641199,36.812798;34.641534,36.809964?access_token=ACCESS_TOKEN&geometries=polyline6&steps=true&tidy=true&banner_instructions=true&voice_instructions=true&waypoints=0%3B2`

**Comment by LukasPaczos** [comment] 2021-05-19 10:45
Thanks!

The issue is a missing `overview=full` param. Try this:
```
MapboxMapMatching.builder()
    .overview(DirectionsCriteria.OVERVIEW_FULL)
    ...
    .build()
```

Also, it might be worth applying other parameters that are listed below, so that you can take advantage of all the Nav SDK features:
https://github.com/mapbox/mapbox-navigation-android/blob/7b760cea94b72c242ea3b60362ed4a83f93269e2/libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/RouteOptionsEx.kt#L56-L72

Heads up that rerouting won't work and you need to provide your own `RerouteController`.

Closing here for now but we'll work on improving the documentation around this use case.

**Closed by LukasPaczos** 2021-05-19 10:45 UTC
Labels: needs more information
