### ISSUE TITLE
Troubles with Routes on Cycling profile

### ISSUE THREAD

**Issue by Floreturns** [mapbox/mapbox-navigation-android#33] opened 2017-05-10 15:18 UTC
Hello MapBox !

**Platform: Android**
**Mapbox SDK version: 4.2.2**

I need to find a route for cycling users so my app is on Cycling profile, but this profile allow parking and private roads.

For now I use Driving profile to avoid these problems, but one way roads and cycling ways are not allowed in this mode.

Do someone have to solve this problem or someones know how to deal with it ?

![image](https://cloud.githubusercontent.com/assets/10733262/25904521/c7f6e05c-359f-11e7-884e-a5b54879b518.png)

Arrival Point before parking's exit :

![image](https://cloud.githubusercontent.com/assets/10733262/25904648/1f5b2c2c-35a0-11e7-9272-34fe332b9ddb.png)

Arrival Point after parking's exit :
![image](https://cloud.githubusercontent.com/assets/10733262/25904670/2fd94912-35a0-11e7-988f-88f63f8e819c.png)

**Comment by cammace** [comment] 2017-05-11 22:45
This issue seems to be a duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/24 which points out that we need to add support for multiple direction profiles (i.e. cycling). Going ahead and closing, but keep on the lookout for an update on this soon :)

**Closed by cammace** 2017-05-11 22:45 UTC
