### ISSUE TITLE
`Route Drawing Utility` examples crash 

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#4229] opened 2021-04-06 08:44 UTC
Examples crash

**Android API:** `24`
**Mapbox Navigation SDK version:** `v2.0.0-beta.4`

### Steps to trigger behavior

 1. run the `examples` module 
 2. scroll down to the bottom of the screens list
 3. click on `Route Drawing Utility`
 4. click `CLEAR POINT/LINE`
 5. run into the crash 
```
2021-04-06 11:52:24.264 2680-2680/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 2680
    java.lang.RuntimeException: Set source property "data" failed:
    Error: A line string must have two or more coordinate points.
    Value set: {"type":"Feature","geometry":{"type":"LineString","coordinates":[]}}
        at com.mapbox.maps.extension.style.sources.Source.updateProperty(Source.kt:99)
        at com.mapbox.maps.extension.style.sources.Source.setProperty$extension_style_release(Source.kt:83)
        at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.feature(GeoJsonSource.kt:474)
        at com.mapbox.navigation.examples.util.RouteDrawingUtil$clear$1.onStyleLoaded(RouteDrawingUtil.kt:119)
        at com.mapbox.maps.MapboxMap.getStyle(MapboxMap.kt:229)
        at com.mapbox.navigation.examples.util.RouteDrawingUtil.clear(RouteDrawingUtil.kt:118)
        at com.mapbox.navigation.examples.util.RouteDrawingActivity$initListeners$4.onClick(RouteDrawingActivity.kt:137)
        at android.view.View.performClick(View.java:6265)
        at android.widget.TextView.performClick(TextView.java:11157)
        at android.view.View$PerformClick.run(View.java:23764)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by Guardiola31337** [comment] 2021-04-06 12:03
Duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/4220

Closing.

**Closed by Guardiola31337** 2021-04-06 12:03 UTC
Labels: bug
