### ISSUE TITLE
onArrival() not triggered if the waypoint is really close after a turn

### ISSUE THREAD

**Issue by nagylilla96** [mapbox/mapbox-navigation-android#1267] opened 2018-09-06 12:04 UTC
**Android API:** 25
**Mapbox Navigation SDK version:** 18.0.0

### Steps to trigger behavior

 1. Place a marker really close to the end of a street, just after a turn
 2. Start a navigation with simulate(true) and make it stop at each waypoint
 3. Override the onArrival() method and when it gets called, display a dialog window asking whether you want to continue or not

### Expected behavior

When the user arrives to the waypoint, onArrival() gets called and in my case, a dialog gets displayed (like in the navigation app, where it asks you whether you want to continue to the next waypoint or not). This works with other markers, which are not placed like this.

### Actual behavior

onArrival() doesn't get called and the whole navigation blocks. You can see that the marker is really close to the end of the street, so probably the simulation doesn't reach the point when it's supposed to take a turn.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20059930/45155426-3e8a3800-b1db-11e8-95c7-30f5bdd14e28.gif)

![device-2018-09-06-134938](https://user-images.githubusercontent.com/20059930/45156069-58c51580-b1dd-11e8-8f0c-5d453e29b9b5.png)

**Comment by danesfeder** [comment] 2018-09-06 13:42
Hey @nagylilla96 this is a great catch - we recently started seeing this behavior as well after #943 landed.  Because the distance remaining on the route is used to trigger the final arrival banner instruction, we run into some reliability issues with routes such as the one you're demonstrating above. 

We will discuss a solution internally to further fortify this logic and then post back here.  Thanks for bringing this to us!

**Comment by nagylilla96** [comment] 2018-09-06 13:59
Thank you for your quick response, please keep me updated! :) 
Have a nice day!

**Comment by Guardiola31337** [comment] 2018-10-25 19:07
Hey @nagylilla96 👋 would you mind testing again with [`0.22.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.22.0)? A lot of our underlying route-following logic has been updated.

As indicated in https://github.com/mapbox/mapbox-navigation-android/pull/1039#issuecomment-420973061 I was able to reproduce this when testing [`WaypointNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/WaypointNavigationActivity.java) from the test app but not anymore so I believe OP should be fixed now. It'd be 💯 if you could report back confirming that the issue is gone. Thanks a lot!

**Comment by Guardiola31337** [comment] 2018-11-02 11:10
Hey @nagylilla96 going to close this as resolved by our latest release - please test and report back if you see the same behavior and we will dig further. Thanks!

**Closed by Guardiola31337** 2018-11-02 11:10 UTC
Labels: bug, navigation-ui, needs research
