### ISSUE TITLE
End of leg right after a turn triggers OffRoute

### ISSUE THREAD

**Issue by Grsmto** [mapbox/mapbox-navigation-android#274] opened 2017-09-27 13:32 UTC
Hi,
Currently the offRoute event is wrongly being triggered at the end of the first leg even tho user is still on the right path. I'm pretty sure it's a regression as this wasn't happening before.
You can test that issue using the `Mock Navigation` test activity and define 2 waypoints.

Thanks!

**Comment by danesfeder** [comment] 2017-09-27 17:17
Hey @Grsmto, 
We recently made some performance tweaks around decoding steps on new location updates, which may have caused this regression. Will look into it - appreciate the feedback!

**Comment by Grsmto** [comment] 2017-09-28 13:06
Hey @danesfeder , I think I know where it comes from: when user reaches the last step of a leg, [this line](https://github.com/mapbox/mapbox-navigation-android/blob/db573a217eaf6aa26de183f2e118a065f6535bed/navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java#L40) checks the distance to next step and defines if it's within the tolerated ratio or not. But the next step being the last one of the leg, has a null geometry, so then `userTrueDistanceFromStep(futurePosition, upComingStep)` returns `NaN` which creates the false positive. 
I think we should check if the next step is the last of the leg and not return offroute in this case (or retrieve the *real* next step (the first one of the  next leg).
Anyway I wish I could submit a PR but you probably have a better idea than me how to fix that properly!
Hope that could help.

**Comment by danesfeder** [comment] 2017-09-28 13:15
@Grsmto Great catch!  Please feel free to submit a PR and we can tweak if needed, but that sounds exactly what the issue is - appreciate your time debugging that

**Comment by Grsmto** [comment] 2017-09-28 16:00
So I tried to work on it to fix it but I'm getting more confused the more I look at it. I'm getting some crazy results on `userTrueDistanceFromStep(futurePosition, currentStep)` like above 100m. Which doesn't make any sense as I'm using the mock that is just following the path...So that should always be close to 0 in theory (especially with `noisyGps` to `false`). 
The offroute event gets triggered really randomly depending on the route, I wasn't able to understand the logic of why this was happening.

Hopefully you can understand it better than me! :(

**Comment by Grsmto** [comment] 2017-10-02 16:01
I finally figured out where the issue is coming from and how to reproduce it consistently:
The offroute is triggered when the end of a leg is place right after a step (like just after a turn for example). See screenshot attached:
![device-2017-10-02-165914](https://user-images.githubusercontent.com/527559/31086981-5054b978-a793-11e7-98c0-72f5f01ad7eb.png)

**Comment by danesfeder** [comment] 2017-10-02 16:31
@Grsmto Interesting - I haven't had a chance to debug this myself (appreciate you putting the time in).  Do you not think it's related to a null geometry like you originally mentioned?  

I was thinking in the scenario you are mentioning above, we don't make it into this `if` block because the upcoming step is null (we are at the end of the leg):

https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java#L40

We can check if the upcoming step is null and then, if it is, check if we have another leg.  Then use the first step of the next leg.  If both are null then we are at the end of the route.

**Comment by cammace** [comment] 2017-10-02 17:42
This is the same idea https://github.com/mapbox/mapbox-navigation-android/issues/238 will have @danesfeder.

**Comment by danesfeder** [comment] 2017-10-02 17:56
@cammace will we ever get to that point though at the end of a leg? because the upcoming step will be null

**Comment by cammace** [comment] 2017-10-02 18:03
If the users at the end of the leg but there's another leg with at least one step, we should factor that into account. That's what we do for other logic in the SDK at least.

**Comment by Grsmto** [comment] 2017-10-02 18:18
I think I got something :)

Actually offRoute gets triggered before `upcomingStep` is even `null`.
The problem that is happening here is that `upcomingStep` has a "wrong" value: when you reach the end of a step, the `upcomingStep` is the last step, whereas you're already on that position. Which means the calculation of the offRoute is wrong (as it calculates the step +1 with the `getFuturePosition` function).
What I did is I retrieve the first step of the next leg, if there is one, as the actual `upcomingStep`. You can check there: https://github.com/mapbox/mapbox-navigation-android/pull/279/commits/0435d3ebcbdb26fbbf3ffbe076cdbb3fcfc7dbcb

**Comment by cammace** [comment] 2017-10-06 15:37
I just tested this using the latest changes we've been making for the 0.6.2 release and wasn't able to reproduce the issue described. Chances are we somehow indirectly fixed the issue ¯\_(ツ)_/¯. Can you test on your end and confirm before I close this ticket?

**Comment by Grsmto** [comment] 2017-10-09 10:35
Seems I can still reproduce this issue. This is only happening when the end of leg is placed right after a turn.
I'll update the issue or close as there seem to be a few issues related to the offroute logic.

**Comment by cammace** [comment] 2018-01-22 02:38
@Grsmto, are you still seeing this issue using the latest SDK version?

**Comment by Grsmto** [comment] 2018-01-23 14:07
@cammace I just pulled the latest code from Master on my fork and tested again the MockNavigationActivity with the same setup and the off route is still being triggered.

My starting location is `51.51427783320443, -0.15708893537521362` if that can help.

**Comment by danesfeder** [comment] 2018-03-13 18:48
Fixed with #667

**Closed by danesfeder** 2018-03-13 18:48 UTC
Labels: bug
