### ISSUE TITLE
Failed to initialize NavigationViewModel#navigation, NullPointerException NavigationView#camera 

### ISSUE THREAD

**Issue by dahu3291** [mapbox/mapbox-navigation-android#985] opened 2018-06-01 06:57 UTC
I want to note that this problem wasn't occurring earlier in the day.

When I start my activity hosting the NavigationView, the screen is blank with the default style but no map, i.e a dark background with sound and feedback buttons visible. Upon panning then clicking  RE-CENTER the app crashes.

**Android API:** 27
**Mapbox Navigation SDK version:** 0.13.0

### Steps to trigger behavior

 1. Follow steps at https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/
 2. Run
 3. pan around blank screen then click RE-CENTER

### Expected behavior
Map visible with navigation started

### Actual behavior
I did a little debugging and found that my Activity was created, destroyed and created in quick succession. (Reason unknown, seems like just inflating the view with setContentView(R.layout.activity_navigation) will cause this to happen)

The real problem comes from a race condition between 
navigationView.onCreate(savedInstanceState);
navigationView.initialize(this);

    @Override
    public void onNavigationReady() {
        ....
        navigationView.startNavigation(options);
    }

Here is the timeline:
First time onCreate is called
// savedInstanceState = null;
navigationView.onCreate(savedInstanceState);
// navigationView#resumeState = false;

Second time onCreate is called
// savedInstanceState != null;
navigationView.onCreate(savedInstanceState);
// navigationView#resumeState = true;

Now onNavigationReady is called
navigationView.startNavigation(options);
...
navigationViewModel.initializeNavigation(options, navigationViewEventDispatcher);
...
if (!resumeState) { // resumeState=true, !resumeState = false
      locationEngineConductor.initializeLocationEngine(getApplication(), 
      options.shouldSimulateRoute());
      initNavigation(getApplication(), navigationOptions);
      navigationViewRouteEngine.extractRouteOptions(getApplication(), options);
}
...
initNavigationCamera();
camera = new NavigationCamera(map, navigationViewModel.getNavigation());

Problem initNavigation was never called!!! so navigation is null, camera is null

Here is the log:

                         FATAL EXCEPTION: main
                     Process: com.lookingbus.navigationmapbox, PID: 31675
                     java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.resetCameraPosition()' on a null object reference
                         at com.mapbox.services.android.navigation.ui.v5.NavigationView.resetCameraPosition(NavigationView.java:265)
                         at com.mapbox.services.android.navigation.ui.v5.NavigationPresenter.onRecenterClick(NavigationPresenter.java:20)
                         at com.mapbox.services.android.navigation.ui.v5.NavigationView$5.onClick(NavigationView.java:532)
                         at android.view.View.performClick(View.java:4785)
                         at android.view.View$PerformClick.run(View.java:19884)
                         at android.os.Handler.handleCallback(Handler.java:739)
                         at android.os.Handler.dispatchMessage(Handler.java:95)
                         at android.os.Looper.loop(Looper.java:135)
                         at android.app.ActivityThread.main(ActivityThread.java:5343)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at java.lang.reflect.Method.invoke(Method.java:372)
                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

Here is my code:

    public class NavigationActivity extends AppCompatActivity implements OnNavigationReadyCallback, NavigationListener {

    private static final double ORIGIN_LONGITUDE = -83.070208;
    private static final double ORIGIN_LATITUDE = 42.349201;
    private static final double DESTINATION_LONGITUDE = -83.070423;
    private static final double DESTINATION_LATITUDE = 42.357868;

    NavigationView navigationView;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        setTheme(R.style.Theme_AppCompat_NoActionBar);
        super.onCreate(savedInstanceState);
        Mapbox.getInstance(this, getString(R.string.access_token));
        setContentView(R.layout.activity_navigation);
        navigationView = findViewById(R.id.navigation_view);
        navigationView.onCreate(savedInstanceState);
        navigationView.initialize(this);
        
    }

    @Override
    public void onStart() {
        super.onStart();
        navigationView.onStart();
    }

    @Override
    public void onResume() {
        super.onResume();
        navigationView.onResume();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        navigationView.onLowMemory();
    }

    @Override
    public void onBackPressed() {
        // If the navigation view didn't need to do anything, call super
        if (!navigationView.onBackPressed()) {
            super.onBackPressed();
        }
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        navigationView.onSaveInstanceState(outState);
        super.onSaveInstanceState(outState);
    }

    @Override
    protected void onRestoreInstanceState(Bundle savedInstanceState) {
        super.onRestoreInstanceState(savedInstanceState);
        navigationView.onRestoreInstanceState(savedInstanceState);
    }

    @Override
    public void onPause() {
        super.onPause();
        navigationView.onPause();
    }

    @Override
    public void onStop() {
        super.onStop();
        navigationView.onStop();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        navigationView.onDestroy();
    }

    @Override
    public void onNavigationReady() {
        Point origin = Point.fromLngLat(ORIGIN_LONGITUDE, ORIGIN_LATITUDE);
        Point destination = Point.fromLngLat(DESTINATION_LONGITUDE, DESTINATION_LATITUDE);
        NavigationViewOptions options = NavigationViewOptions.builder()
                .origin(origin)
                .destination(destination)
                .directionsProfile(DirectionsCriteria.PROFILE_WALKING)
                .shouldSimulateRoute(true)
                .navigationListener(this)
                .build();

        navigationView.startNavigation(options);
    }

    @Override
    public void onCancelNavigation() {

    }

    @Override
    public void onNavigationFinished() {

    }

    @Override
    public void onNavigationRunning() {

    }

    }

**Comment by danesfeder** [comment] 2018-06-11 19:14
Hey @dahu3291, closing this ticket as a duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/1002.  Thanks again for your feedback!

**Closed by danesfeder** 2018-06-11 19:14 UTC
