### ISSUE TITLE
Missing translations in libandroid-navigation-ui

### ISSUE THREAD

**Issue by sarahthe** [mapbox/mapbox-navigation-android#598] opened 2017-12-15 12:41 UTC
The buttons in the navigation-ui are only available in English, translations are missing.
This includes the buttons for route issues as well as the buttons on screen (re-center, mute etc.).

![grafik](https://user-images.githubusercontent.com/27763767/34042482-342ac9ba-e19d-11e7-9b9f-87c31a93a7be.png)

**Comment by danesfeder** [comment] 2017-12-15 14:33
Thanks @sarahthe, you are correct here and we are currently prioritizing our localization work.  Please stay tuned  - as this progresses, I will update this ticket.

**Comment by 1ec5** [comment] 2018-01-18 19:26
A Transifex project was set up for this SDK in #28, but that was back before we added UI to the SDK.

/cc @langsmith

**Comment by langsmith** [comment] 2018-01-18 19:38
https://github.com/mapbox/mapbox-navigation-android/blob/master/.tx/config

**Comment by sstolz** [comment] 2018-02-06 14:40
Hi,

Don't know if my problem is the same but I try to have all my navigation in french (in a Kotlin application) and I've got :
- voice in french ;
- voice instruction mixed french / english (streets in french, instructions in english) ;
- instructions displayed in english ;
- the time of arrival is in 12h format instead of 24h ;
- distance en metric system ;
- all data in API response is in french (maneuver instructions and voice instructions announcement).

I've used directionsLanguage method of NavigationViewOptions : 

```kotlin
val options = NavigationViewOptions.builder()
        .origin(origin)
        .destination(destination)
        .awsPoolId(awsPoolId)
        .shouldSimulateRoute(simulateRoute)
        .directionsLanguage(Locale("fra"))
        .navigationOptions(navigationOptions)
        .build()
```
 
language and voiceUnits method of NavigationRoute

```kotlin
val navigationRoute = NavigationRoute.builder()
            .accessToken(Mapbox.getAccessToken())
            .language(Locale("fra"))
            .voiceUnits("metric")
            .profile(DirectionsCriteria.PROFILE_DRIVING)`
```

I've tried "fr" and "fr_FR" instead of "fra" but it changes nothing.

![screenshot_20180206-152432](https://user-images.githubusercontent.com/2139682/35865116-f670ce68-0b53-11e8-96c9-9ae34d8ddad5.png)

**Comment by devotaaabel** [comment] 2018-03-22 15:39
@sstolz Your issue should be fixed now. If it's not, go ahead and create a new issue because it's not related to this ticket.

**Comment by Guardiola31337** [comment] 2018-04-06 16:43
@sstolz feel free to comment/open a new ticket if you can still reproduce OP! Thanks again for reaching out and reporting your issue.

Closing as answered.

**Closed by Guardiola31337** 2018-04-06 16:43 UTC
