### ISSUE TITLE
Reroute event drops waypoint added

### ISSUE THREAD

**Issue by navdeepg** [mapbox/mapbox-navigation-android#1315] opened 2018-09-25 23:41 UTC
NAvigation drops added waypoint on reroute event.

Android API: 27
Mapbox navigation sdk: 0.19.0

### Steps to trigger behavior

 1. Add Current location as origin, Pickup as waypoint and dropoff as a destination in navigation view
 2.  Initially, It will show pick up on route to the destination 
 3. On reroute event, navigation shows the route from current to destination dropping pickup.

### Expected behavior
It should show pickup point after rerouting event as well
### Actual behavior
Pickup is not seen in navigation view after reroute

**Comment by Guardiola31337** [comment] 2018-09-26 09:07
Hey @navdeepg 👋 Thanks for reaching out and report your issue.

I've tested running the [`EndNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EndNavigationActivity.java) from the test app (which uses `NavigationView` and adds a pickup waypoint) and it worked as expected - after a couple of reroutes the pickup waypoint is still the "first" destination 👀 

![waypoints_working_after_reroute](https://user-images.githubusercontent.com/1668582/46069554-152a4f80-c17c-11e8-992b-cc57b57270b8.gif)

Could you add some more information for reproducing the crash (minimal example) or any other specifics around your test setup? Do you have some more information on used device? If there is any sample or pseudo code you can provide, that would be really helpful because without having additional information, I'm unable to reproduce.

**Comment by danesfeder** [comment] 2018-10-03 13:13
@navdeepg any updates here regarding this issue?

**Comment by danesfeder** [comment] 2018-11-09 15:18
@navdeepg are you still able to reproduce this?  A follow-up here would be appreciated.

**Comment by danesfeder** [comment] 2018-11-20 17:55
@navdeepg going to go ahead and close this as resolved.  If you continue to experience issues around this, please feel free to cut a new ticket - thanks!

**Closed by danesfeder** 2018-11-20 17:55 UTC
