### ISSUE TITLE
I got "Bad notification posted from package..." when start navigation.

### ISSUE THREAD

**Issue by LoveMobile** [mapbox/mapbox-navigation-android#186] opened 2017-08-29 17:42 UTC
Hi, MapBox Support Team.

I got "Bad notification posted from pakage..." when start navigation.
`@Override

    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {

        Log.e(TAG, "Get Route");

        Log.e(TAG, String.valueOf(response.body()));

        if (response.body() != null) {

            if (response.body().getRoutes().size() > 0) {

                DirectionsRoute route = response.body().getRoutes().get(0);

                // First run

                drawRoute(route);

                if (!running) {

                    ((MockLocationEngine) locationEngine).setRoute(route);

                }

                navigation.startNavigation(route);

            }

        }

    }`

I have two android device. 
One is Samsung Galaxy Note S3(Android 21), the other is Samsung Galaxy S6(Android 24).

Above crash was happened io S3, not happened in S6.

Could you let me know what is the solution of this crash?

Best Regards.

**Comment by cammace** [comment] 2017-08-30 00:35
Interesting, could you provide a bit more information for which version of the SDK you are using and the actual log when the crash occurs.

BTW, you should reverse this statement so the log happens after the null check.

```
Log.e(TAG, String.valueOf(response.body()));
if (response.body() != null) {
...
```

**Comment by cammace** [comment] 2017-09-05 20:59
I changed our remote views to use match_parent rather than wrap for the height in #205. Since I don't have an s3 and haven't been able to reproduce the issue I'm not sure if this resolves the issue you are seeing. Closing once merged but if you still have issues please comment on this ticket with additional information.

**Closed** 2017-09-06 19:38 UTC
Labels: - bug
