### ISSUE TITLE
Feature Request - Waypoints as "Vias"

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#875] opened 2018-04-23 09:05 UTC
We provide a series of Waypoints to determine the route we would like Mapbox to navigate. But this is only to ensure certain roads are used, etc.

It would be great if it was possible to have an option so that the waypoints are used to determine the route, but are not visible to the user - i.e. not included in the geometry or instructions, and there will just be one leg.

Ideally the option would be per waypoint, so that both could be used in a request.

**Comment by danesfeder** [comment] 2018-04-23 13:29
Hey @richjhart yeah I see what you mean here.  Have you checked out our [MapMatching API](https://www.mapbox.com/api-documentation/#map-matching)?  We actually just added support for usage in the Navigation SDK, so we are still working on getting some good documentation.  

You can convert a map matching response to a `DirectionsRoute` now with https://github.com/mapbox/mapbox-java/blob/master/services-matching/src/main/java/com/mapbox/api/matching/v5/models/MapMatchingMatching.java#L121-L132

**Comment by Danny-James** [comment] 2018-04-23 14:05
@danesfeder I'm following this as this is what I am using waypoint for at the moment.

**Comment by iosdbeyond** [comment] 2018-04-23 16:37
I'm working with @richjhartabove but the iOS app. Is there an equivalent
 iOS Swift function to convert a map matching response to a DirectionsRoute ? like the above

**Comment by danesfeder** [comment] 2018-04-23 17:04
@Danny-James this is a possible solution to #873 if you want to give that a shot.

@iosdbeyond Yes, iOS added support with https://github.com/mapbox/MapboxDirections.swift/pull/236 and just added their documentation with https://github.com/mapbox/MapboxDirections.swift/pull/269

**Comment by richjhart** [comment] 2018-04-24 09:02
@danesfeder Thanks for the tip on MapMatching - so far that seems to be working very well.

However, there is still one issue. Because the route doesn't know about waypoints at all now, if we chose to re-route due to being off course, it's going to skip all the previously defined waypoints and find the shortest/quickest route to the destination. I don't suppose there's a way of combining the two methods (i.e. instructions do not include waypoints, but routing does)?

Alternatively (or in the mean time), we might be able to do our own waypoint tracking, and when we need to re-route we could restart it buy making our own route request with the remaining waypoints. Is there a "clean" way of doing that?

**Comment by danesfeder** [comment] 2018-04-24 12:57
@richjhart are you using https://github.com/mapbox/mapbox-java/blob/master/services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java#L412-L428?

I think this may actually be a bug on our side though.  When we get the response from the map matching service, we [generate `RouteOptions`](https://github.com/mapbox/mapbox-java/blob/master/services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java#L208) and this is the object used when we re-route during navigation (to build the new request).  As you can see, we are formatting the coordinates here.  

This will cause issues I think on the nav side because these coordinates can be up to 100 and we don't use map matching in the nav SDK for re-route requests.  Going to look into this with our team.

**Comment by richjhart** [comment] 2018-04-24 13:06
@danesfeder Yes I see that that should in theory work - we just don't have re-routing on at the moment so I hadn't fully considered how it would work.

But yes I guess it will not only be too many points - but also because it doesn't use Map Matching in the new request, the coordinates will become waypoints I assume? (as you no longer have the waypoint list in the options)

**Comment by danesfeder** [comment] 2018-04-24 13:11
>  the coordinates will become waypoints I assume?
Yeah exactly, this being the main issue with the new requests ^

**Comment by richjhart** [comment] 2018-04-26 11:28
@danesfeder Is there any sort of estimate on when this might update: i.e. so that a route planned using Map Matching will reroute using Map Matching with the same options (minus the completed steps)?

Or, similar to an earlier question - what would be the cleanest way for us to re-request ourselves?
I'm thinking something along the following lines:
- allow redirection in general
- but always return false to allowRerouteFrom(), and separately make our own decision
- when we decide we should reroute, we generate a new Map Match, starting from the next step (or perhaps a little further), and inserting the current position as the first coordinate, and wait for the response
- Once we have the new route, end the navigation, without quitting
- Make a fresh call to startNavigation with the new route

Obviously I can test this, but I just wanted to check if that seems like the best approach?

**Comment by danesfeder** [comment] 2018-04-26 15:45
Hey @richjhart, given our current setup / constraints, I think your solution would be the cleanest.  You would always return `false` when `allowRerouteFrom()` is fired, but you would still use the callback as a cue to fetch a new Map Match just like you said. 

The tricky part here will be giving the new route to the `NavigationView`.  We designed it so that it can take multiple different routes while inflated.  So calling [`NavigationView#startNavigation`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L358-L371) again with the new route, should act just like a reroute request normally would, ignoring all other options in `NavigatonViewOptions` other than the route and if it should be simulated.  

Hope this helps!  Let me know if you have any other questions

**Comment by richjhart** [comment] 2018-04-30 11:12
@danesfeder Thanks for the advice. This did work pretty well - and yes calling startNavigation with the new route worked fine.

One more query on this, which is also related to #863, is it possible to tell the navigation engine to "jump" to a particular step. When re-routing (and in some other circumstances), we would like to provide a route which includes the sections already covered, but inform the turn-by-turn navigation that the user is already at step x? (or does it already jump to the nearest step at the start of navigation?).

Again, I can obviously test whether it does jump at the start, but don't know where to start on the other part.

**Comment by danesfeder** [comment] 2018-04-30 14:34
@richjhart That's another good question.  The route processing is currently set up to detect a new route, then reset the leg and step indices used for tracking user progress along the route: 
 https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java#L112-L118

I think this may cause some issues when the new route is passed in.  May I ask what the use case is with this?  Is it to show the same route line (or appear to) on the map even after re-routing?  

That being said, I think you should still give this a shot and see how the SDK reacts and if it adjusts to a user position that is not at the beginning of the route (my hunch is an immediate re-route though unfortunately).

**Comment by richjhart** [comment] 2018-04-30 15:15
@danesfeder There are basically two use cases we are looking at:
- one is just a nice-to-have when re-routing, so that after re-routing it shows where the user has been (so we would insert the current location instead of just putting it at the front of the remaining locations)
- the other is for offline restoration of a route when we can't (or just don't) request a new route but need to trigger a fresh startNavigation call

I did a short test earlier, and it began at the start of the route, but then seemed to "catch up". But I hadn't gone very far along the route so it might have just been lucky. I'll try a better test once the weather here improves slightly.

**Comment by danesfeder** [comment] 2018-05-01 17:18
@richjhart thanks, yeah please keep us posted on your testing results.  If needed, we can cut a ticket to start tracking this / discuss the expected behavior for passing in a route that has already been progressed along.

**Comment by richjhart** [comment] 2018-05-02 09:29
@danesfeder It does look as though the initial test wasn't really valid - as it was just close enough to happen to work (on each location update, we were close enough to the "next" step that it accepted it as step complete, and caught up).

I have modified (hacked) the library to get something that I think works, by just repeatedly calling a modified version of NavigationRouteProcessor.buildNewRouteProgress() - which always advances - at the start until we're at the right step. However, it required making a bunch of stuff public and also is on version 0.12.0, and I believe that code has already changed. Still, I'll give it a real try shortly and see what happens. I think someone with a better understanding of the library architecture could make the change properly much quicker than me!

**Comment by richjhart** [comment] 2018-05-02 12:38
@danesfeder I am having a serious problem with MapMatching at the moment. It's been working very well if I only provide 0 and the last index as waypoints. But if I try to add an intermediate waypoint (so first, middle, and last for example), I can only provide up to 10 coordinates in total, otherwise I get an internal server error.

e.g.:
This works (11 points, start and end as waypoints):
https://api.mapbox.com/matching/v5/mapbox/walking/-0.105939,51.500392;-0.107091,51.500244;-0.105304,51.498652;-0.104495,51.498395;-0.100916,51.49721;-0.099821,51.496703;-0.099486,51.49519;-0.096765,51.494553;-0.093852,51.4931;-0.092599,51.492057;-0.092854,51.490882?access_token=*<token>*&geometries=polyline6&overview=full&steps=true&bearings=%3B%3B%3B%3B%3B%3B%3B%3B%3B%3B&annotations=congestion&roundabout_exits=true&voice_instructions=true&banner_instructions=true&waypoints=**0;10**

As does this (10 points, 3 waypoints):
https://api.mapbox.com/matching/v5/mapbox/walking/-0.105939,51.500392;-0.107091,51.500244;-0.105304,51.498652;-0.104495,51.498395;-0.100916,51.49721;-0.099821,51.496703;-0.099486,51.49519;-0.096765,51.494553;-0.093852,51.4931?access_token=*<token>*&geometries=polyline6&overview=full&steps=true&bearings=%3B%3B%3B%3B%3B%3B%3B%3B%3B&annotations=congestion&roundabout_exits=true&voice_instructions=true&banner_instructions=true&waypoints=**0;5;9**

But this results in an internal server error (11 points, 3 waypoints):
https://api.mapbox.com/matching/v5/mapbox/walking/-0.105939,51.500392;-0.107091,51.500244;-0.105304,51.498652;-0.104495,51.498395;-0.100916,51.49721;-0.099821,51.496703;-0.099486,51.49519;-0.096765,51.494553;-0.093852,51.4931;-0.092599,51.492057;**-0.092854,51.490882**?access_token=*<token>*&geometries=polyline6&overview=full&steps=true&bearings=%3B%3B%3B%3B%3B%3B%3B%3B%3B%3B&annotations=congestion&roundabout_exits=true&voice_instructions=true&banner_instructions=true&waypoints=**0;5;10**

**Comment by danesfeder** [comment] 2018-05-02 19:49
@coxchapman see anything out of the ordinary with these requests containing waypoints?

**Comment by danesfeder** [comment] 2018-05-03 00:08
@richjhart we are looking into this on our end, it doesn't look like you are doing anything wrong with your requests.  Will follow up on this ticket when we are able to find the issue.  Thanks for your patience!

**Comment by danesfeder** [comment] 2018-05-16 19:44
Hey @richjhart, this was a bug with the API that was fixed - can you try again / see if you reproduce the same issue?

**Comment by richjhart** [comment] 2018-05-17 15:47
Further to the previous message, it doesn't appear to be related to the points being too close. I stripped out any points within 50m of each other, but it still has issues. I'm still putting together an example of where the strategy works, and where it doesn't - despite similar requests

**Comment by richjhart** [comment] 2018-05-18 10:10
@danesfeder I have investigated the issue further, and it seems there are some "blind spots" for map matching - and in fact it's when points are too far apart it can struggle (even if there's not a lot going on in between the points).

If, for example, I try to get a match from 51.466185, -0.101598 to 51.46152, -0.114159, it finds no routes (no error, just no routes).

But if I add in 51.465608, -0.102932, it now finds a route. What is more - that route is directly along a single road from origin to destination, and both the origin and destination are consecutive points returned on a previous map matching request.

For clarity, the two full requests (token removed) are:

No matches:
https://api.mapbox.com/matching/v5/mapbox/walking/-0.101598,51.466185;-0.114159,51.46152?access_token=<token>&geometries=polyline6&overview=full&steps=true&voice_instructions=true&banner_instructions=true&waypoints=0;1
Match found - 2 steps, depart and arrive only:
https://api.mapbox.com/matching/v5/mapbox/walking/-0.101598,51.466185;-0.102932,51.465608;-0.114159,51.46152?access_token=<token>&geometries=polyline6&overview=full&steps=true&voice_instructions=true&banner_instructions=true&waypoints=0;2

**Comment by richjhart** [comment] 2018-05-18 11:09
@danesfeder Another update. It appears that if I provide random timestamps (tried 10 seconds apart), it seems to find a match for the above ones. I will try that on a larger scale.

Note, however, the error I've just raised: https://github.com/mapbox/mapbox-java/issues/819
I'm currently having to use reflection to modify the timestamps string after building the request, which obviously isn't ideal (I tried just providing the string already formed, but that threw an error because it wasn't enough values).

**Comment by danesfeder** [comment] 2018-05-18 12:39
@richjhart thanks for really digging on this - I'll get eyes on this again from our directions team and thanks for mapbox/mapbox-java#819, I'll make sure that team is also aware of this issue.  Will keep you posted here.

**Comment by richjhart** [comment] 2018-05-21 12:17
@danesfeder I see that's already been merged, which is great!

Now that I have raised #958, I think that we now actually have a solution that works for us (using Map Matching, and manually making the re-route requests). It would still be a slight improvement for us to be able to have "invisible waypoints", but it isn't something that would now hold us up, so I don't know if you wanted that on the roadmap/keep this open, or if you wanted to close this one.

**Comment by danesfeder** [comment] 2018-05-22 12:45
@richjhart do you mind clarifying "invisible waypoints" - is this from a UI standpoint?  Not drawing the waypoint "dots" on the map along the route?  I apologize if I'm not following here.

**Comment by wbearand** [comment] 2018-05-23 08:59
I hope you guys don't mind if I add sth to this discussion as I am also interested in using an additional waypoint type: a certain competitor navigation sdk differentiates between STOP_WAYPOINT and VIA_WAYPOINT .

STOP_WAYPOINT:
A maneuver is generated for a STOP waypoint. After the STOP waypoint, route is allowed to continue in the opposite direction, i.e. to turn back.
During Guidance, "You have reached your stop-over" will be announced if supported by the selected voice skin. The first and the last waypoint to be used for route calculation must be of RouteWaypoint.Type.STOP_WAYPOINT type.

VIA_WAYPOINT:
No maneuver is generated for a VIA waypoint. After the VIA waypoint, route will continue in the same direction as when it's approached. Via waypoints will "force" the route to pass through them, but they will not cause any guidance, announcement or maneuvers.

https://developer.here.com/documentation/android-premium/topics_api_nlp_hybrid_plus/com-here-android-mpa-routing-routewaypoint-type.html#topic-apiref__via-waypoint
(hope it is ok that i share that link.)

So from my point of view it would be great to also have such VIA_WAYPOINTs in the mapbox navigation sdk, i think that is also what @richjhart means(of course please correct if not).

**Comment by richjhart** [comment] 2018-05-31 10:30
@danesfeder Apologies for the slow response here. The comment by @wbearand covers exactly what I was referring to. As per this thread, we can do most things by using map matching, but there are a couple of small things that would be better achieved with a VIA_WAYPOINT (even when using Map Matching)

**Comment by richjhart** [comment] 2018-07-05 10:45
@danesfeder Not sure where else to post this, so I'll just put it here.

A couple of days ago, we were having trouble with a map matching request. We narrowed it down to a simple request of:

https://api.mapbox.com/matching/v5/mapbox/walking/-0.08547498841778634,51.4991047809622;-0.08928,51.50073?access_token=<key>&geometries=polyline6&overview=full&steps=true&voice_instructions=true&banner_instructions=true&waypoints=0;1

And it returned no results (we also tried with timestamps provided, which has previously fixed issues, but it didn't work in this case).

But I was just getting ready to report the issue, and now the exact same request works - with or without any timestamps (I do these tests in Postman to ensure the request is identical). Has anything changed in the last day or so that would affect this? (Obviously it's good that it's working, just trying to understand why so we know if things will continue to be more stable)

**Comment by danesfeder** [comment] 2018-07-05 13:39
cc'ing @danpat here 👋 - does anything stand out to you that would cause this request to be unstable or inconsistent?

**Comment by richjhart** [comment] 2018-09-14 11:38
Hi @danesfeder I'm just wondering if anything is going on at the back end with Map Matching with regards to the issue I described above where a route is much more likely to be returned when we provide random (linear) timestamps along with the waypoints? On Android, it's not a big deal as we can simply always provide the timestamps and that seems OK as a workaround. But our iOS developer hasn't had the same luck and isn't able to enter the timestamps when making the request - as a result route and re-route requests are failing a lot more often on iOS.

**Comment by 1ec5** [comment] 2018-09-14 12:26
> But our iOS developer hasn't had the same luck and isn't able to enter the timestamps when making the request

It looks like our Swift directions library is missing that option: mapbox/MapboxDirections.swift#294.

**Comment by danesfeder** [comment] 2018-09-14 16:14
Hey @richjhart 👋 

>  I'm just wondering if anything is going on at the back end with Map Matching with regards to the issue I described above where a route is much more likely to be returned when we provide random (linear) timestamps along with the waypoints? 

@danpat @coxchapman Is there any work slated for the above on the Map Matching API?

**Comment by 1ec5** [comment] 2019-02-06 17:26
mapbox/mapbox-java#956 tracks a via waypoint option. Are any changes needed in the SDK proper, or can this issue be closed?

**Comment by Guardiola31337** [comment] 2019-03-01 16:32
Hey @richjhart @Danny-James @wbearand support for via / silent waypoints was added as https://github.com/mapbox/mapbox-java/pull/959 and https://github.com/mapbox/mapbox-navigation-android/pull/1733 landed 🎉 this is available in the latest versions of the SDK.

Could you bump to [`v0.30.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.30.0) and confirm that covers your requirements / use cases? Thanks a lot!

**Comment by 1ec5** [comment] 2019-03-05 18:15
Note that there’s a bug with via points when rerouting: #1781.

**Comment by schimini** [comment] 2019-06-16 11:16
Hello everyone, i started using mapbox 2 months ago and I've tried using silent waypoints. However, as stated by @1ec5, #1781  is still open and it really breaks this functionality for me. What would you recommend i do? Try to fix it? Wait?
Thanks for your time

**Comment by surendra4586059** [comment] 2019-11-06 13:52
dynamic waypoint  how to add in java script

**Comment by mhamdizo** [comment] 2020-02-28 21:17
when i make this call i get an internal server Error
{"message":"Internal Server Error"}
anyone can tell me what's wrong. 
Thanks 
`
https://api.mapbox.com/matching/v5/mapbox/driving/-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683578,45.514713;-73.683548,45.514664;-73.683563,45.514606;-73.683296,45.514397;-73.683060,45.514240;-73.683273,45.514023;-73.683693,45.513737;-73.684380,45.513218;-73.684975,45.512695;-73.685776,45.512119;-73.686646,45.511368;-73.687614,45.510586;-73.687851,45.510418;-73.687851,45.510376;-73.687965,45.510326;-73.688057,45.510246;-73.688065,45.510277;-73.688065,45.510231;-73.688423,45.510017;-73.689178,45.509357;-73.689987,45.508709;-73.690231,45.508472;-73.690956,45.507885;-73.691017,45.507835;-73.692047,45.507030;-73.692383,45.506802;-73.692551,45.506664;-73.692551,45.506664;-73.692917,45.506325;-73.693962,45.505478;-73.694801,45.504860;-73.695190,45.504574;-73.695435,45.504345;-73.696518,45.503490;-73.697380,45.502792;-73.697845,45.502483;-73.698135,45.502239;-73.698174,45.502205;-73.699165,45.501293;-73.699707,45.500969;-73.700241,45.500504;-73.700951,45.499893;-73.701622,45.499432;-73.702400,45.498795;-73.703300,45.498089;-73.704102,45.497471;-73.704193,45.497395;-73.705040,45.496719;-73.705254,45.496548;-73.705254,45.496548;-73.706070,45.495907;-73.706383,45.495800;-73.708229,45.496948;-73.709824,45.497959;-73.709969,45.498039;-73.709846,45.497902;-73.708366,45.496983;-73.707680,45.496525;-73.707108,45.496151;-73.705612,45.495205;-73.704384,45.494522;-73.704170,45.494774;-73.704239,45.494671;-73.704437,45.494556;-73.704689,45.494717;-73.704712,45.494709;-73.704697,45.494728;-73.704697,45.494736;-73.704697,45.494728;-73.704697,45.494701;-73.704704,45.494717;-73.704796,45.494717;-73.704712,45.494629;-73.704704,45.494629?radiuses=50;50;50;50;50;50;50;50;50;50;50;40;40;50;50;50;50;50;50;40;50;50;40;50;40;50;50;50;40;40;50;50;40;50;40;50;40;50;40;50;40;50;50;40;40;50;50;40;50;50;40;40;30;50;50;40;40;40;40;30;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50;50&geometries=geojson&overview=full&tidy=false&access_token=`

**Comment by Guardiola31337** [comment] 2020-06-01 18:08
Any updates here @RingerJK?

cc @1ec5

**Comment by RingerJK** [comment] 2020-06-02 10:39
native team scheduled to add support _via_ waypoints in current sprint

**Comment by RingerJK** [comment] 2020-08-31 12:11
A part of silent waypoints issue 
**cc** @Lebedinsky

**Comment by Guardiola31337** [comment] 2020-12-21 18:04
Where are we here @RingerJK? Could you provide an update when you have a chance? 🙏 

cc @Lebedinsky

**Comment by RingerJK** [comment] 2020-12-22 11:56
we provide support of silent(via) waypoints: https://github.com/mapbox/mapbox-navigation-android/pull/3581(fix with reroute issue when we use silent waypoints), https://github.com/mapbox/mapbox-navigation-android/pull/3497(the instance how to use silent waypoints).
We should be good to close the issue.

cc @Guardiola31337 @richjhart

**Closed by RingerJK** 2020-12-22 11:56 UTC
Labels: feature
