### ISSUE TITLE
Turn by turn directions not announced in Samsung Galaxy S8 and other / latest Samsung Galaxy devices.

### ISSUE THREAD

**Issue by milanrathod87** [mapbox/mapbox-navigation-android#1812] opened 2019-03-12 13:10 UTC
**Android API:** 26
**Mapbox Navigation SDK version:** 0.31.0

**mapbox-android-sdk:** 6.7.2'
**mapbox-android-navigation:** 0.31.0'
**mapbox-android-navigation-ui:** 0.31.0'

**Device Information:**

**model:** sm-g950u
**Device:** Galaxy s8
**Hardware:** REV1.0
**OS:** G950USQU5CRL2 // 8.0.0

### Steps to trigger behavior

 1. Set ride from pickup to drop off
 2. Updating route from driver location to drop-off location
 3. Turn by turn navigation sound is not working in Samsung Galaxy S8 and other / latest Samsung Galaxy devices.

### Expected behavior
Turn by turn navigation sound must be announced in Samsung Galaxy S8 and other / latest Samsung Galaxy devices.

### Actual behavior
Turn by turn navigation sound is not announced in Samsung Galaxy S8 and other / latest Samsung Galaxy devices.

**Comment by danesfeder** [comment] 2019-03-13 17:55
Hey @milanrathod87 👋 thanks for the feedback here.  Do you mind testing this locally with simulation enabled?  Then we can check and see if there are any error logs in `logcat` that may be able to help us here.  Thanks!  (in the meantime we are going to test with >= S8 devices as well).

**Comment by milanrathod87** [comment] 2019-03-15 05:06
Hi Danesfeder,
Thanks for your response.

Are you asking to provide you error logs with simulation enabled? 
Also, just want to inform you that this issue has been reported by client and I don't have Samsung Galaxy >= S8 device. In rest of the devices functionality works as aspected.

So it would be great if you test on that device please.

Thank you.

**Comment by milanrathod87** [comment] 2019-03-15 05:07
Hi Danesfeder,
Thanks for your response.

Are you asking to provide you error logs with simulation enabled? 
Also, just want to inform you that this issue has been reported by client and I don't have Samsung Galaxy >= S8 device. In rest of the devices functionality works as aspected.

So it would be great if you test on that device please.

Thank you.

**Comment by milanrathod87** [comment] 2019-03-19 07:27
@danesfeder , any update on this? 
Client is very frustrated because of this issue and they have MapBox subscription. Please do the needful ASAP.

Thank you.

**Comment by danesfeder** [comment] 2019-03-19 12:22
@milanrathod87 we have no been able to reproduce this on our end unfortunately (tested with Galaxy S8) - voice announcements were being triggered as expected.  We will continue to try to reproduce on other Samsung devices.  Thank you for your patience.

**Comment by milanrathod87** [comment] 2019-03-28 05:33
@danesfeder thanks for your efforts and the update. Do you want the steps with screenshots about how did we integrate the mapbox navigation?

**Comment by danesfeder** [comment] 2019-03-28 12:11
@milanrathod87 some code snippets from your Mapbox implementation would be great.  Anything to give us more information to reproduce here.  Thanks!

**Comment by Guardiola31337** [comment] 2020-07-08 14:00
@JunDai could we check if this would be an issue in `1.0`?

cc @abhishek1508

**Comment by abhishek1508** [comment] 2020-07-13 18:28
Let's verify.
cc @JunDai @cafesilencio @langsmith

**Comment by langsmith** [comment] 2020-08-03 18:20
We'll keep an eye out for this in future Nav UI SDK versions, but I'm going to close this ticket. 

We can't reproduce this issue and `0.31.0` is much older than the current stable `0.42.6`. The 1.0.0 Nav UI SDK is going to be available soon anyway.

@JunDai  has Samsung devices and he mentioned that he's never missed voice instruction on his Samsung device(s).

**Closed by langsmith** 2020-08-03 18:20 UTC
Labels: bug, needs investigation, topic: instructions, topic: voice
