### ISSUE TITLE
JNI ERROR (app bug): weak global reference table overflow (max=51200)

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-navigation-android#1450] opened 2018-10-23 13:23 UTC
during navigation we got weird crash bug.

this happens with original sdk not with **CUSTOM BUILD** 

```
y A/zygote: runtime.cc:542] Runtime aborting...
652 A/zygote: runtime.cc:542] 
652 A/zygote: runtime.cc:550] JNI ERROR (app bug): weak global reference table overflow (max=51200)
A/zygote: runtime.cc:550] weak global reference table dump:
A/zygote: runtime.cc:550]   Last 10 entries (of 51200):
A/zygote: runtime.cc:550]     51199: 0x14500000 java.lang.Thread
A/zygote: runtime.cc:550]     51198: 0x144c0000 java.lang.Thread
653 A/zygote: runtime.cc:550]     51197: 0x14480000 java.lang.Thread
653 A/zygote: runtime.cc:550]     51196: 0x14440000 java.lang.Thread
653 A/zygote: runtime.cc:550]     51195: 0x14400000 java.lang.Thread
653 A/zygote: runtime.cc:550]     51194: 0x143c0000 java.lang.Thread
653 A/zygote: runtime.cc:550]     51193: 0x14380000 java.lang.Thread
653 A/zygote: runtime.cc:550]     51192: 0x14340000 java.lang.Thread
653 A/zygote: runtime.cc:550]     51191: 0x142c0000 java.lang.Thread
653 A/zygote: runtime.cc:550]     51190: 0x14300000 java.lang.Thread
653 A/zygote: runtime.cc:550]   Summary:
653 A/zygote: runtime.cc:550]      7261 of java.lang.Class (7261 unique instances)
653 A/zygote: runtime.cc:550]       137 of java.lang.Thread (137 unique instances)
653 A/zygote: runtime.cc:550]        33 of java.lang.DexCache (33 unique instances)
653 A/zygote: runtime.cc:550]         7 of dalvik.system.PathClassLoader (2 unique instances)
653 A/zygote: runtime.cc:550]         2 of com.mapbox.mapboxsdk.maps.NativeMapView (2 unique instances)
653 A/zygote: runtime.cc:550]         2 of com.mapbox.mapboxsdk.maps.MapView$4 (2 unique instances)
```

**Comment by Xgamefactory** [comment] 2018-10-26 14:35
this crash still happens ? dont get why this issue ignored.
This is mapbox engine crash so it would be nice if some one from team make an attention.

**Comment by danesfeder** [comment] 2018-10-29 13:51
Hey @Xgamefactory we will have a look at this, thank you for your patience.  

@mapbox/maps-android could this be related to Navigation SDK usage of the Maps SDK?  Any ideas where we could be causing this in our code?  Thanks!

**Comment by danesfeder** [comment] 2018-10-29 14:21
@Xgamefactory @ohyooo after syncing with the Maps team on this, we are going to close this as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/13107.  This seems to be a maps-related issue.  

It also seems this issue occurs at random, but if you're able to provide steps to reproduce consistently, we'd really appreciate it.  Thanks for your patience.

**Closed by danesfeder** 2018-10-29 14:21 UTC
